### ISSUE TITLE
App version video quality issue

### ISSUE THREAD

**Issue by fireattack** [instaloader/instaloader#1022]
In some previous PR and commits (#712, #630, etc.), we introduced the feature that we choose to download the media served to app client (instead of the ones served for web), since they typically have higher resolution.

This still remains true, but the app version tends to have slightly lower quality. This was noted before, but the difference was small. Only recently, I noticed that the quality difference sometimes is very huge, especially for videos. 

I started to think, should we really download the app version despite having higher nominal resolution?

Let's take this example: https://www.instagram.com/p/CLHoAQpCI2i/
* The web version is 640x480 875KB.
* The app version is 720x540, but only 240KB.

And if you compare the two side by side, it is clear that the app version is *awful*:

Web:
![image](https://user-images.githubusercontent.com/4130991/107616002-ced1d000-6c12-11eb-863c-ab518c7d1537.png)
App:
![image](https://user-images.githubusercontent.com/4130991/107616028-d6917480-6c12-11eb-9e6d-14bd3b290138.png)

(Just to make it clear: it's not always the case. Sometimes the app version is still better; sometimes the two videos are identical. So the whole situation is more complicated and not black and white)

As the one who suggested this into instaloader to begin with, I feel responsible to improve this. Like adding an option, or do it more smartly. But I would like to hear your opinion first.

Thanks!

**Comment by aandergr** [comment]
Thanks for reporting this!

I noticed that in that post, the field `video_versions` contains three versions (type 101, type 102, type 103). Type 102 and 103 are identical, 101 has an inferior quality, all have 720x540 resolution. Instaloader currently loads type 101, which is the worst quality of all the available video versions. The web version has 640x480 resolution, but has a better bitrate (845 kb/s) than type 102/103 (586 kb/s). All 3 versions (101 / 102=103 / web) use the same codec (AVC).

It's probably hard to decide a good strategy for Instaloader here. Maybe what we could do, given that they all use the same codec (do they?), is that we check all available versions, or at least the web version and the type 103 version, and keep the one that has the largest file size, hence the highest bitrate and the best quality regardless of the resolution.

Also, it might be good to let the Post structure expose all available video versions via attributes, so that the user can choose when using Instaloader as a module.

**Comment by schleeb** [comment]
This might not be particularly helpful, especially since I'm not sure how you'd be able to account for it, and certainly don't know much about most of this, but is it possible the discrepancy is tied whether or not the video was recorded w/ IG as opposed to uploaded to it? Maybe experiment a bit?

**Comment by fireattack** [comment]
Finally have some time to deal with this. The behavior of IG constantly changes, so I would re-try the example post mentioned above to see if anything changed first.

Now, in one attempt, I have the following files found from their APIs:

video_url in web API: 
* `148185058_3613371398759511_1428089393759100272_n.mp4`, 720x540,  239 KB

From `self._iphone_struct['video_versions']`:

* type 101: `148185058_3613371398759511_1428089393759100272_n.mp4`, 720x540, 239 KB (same as web one)
* type 102: `147921149_901285143979896_5855426601976176308_n.mp4` , 720x540, 606 KB
* type 103: `147921149_901285143979896_5855426601976176308_n.mp4` , 720x540, 606 KB (same as type 102)

In summary, they all serve the same resolutions now, no more 640x480 875KB variant. And web version now is the same as type 101. Type 102 (=103) has the best quality.

I also noticed you can get more variants from the `video_dash_manifest` in web API, and there are four of them:

* `147443688_171418268077432_595353563536612094_n.mp4`, 720x540, 1.29 MB
* `149245500_226051462569765_1149311680337323135_n.mp4`, 490x368, 93 KB
* `146735039_411063413318353_5096869982369914540_n.mp4`, 720x540, 217 KB 
* `148582455_2912281075669375_4009681277085741574_n.mp4`, 720x540, 557 KB 

To compare these variants before downloading, however, we need to know their parameters.

For the web version, I didn't find a way to get its bitrate/filesize/dimension from metadata
For iPhone versions, you can get width and height but again, no bitrate/filesize info.
For MPD versions, you can get width, height, bitrate. 

But I don't think it's guaranteed to get the full video from MPD. This one is short enough so the baseURL is full, but if the video is longer it could be just the first segment if I understand MPD right. 

And the file downloaded is kinda missing some metadata headers due to likely the same reason, its resolution and duration can be recognized by Windows at least). Perceptually, I don't find the 1.29 MB one from MPD, while obviously encoded differently, any better than 606 KB version from iPhone API. Therefore, I don't plan to use anything from MPD at the moment

So, my question is:
* Can we afford to use something like `requests.get(url, stream=True).headers['Content-length']` to get the filesize of each?
* If not, one improvement I can do immediately is sort the  `self._iphone_struct['video_versions']` by width and then if equal, pick the *last one* (which seems to have the best quality.)

**Comment by fireattack** [comment]
More on DASH/MPD: according to an expert, it's actually always just one segment; but the audio track (if any) is separate so you have to mux them yourself.

**Comment by aandergr** [comment]
Nice, thanks for doing further research on this!

> * Can we afford to use something like `requests.get(url, stream=True).headers['Content-length']` to get the filesize of each?

I think we can afford that; to my knowledge there is no rate limiting on the CDN. Instead of `requests.get` we might better do a `requests.head` because it might be faster.

Otherwise, if this turns out to be not feasible, just using type 103 seems a similarly-well way to go.

**Comment by 89z** [comment]
This thread is very helpful. However can you clarify how you are getting the Web media? Are you just scraping the HTML? I didnt see any API for that.
