### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by Rcola1987** [instaloader/instaloader#106]
Is there a way that you can update the README.rst on Github to include a windows install section?
If you could it would remove some confusion with runtime errors on the windows platform.

Things that would be nice if they were added there:
1. Software Prerequisites (Python 3.6 for windows and Microsoft C++ Redistributable 2013) ** This is For Windows 7 64bit Don't know if windows 10 has different requirements
2. Add links to these resources to make it much easier for more basic users to find the correct files.

Seperate form the windows related items can you add in the README.rst the --password cli argument? Until i dug around i didn't even know it existed.

Thanks again for a excellent program.

**Comment by aandergr** [comment]
(related to #88, where I listed the issues I noticed about our documentation)

Thanks for these suggestions! We are working on improving the documentation for the upcoming Instaloader-v4, where it is really helpful to get some feedback by readers.

Some comments:
- We discourage from using `--password`, which is why we nowhere promote it. When it is used, the password becomes part of the command line and is visible a) in the command prompt and b) (much worse) in `top` or `ps` (programs similar to the Windows Task Manager) where all running applications with their command line and resource usage are listed. The latter makes it very insecure on (at least) Linux, where on a computer that is used by multiple users everyone can see the other users' application with their command line and hence the password. The preferred way is `instaloader --login USERNAME [--sessionfile SESSIONFILE]` to create and reuse a session file, which is per default stored in a secure place with rightly set file permissions.
- The `README.rst` on Github is merely a short introduction to what Instaloader is, mainly listing its features and giving a brief usage introduction, to attract people if they see it may help solve their problem. We consider https://instaloader.github.io/ as the main entry point, where we have a better control about the contents, how they are presented and internally linked. However, that site certainly needs some rework, too. Nevertheless, we probably should extend the installation section in `README.rst` or at least guide the reader to our installation section in our documentation.
