### ISSUE TITLE
the Basic Usage portion in the documentation could be improved in the following way

### ISSUE THREAD

**Issue by ryq99** [instaloader/instaloader#1064]
**Issue:**
the current command is shown as:

`instaloader profile [profile ...]`

which could be a little  confusing because if I'd like to get user 'JohnDoe', I initially tried instaloader profile [JohnDoe], instaloader profile [JohnDoe_1, JohnDoe_2], etc... 

**Propose:**
a better way is to separate the above command into 2, one is to scrape a single user, and the other is to scrape a list of users:

`instaloader profile`

and

`instaloader profile_1 profile_2`

**Comment by Thammus** [comment]
Enclosing arguments with `[` and `]` is a well-known notation to denote them as optional. The syntax `instaloader profile [profile ...]` follows exactly the example from Python's ArgumentParser documentation:
https://docs.python.org/3/library/argparse.html#usage
Especially the reuse of the same argument name is perfectly in accordance.
We do not want to deviate from the current description, because it follows a well established convention.
