### ISSUE TITLE
--fast-update, but without the need to keep downloaded files

### ISSUE THREAD

**Issue by ekalin** [instaloader/instaloader#1122]
**Provide us a use case of the feature**
`--fast-update` can be used to download only new posts, but it requires that the downloaded files are kept (actually only the most recent). I'd like a feature that allows one to download only new posts, but the file can be deleted/moved after looking at them.

**Describe the solution you'd like**
One possibility would be store the timestamp at which each profile was last scraped in a file. In the next run, only media newer than that timestamp are downloaded, and the timestamp is updated.

**Describe alternatives you've considered**
I guess this could be another project that handles the saving of timestamps, using instaloader as a library, something like the example in https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period. However, looking at the actual code for instoader (functions such as `posts_download_loop`) it seems it does quite a lot more than that simple exemple, such as error handling, rate limiting, and so on, so I see value in having this feature built-in in instaloader.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

As I matter of fact, I have written a proof of concept that does just that. It's working for posts and stories. If there's interest in this feature, I could try to enhance to also suports highlights, igtv, etc, and add documentation

**Comment by aandergr** [comment]
I think that in general this is a good idea and we will be happy to review a pull request for this.

There might be some caveats though:
- The timestamps are not necessarily monotonous. They are for profile feeds; but e.g. for hashtag feeds, it has been observed that the posts are not strictly ordered from newest to oldest (#666). It might be advantageous to store a list of ids or shortcodes of downloaded media instead. Timestamps on the other hand have the advantage of giving the user an easy way to download only posts that have been posted after a certain date.
- Changing the behavior might always break compatibility with existing software that uses Instaloader. Maybe we could enable this new mechanism with a separate flag, rather than changing what `--fast-update` does. 

> However, looking at the actual code for instoader (functions such as `posts_download_loop`) it seems it does quite a lot more than that simple exemple, such as error handling, rate limiting, and so on, so I see value in having this feature built-in in instaloader.

Actually rate limiting is included in the snippet. However I fully agree that posts_download_loop does a lot more than the cited example and that there is value in having this feature built-in.
