### ISSUE TITLE
Instaloder Instagram CDN CORS Error: blcoked_by_response - same-origin

### ISSUE THREAD

**Issue by OfirPearl** [instaloader/instaloader#1154]
Hi All, I'm using Instaloader python module for the past few months now to scrape posts data for my website. A python script scrapes data (including post's image - post.url, and user's profile pic - post.owner_profile.profile_pic_url) into a database and then i directly use post.url in an <img> tag SRC attribute on my site..
It all worked fine until a month ago, when I started getting CORS errors saying I can't display Instagram images from a different domain.
Error: 

![IG_CORS_ERROR](https://user-images.githubusercontent.com/63124838/119974692-a4d3cc00-bfbd-11eb-8a2d-3166a9d1c40f.png)
![IG_CORS_ERROR2](https://user-images.githubusercontent.com/63124838/119974695-a56c6280-bfbd-11eb-99c0-38ceba2bbdae.png)

Is there a way to redefine a cross-origin-resource-policy or something like that in order to display the scraped images this way? 
Have I done something wrong or did Instagram just changed their API policy?

Thank you in advance!

@Instaloader
@aandergr 
@Thammus

**Comment by kallewesterling** [comment]
I don't believe this has to do with the `instaloader` module but rather is a problem in your browser trying to access images on Instagram's CDN (that has a `cross-origin-resource-policy` set to `same-origin`). You can read more about [CORP here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)) and if you're trying to build an API or so, to access the database you're referring to in your message, [this](https://www.moesif.com/blog/technical/cors/Authoritative-Guide-to-CORS-Cross-Origin-Resource-Sharing-for-REST-APIs/) might be a helpful resource.

I suggest this issue is closed.
