### ISSUE TITLE
4.0.1 stops while downloading the list of followees

### ISSUE THREAD

**Issue by gituzzer** [instaloader/instaloader#118]
I've got a bit more than 2500 followees
I'm running the following command.
instaloader.py -l instauser -p instapasswd @instauser --no-captions --fast-update --stories-only

With 4.0.1, instaloader starts downloading the list of followees before iterating through them, but the retrieval stops back to prompt after a few "JSON Query to graphql/query: 429 Too Many Requests".
With 4.0.0, instaloader retrieves the list OK and proceeds to the story download iteration phase for each profile OK

Reproducible in Windows and Linux.

Comparative logs attached:
[4.0.1-ERROR.txt](https://github.com/instaloader/instaloader/files/1998249/4.0.1-ERROR.txt)

**Comment by mullier** [comment]
And even when managing to begin downloading stories, it soon enough gives the "JSON Query to graphql/query: 429 Too Many Requests" error, too, no matter what I've tried. I don't use Instagram anywhere else during the download process and pauses are continuously made during it, but in spite of all that, the script still inevitably stops working after a few dozens of profiles. The error is triggered, and the script just keeps showing it every time it tries to download stories from each next profile.
However, weirdly enough, version 3.3.10 still downloads stories just fine, so I had to switch back to it for now. It does everything real fast, with my ~350 followees, finishes in about an hour, with no errors. It just works great, as if the request limit doesn't even exist or affect it at all. But starting with version 4 and up, there definitely were some changes made to how stories, and probably everything else, is downloaded, and I think, unfortunately, it was for the worst and needs some fixing.

**Comment by mullier** [comment]
And even when managing to begin downloading stories, it soon enough gives the "JSON Query to graphql/query: 429 Too Many Requests" error, too, no matter what I've tried. I don't use Instagram anywhere else during the download process and automatic pauses are continuously made during it, but in spite of all that, the script still inevitably stops working after a few dozens of profiles. The error is triggered, and the script just keeps showing it every time it tries to download stories from each next profile.
However, weirdly enough, version 3.3.10 still downloads stories just fine, so I had to switch back to it for now. It does everything real fast, with my ~350 followees, finishes in about an hour, with no errors. It just works great, as if the request limit doesn't even exist or affect it at all. But starting with version 4 and up, there definitely were some changes made to how stories, and probably everything else, is downloaded, and I think, unfortunately, it was for the worst and needs some fixing.

**Comment by mullier** [comment]
And even when managing to begin downloading stories, it soon enough gives the "JSON Query to graphql/query: 429 Too Many Requests" error, too, no matter what I've tried. I don't use Instagram anywhere else during the download process and automatic pauses are continuously made during it, but in spite of all that, the script still inevitably stops working after a few dozens of profiles. The error is triggered, and the script just keeps showing it every time it tries to download stories from each next profile.
However, weirdly enough, version 3.3.10 still downloads stories just fine, so I had to switch back to it for now. It does everything real fast, with my ~350 followees, finishes in about an hour, with no errors. It just works great, as if the request limit doesn't even exist or affect it at all. But starting with version 4 and up, there have definitely been some changes made to how stories, and probably everything else, is downloaded, and I think, unfortunately, it was for the worst and needs some fixing.

**Comment by Thammus** [comment]
Version 4.0.1 stopped working because Instagram tightened their rate limits again to 20 queries per 11 minutes which had been respected in version 4.0.

In version 3.x, some strange queries to URLs used for mobile apps were used to obtain the story data. Although these queries are more relaxed regarding rate limits, they are harder to reverse engineer and therefore harder to debug if something goes wrong or changes on server side. Hence, our design decision for version 4 was to better mimic the browser behaviour for obtaining stories which results in more usage of GraphQL queries. Another benefit of the GraphQL data is that it better fits into our new class structures. These advantages overweight the minimal longer waiting times and we will not return to the version 3 mechanisms without convincing reasons.

Instaloader version 3.3 has reached its end-of-life and we will not support it any longer.

Moreover, if you only want to download stories: 
As @aandergr stated in issue #112 and added to the [documentation](https://instaloader.github.io/cli-options.html#cmdoption-stories-only):
> If possible, use `:stories` target rather than `--stories` with all your followees. `:stories` uses fewer API requests.
