### ISSUE TITLE
iterator_xxxxxxxx.json.xz is ignored when session file and account is changed

### ISSUE THREAD

**Issue by netherlink117** [instaloader/instaloader#1231]
Is this an expected behavior when you switch session files and accounts?

A bit of context:
I crated a temporal account on IG after a "to many request" error on a profile, and then loged in on instaloader using a different session file for the new account.
I could not complete the process because the iterator file was ignored in several tries with the new session file.
By now I can say that I just had to wait about 24 hours to be able to use the old session file again.
Then, with the old session file, the "iterator_xxxxxxxx.json.xz" was used and removed...
Is this an expected behavior when you switch session files and accounts?

**Comment by aandergr** [comment]
Yes, only resume files with matching login names are considered.

We decided to not allow resuming download loops between accounts because the information needed for resuming a download may be private in the sense of being associated to a certain account. This becomes clear when thinking about looping through a private profile that is followed by one account but not by another one. Sharing resume information between these accounts would very likely lead to a 'suspicious activity' ban. With Instaloader being open source, it is of course possible to remove the same-account-check in Instaloader's [nodeiterator.py](https://github.com/instaloader/instaloader/blob/master/instaloader/nodeiterator.py). 

(https://github.com/instaloader/instaloader/issues/855#issuecomment-727224264)

**Comment by netherlink117** [comment]
It's nice to know. Question cleared, thanks.
