### ISSUE TITLE
HTTP 429 error when trying to get the followers

### ISSUE THREAD

**Issue by WST** [instaloader/instaloader#128]
I’m experiencing a weird issue, similar to #118  when trying to get list of my followers from Python code.

```python
profile = instaloader.Profile.from_username(instagram.context, '*********')
followers = [{'username': i.username, 'full_name': i.full_name} for i in profile.get_followers()]
```

How it’s even possible to get this error (429 too many requests) when doing such a simple job? Isn’t it doable in 1-2 requests?

**Comment by aandergr** [comment]
Obtaining followers takes one request per 50 users, and currently the limit is 20 requests per 11 minutes. In my experiments, the limit is correctly set and your code works.

Does this problem still persist? Do you use the current Instaloader version?

**Comment by WST** [comment]
I’ve installed it into a virtualenv using pip the same day when posted the issue. However, your explanation makes sense, the limits for number of users and number of requests are surprisingly low, and I think I could easilly reach it, by browsing Instagram manually from the same IP at the same time.

**Comment by aandergr** [comment]
A general note about the notorious **429 - Too Many Requests**: Instaloader has a logic to keep track of its requests to Instagram and to obey their rate limits. Since they are nowhere documented, we try them out experimentally. However, we have a daily cron job running to confirm that Instaloader still stays within the rate limits. Nevertheless, the rate control logic assumes that
- at one time, Instaloader is the only application that consumes requests. I.e. neither the Instagram browser interface, nor a mobile app, nor another Instaloader instance is running in parallel,
- no requests had been consumed when Instaloader starts.
The latter one implies that restarting or reinstantiating Instaloader often within short time is prone to cause a 429. When a request is denied with a 429, Instaloader retries the request as soon as the temporary ban is assumed to be expired.
