### ISSUE TITLE
Best way to avoid time-outs when downloading multiple "post types" (--igtv, --highlights, --story)

### ISSUE THREAD

**Issue by atmos-o** [instaloader/instaloader#1313]
Does running `instaloader` one at a time for each "post type" flag (e.g. `instaloader --igtv` & `instaloader --highlights` & `instaloader --story`) have the same amount of http requests as running it all in one go ('instaloader  --igtv -highlights --story`) ?

At the moment I have a script in which I'm calling `instaloader` each time depending on what I want to include in the download to save it in separate locations. But I think there may be a way for me to do it all in one go & still have post types seprated into different locations accurately. 

But if I still come across the "too many http requests" issue at the same rate, then there's no point in me racking my brain to make it work.

**Comment by ekalin** [comment]
If you run instaloder twice for different media types, there'll be at least one extra request, since the profile must be fetched. But I think that the profile fetching is unlikely to make a significant difference for rate limiting.

However, instaloader keeps track of requests and tries to slow down when the limit is being reached, but this only works in a single run. If you run instaloader again, it starts counting requests from zero; requests from the previous run are not considered. That increases a lot the chances of getting a 429 error.
