### ISSUE TITLE
Some commands don't download content from a renamed account

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#1325]
**Describe the bug**
Instaloader wasn't able to download posts for a renamed account using `posts.txt` and apparently `highlights.txt`. I run everything as cronjobs.

posts.txt (runs every 2 hours, no sign of a 6 hour old post)
```
--igtv
--no-video-thumbnails
--no-compress-json
--filename-pattern={date_local:%y%m%d_%H꞉%M꞉%S} {profile} [{shortcode}]
profile1

```

highlights.txt (runs every 8 hours, probably doesn't work either)
```
--no-profile-pic
--no-posts
--highlights
--geotags
--igtv
--no-video-thumbnails
--no-compress-json
--filename-pattern={date_local:%y%m%d_%H꞉%M꞉%S} {profile} [{shortcode}]
--fast-update
profile1
```

stories.txt (runs every 30 min, downloaded after renaming as expected)
```
--no-profile-pic
--no-posts
--stories
--geotags
--no-video-thumbnails
--no-compress-json
--filename-pattern={date_local:%y%m%d_%H꞉%M꞉%S} {profile} [{shortcode}]
--fast-update
profile1
```

**Expected behavior**
Everything available at the moment would be redownloaded, albeit with a different profile in the filename.

**Instaloader version**
4.5

**Additional context**
While `stories.txt` worked and renamed directory to 'profile1_renamed' and created some duplicates due to now different filenames, the `posts.txt` was missing some posts that were created. I have a reason to believe that 'highlights.txt` doesn't work either, here's why. Fast-update option doesn't prevent duplicates of the same story, since the filenames (at least in my example) are different now. So if stories were downloaded again, then highlights would be too, but the weren't.

**Comment by ekalin** [comment]
After the first run with the renamed profile, the directory is renamed. Therefore there is no reference to the old name anymore, the successive runs probably failed with a 'profile not found'.

Profile renames require immediate action, that's why they're reported even in quiet mode. For such frequent runs, you'd probably have to automate it somehow, parsing the output or getting the list of profiles to download from the actual directories present.
