### ISSUE TITLE
Is it possible to get posts only from a specific date without passing through the most recent posts?

### ISSUE THREAD

**Issue by Leonardomorn** [instaloader/instaloader#1395]
Hi,
 I want to download posts within hashtags that has an enormous quantity of posts, i'm currently using this command: 

`instaloader --login user --password password "#jellyfish" --post-filter="date_utc <= datetime(2015, 12, 31)"`

 I get the skipped requests on the data that is more recent than that and i'm incapable of reaching at the needed posts until too many queries or bad request appears.  Besides that, i need some information that i can only obtain when logged in, such as latitude and longitude. 
  So what i want to know is if it is possible to get only the posts before that specific time without passing through the more recent ones.

**Comment by gituzzer** [comment]
Interesting, I was going to ask here the exact same question.
I believe there is a way to do it, may be not implemented as we want atm.
I can see that it can be done, whenever I Ctrl-C a running instaloader script session, as below

...
[ 23/XXX] ... 2021-12-05_16-15-45_1.jpg ^C
Saved resume information to <profile>/iterator_COWcuDsy.json.xz.
Interrupted by user.

I'm back to prompt, and the json file is saved when it was saving that file, on that date.

Some time later, I start the same  instaloader script, and instead of starting with [1/...]

[1/1] Downloading profile <profile>
...
Retrieving posts from profile <profile>
Resuming from <profile>/iterator_COWcuDsy.json.xz.
[ 23/XXX]

It resumes at that date. It does it badly, as it soon stops (it does not deal well with _1.jpg _2.jpg .. multiple pics part of the same insta portrait ) but that's another topic.

Iteration complete, deleted resume information file <profile>/iterator_COWcuDsy.json.xz.
