### ISSUE TITLE
How to stop downloading a user from the args.txt when at the Datetime set and continue the next user?

### ISSUE THREAD

**Issue by lyscop** [instaloader/instaloader#1409]
I run the following command in CMD, but there is more than 4000 post from some users, when the post time at 2022, 1,15, it shows <Post bs3jKVINrI> skipped until all the 4000 posts are scanned. 

And it will show continuously errors.

I want to stop downloading from the user first showing post **skipped**, and continue the next user in the args.txt.

Just like `--fast-update` auto turn to next user.

`instaloader --login=lyscop --filename-pattern="{date_utc:%Y-%m-%d}_{shortcode}" --post-filter="date_utc >= datetime(2022, 1, 15)" --no-captions --no-profile-pic --no-metadata-json --no-compress-json +args.txt`

```
 Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "D:\Program Files\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "D:\Program Files\Python\Python310\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Program Files\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Program Files\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Program Files\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "D:\Program Files\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by mb9023** [comment]
This would be great if possible. I have archives from a different script and some users have 5000+ posts, if I set the date to only pull the last week of posts there's no reason it should scan the next 4990 posts before finishing. Once there's a 'skipped' it should move on when "date" is specified.

**Comment by ekalin** [comment]
Maybe `--latest-stamps` is what you need.

The first time you download an user, all posts will be downloaded. And the date/time of the newest post will be saved in a file. The next time you download that user, only new posts will be downloaded, and unlike the filter (which has to go through every post because there's no way for instaloader to know that there'll be no more included posts after the filter excludes one - you could filter based on a work in the title, for example), this immediately stops downloading for that user.

But in the first time all posts will be scanned.

If that does not solve your problem, there's an example of using instaloader as a Python module that does exactly that (download only until a date - and stopping once that date is reached): https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period . It's not possible with only the command line.

**Comment by mb9023** [comment]
My issue is coming from another download method, I already have most posts saved and I'm just trying to fill in the past week or two that I'm missing for a number of users. After the initial catching-up I expect it to be easier for new posts
