### ISSUE TITLE
Resuming interrupted download for highlights

### ISSUE THREAD

**Issue by i998979** [instaloader/instaloader#1448]
**Provide us a use case of the feature**
As the title says, I would like to suggest a feature that resumes interrupted download for highlights

**Describe the solution you'd like**
I wanted to download a user's profile with loads of saved stories (highlights), but Instagram just loves blocking me by too many requests or even 400 bad request. It is impossible for me to download from where it stopped and I have to iterate from the beginning and I get blocked AGAIN even I didn't reach where I stopped.

**Describe alternatives you've considered**
~~Well I don't think there is an alternative of this :(~~
Alternatively, if you are using windows, you may select anything in cmd and halt the whole thread until the tempban is unbanned because of 429 Too Many Requests. But if you are getting banned by 400 Bad Request and required to do email/phone verification and change password, then you have no luck :(
Also, if you halt the thread for too long, you will receive an error (I forgot the error) and the iteration loop will end

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**
Add any other context about the feature request here.

**Comment by aandergr** [comment]
Generally I think it would be nice to have as many things resumable as possible (at least where it is of any significant use). Highlights are obtained in a very different way than e.g. profile posts or comments of a post, where resuming works fine; as such, to implement resuming interrupted download for highlights will require a lot of thought and coordination. Accordingly, we are eager to hear your implementation ideas and are happy to provide feedback on any outlines.

**Comment by i998979** [comment]
I have a very brief look at the code (I only know how to read but not write, I don't know Python), I guess when the download was stopped for any reason(user interruption, --abort-on), save the currently downloaded storyitems to json, so next time we continue from that place?
The main point here is saving what StoryItem user has downloaded, then resume from the first not downloaded. Or alternatively, save what Highlights the user has downloaded and resume from the first unfinished. In both cases, it should be able to reduce the call to Instagram API, so that we won't get 403 that frequently as we don't trigger 400 and are required to start all over again.

My suggestion here is basically because I am reaching a bunch of 403 and end up with 400 during download a huge amount of storyitems in highlights (1000+).

My suggestion to users is to "trust" the session created by Instaloader inside Instagram, so that it MAY decrease the chance of triggering 400 and having to start all over again as highlights have no resume function.

**Comment by i998979** [comment]
Also I would like to ask whats the difference between iPhone version of photo/video and the normal one? Because I see an option of --no-ipphone but I don't exactly know the difference as the docs didn't write it clearly

**Comment by Thammus** [comment]
> The main point here is saving what StoryItem user has downloaded, then resume from the first not downloaded. Or alternatively, save what Highlights the user has downloaded and resume from the first unfinished.

For resuming, there is no need to keep the information which StoryItem already got downloaded because Instaloader detects the already-present files without issuing a request again. Therefore, your second suggestion seems more effective to me, i.e. saving which Highlights are targeted to be downloaded and resume from the first unfinished.

Each Highlight requires Instaloader to do one GraphQL query for fetching the list of associated StoryItems including their (non-iPhone) download URL. In the case of iPhone support (for example when downloading highlights through the CLI without `--no-iphone`) Instaloader needs to fetch the iPhone struct for each (not already-downloaded) StoryItem in order to obtain a higher quality image/video which is a request that is rate limited.

> what's the difference between iPhone version of photo/video and the normal one?

Images and videos obtained through the iPhone endpoint seem to have different characteristics that suggest they have a higher quality. Video files for example can differ in their resolution and file size. (See #1022 for a deeper discussion on this topic)

**Comment by i998979** [comment]
So without `--no-iphone`, the media downloaded are supposedly higher quality, but it counts towards the rate limitation.

However, with `--no-iphone` the rate is not limited, and most of the time the files are identical to above, but sometimes web version has lower resolution but high bitrate, or even some other weird characteristics, no matter on the web or iphone endpoint, photos or videos, am I understanding it right?


For the suggestions above, I guess we will have to consider the contents of highlights have changed or not too. For example, the user added/removed stories, or changed the contents but the amount is still the same.

**Comment by Thammus** [comment]
> However, with `--no-iphone` the rate is not limited, and most of the time the files are identical to above, but sometimes web version has lower resolution but high bitrate, or even some other weird characteristics, no matter on the web or iphone endpoint, photos or videos, am I understanding it right?

Even when using `--no-iphone` most of the queries are rate limited but there are different categories of requests that can have different limitations and the iPhone ones seem to be stricter. As for the quality differences it looks like you understand it right. That is why we consider bigger files resulting in an overall better quality regardless of other weird characteristics.


> For the suggestions above, I guess we will have to consider the contents of highlights have changed or not too. For example, the user added/removed stories, or changed the contents but the amount is still the same.

In my personal opinion it would be okay if a resumed instance tries to downloads the state of the highlights that it has at the time the download got initially started. The already existing resumable iterators do also behave that way.

**Comment by palmer2839** [comment]
Sorry, I don't have any suggestions but I'd definitely benefit from this feature, especially for backing-up large accounts in iterations.

However, since highlights are retrieved differently, is it safe to assume that stories also (--stories, :stories) behave the same way?

**Comment by Thammus** [comment]
Instaloader's Highlight class extends the Story class and a Highlight consists of StoryItems the same way a Story does. Although the logic for stories seems very similar, I guess that a resume feature does not provide any benefit. As discussed for the resuming of highlights, each Highlight requires Instaloader to do one GraphQL query for fetching the list of associated StoryItems. According to this logic, resuming of stories would take place on a per profile level and since stories are ephemeral, Instaloader would need to check available stories for the target profile, even when resuming.

**Comment by afterdelight** [comment]
This is very nice, I would love it to be implemented. I got a lot of 400 bad requests lately
