### ISSUE TITLE
How to stay logged in after a login

### ISSUE THREAD

**Issue by Esoppant** [instaloader/instaloader#1517]
When using the command prompt, Instaloader is asking me to log in to download videos from a certain (public) profile; I log in via "instaloader --login username" command, enter my pass, and a session file is created. After this, typing "instaloader -- -postID" returns the same error message that asks me to log in. Logging in **and** downloading the post in the same command works fine. But doing this every time takes quite a while. What is the primary way of staying logged in so that download commands go through that one login? Do I have to keep my session key file and instaloader.exe in the same directory?

**Comment by Showmaster3000** [comment]
You always have to use the parameter `--login username`. If a session file exists, it will be used instead of asking for password.
Session file will be saved in `%LOCALAPPDATA%\instaloader` by default. 
More info see manual: https://instaloader.github.io/cli-options.html#login-download-private-profiles
