### ISSUE TITLE
Start scraping from a particular post in a profile

### ISSUE THREAD

**Issue by mojo-jojo-7** [instaloader/instaloader#1521]
**Provide us a use case of the feature**
When an account gets banned halfway through scraping a profile, there is no way to continue where it stopped using a different profile 

**Describe the solution you'd like**
Maybe you can add an option like `--start-from 30` which ignores the first 30 posts in the profile. Or even be able to share the iterator across different user accounts will do the trick

**Describe alternatives you've considered**
There's no effective alternative as far as I can tell apart from starting from the beginning again, which will only waste api calls for posts that are already downloaded

**If the feature request is accepted, would you be willing to submit a pull request?**
Even if I wanted to, my coding skills are pretty bad. Sorry!

**Comment by aandergr** [comment]
Do you mean something like what we discussed in #855?

**Comment by cosimopp** [comment]
It will not work. I have already tried to implement it, and yet you get stuck on the post you got blocked on
#1525

for one my project, I had to download tons of media, and after some tests I figured out that If you create different instances of instaloader, you can download up to 10 posts/sec, without using any proxy/VPN. https://github.com/cosimopp/recognizeSchoolmateFaces/blob/main/downloadPosts.py
(usage: python3 downloadPosts "YOUR_IG_USERNAME" "YOUR_IG_PASSWORD" "PROFILE_TO_SCRAPE"
the program will download the most recent 12 pics of PROFILE_TO_SCRAPE's followers)
Therefore I think that if @aandergr will tell us what is the value that represents the id of instaloader's instance in JSON file (in order to edit it every time), we can accomplish it!
