### ISSUE TITLE
429 Too Many Requests Error Update

### ISSUE THREAD

**Issue by Marthe050** [instaloader/instaloader#1532]
Hi there!

I am trying to scrape the 20 most recent posts of 44 predetermined Instagram accounts (I aim to get the visuals and their accompanying caption as well as metadata, for example about how many people liked the post or commented on it). I do not need a lot of data as I want to scrape less than 1000 posts in total.

I use Instaloader version 4.9.

I receive a 429 Too Many Requests Error very quickly (sometimes after getting in two visuals of the same profile). Waiting for the time that is suggested by the Instaloader leads to the same error message again before getting any new data in. I have tried to following things (but none of them worked):
- Waiting for some time (24 hours and also waiting for 48 hours)
- Using a different Instagram account
- Being logged in
- Being logged out
- Logging out of Instagram on any other device I own
- Changing the max connection attempts
- Using a different IP address

I think I have a similar issue to the one discussed in issue [#834](https://github.com/instaloader/instaloader/issues/834), but the last comment that I see there is from November 2021.

I was wondering: are there any updates on this? 
Is there something I can do to avoid this error, or is this purely Instagram blocking me and there is nothing I can do about it?

Thank you in advance for any reply!

**Comment by Joost-dm** [comment]
I have the same problem.. 2 monthes ago everething wath OK.

**Comment by aandergr** [comment]
> Waiting for the time that is suggested by the Instaloader leads to the same error message again before getting any new data in.

This wording arouses my suspicion of a usage error. Instaloader remembers all requests including their time, calculates a wait time to the second, waits it out itself, and then continues automatically. It is not a suggestion when you should restart it, but just an information when it will continue by itself. No user interaction is necessary. On the contrary, manually waiting for the specified time and then restarting it will result in 429 errors, since all internal information regarding tracked requests between restarts will be lost.

Also see https://instaloader.github.io/troubleshooting.html#too-many-requests
