### ISSUE TITLE
Login required

### ISSUE THREAD

**Issue by jlntrt** [instaloader/instaloader#159]
Hey there,

I have several issues with the last two updates. Since then, instaloader logs in as wanted, downloads some stories, but at the end of the run, it claims `Download stories: --login=USERNAME required.`. Further IL logs on every profile `JSON Query to api/v1/users/<ID>/info/: 429 Too Many Requests Unable to fetch high quality profile pic.`

At the moment, I have 200 profiles to load and it seems that IL stops after about 10 profiles. 

Here are the parameters: `instaloader --sessionfile $HOME/lager/session --max-connection-attempts=1 --no-metadata-json --login=... --password=... --stories --fast-update $(dir -1 | shuf)`

Currently I downgraded to Instaloader 3.3.10 which has no request issues.

**Comment by Thammus** [comment]
Hey, thanks for reporting. The 429 error indicates that the queries for fetching high quality profile pics is rate limited but not monitored by the internal logic of Instaloader. Because of a bug, this error caused a logout and made the story download abort. This bug is fixed with the next version (4.0.8).
