### ISSUE TITLE
Logging Feature

### ISSUE THREAD

**Issue by LynBean** [instaloader/instaloader#1620]
A simple function to enable logging all info and errors into a text file. Can be toggle using command line parameter.
The level of logging such as `INFO`, `DEBUG`, `ERROR` and such parameters can be set

**Comment by Showmaster3000** [comment]
similar thing as requested in #1480.

**Comment by edinhodiluviano** [comment]
@Showmaster3000 I'd open a new issue but rather comment on this one since it would be the same idea (just with a longer explanation).

1. Why we'd benefit from a logging feature (not only logging to a file)?
To standardize output when using instaloader from within a big python script. For instance, this is the output of my script:
```
2022-10-30 03:19:32.215 - __main__                       - INFO     - MainThread - func:get_link - line:32 - Pegar um novo link
2022-10-30 03:19:32.642 - __main__                       - INFO     - MainThread - func:download - line:85 - Preparando para baixar link link.id=85
2022-10-30 03:19:32.643 - __main__                       - DEBUG    - MainThread - func:download - line:86 - Fazendo login.
2022-10-30 03:19:37.696 - __main__                       - DEBUG    - MainThread - func:_download_and_save - line:79 - Baixando
[- xxxx ] 250…500…750…1000…1250…1500…1750…2000…2250…2500…2750…3000…3250…3500…3750…4000…4250…4500…4750…5000…5250…5500…5750…6000…6250…6500…6750…7000…7250…7500…
Too many queries in the last time. Need to wait 137 seconds, until 03:35.

Too many queries in the last time. Need to wait 18 seconds, until 03:35.
7750…8000…
```
Notice the format difference between instaloader printed lines and my logger using python build in logging lib.
The main benefit would come when integrating instaloader with other python script, not when running it from the command line.

2. Why this would not be a dupe of [1480](https://github.com/instaloader/instaloader/issues/1480)?
Because it is not only sending the output to a file. It is a real logging feature. Of course the output could be sent to a file. But also it could be sent to a log server, or to telegram, or to two places at once... all this already built in python logging.

How do you achieve the here-described goal without the feature you are requesting?
There is no simple way to achieve all logging features from a print. Logging can filter, send logs to other places, control the level/verbosity easily, control the log format, all this from config files (in any formats) and even other libraries that work together with logging to make it simpler (i.e. [loguru](https://pypi.org/project/loguru/))

If the feature request is accepted, would you be willing to submit a pull request?
Yes.

**Comment by aandergr** [comment]
@edinhodiluviano Indeed, I see that logging via `logging` could be a benefit for Instaloader. However, it should be considered that we often log partial lines, i.e. messages that do not end with a line break. In the default case of the CLI, that the log is shown directly to the user, this should be preserved. If the log is somehow displayed or processed differently, it probably is not important.

**Comment by edinhodiluviano** [comment]
I'm unaware of any feature of the `logging` library that can change the end separator (just like a simple print).
What we can try to do is to "accumulate" the message and emit just one log when the line is finished. But this solution could be a problem if the partials are being generated too far away in the code base.
Another option would be to just upgrade the low hanging fruits and keep these special cases as raw `print`, as they are today.

**Comment by aandergr** [comment]
I think it would be okay to accumulate the messages, and give it to `logging` as soon as a complete line is finished.

**Comment by YisusChrist** [comment]
I made a couple of months ago a simple implementation of the suggested feature using the `logging` module. It's specially useful because you can specify in the configuration of the module whether you want to print log messages to screen (stdout), a file (log_file) or both at the same time.

I provide here a simple function to set up the logger which can be called right from the main function right before  the instance of the `Instaloader` object is made. By the way, I always add a 'debug' argument to all my python scripts using the `argparse` module so I can separate debug messages (with more information about the execution trace) from normal log messages.

```
import logging


def setup_logger(
    log_file: str, verbose: bool = False, debug: bool = False
) -> None:
    """
    Set up the logger for this instance.

    Args:
        log_file (str): File path to save logs.
        verbose (bool, optional): Whether to display logs in stdout. Defaults
                                  to False.
        debug (bool, optional): Whether to set logger level to DEBUG and add
                                file location info to logs. Defaults to False.

    """
    handlers = [logging.FileHandler(log_file)]
    level = logging.INFO
    msg_format = "[%(asctime)s] %(levelname)s: %(message)s"

    # In case you want to print messages also to stdout
    if verbose:
        handlers.append(logging.StreamHandler())

    if debug:
        level = logging.DEBUG
        msg_format += ": %(pathname)s:%(lineno)d in %(funcName)s"

    logging.basicConfig(
        level=level,
        format=msg_format,
        handlers=handlers,
    )
```

And here is a sample of the log_file you would get after a run:

```
[2023-04-04 23:54:06,856] INFO: Loaded session from /home/yisus_christ/.config/instaloader/session-<session>.
[2023-04-04 23:54:09,619] INFO: Logged in as <session>.
[2023-04-04 23:54:10,749] INFO: Stored ID <ID> for profile <profile1>.
[2023-04-04 23:54:10,749] INFO: [1/1] Downloading profile <profile1>
[2023-04-04 23:54:17,688] INFO: Retrieving posts from profile <profile1>.
[2023-04-04 23:54:17,689] INFO: [1/2] 
[2023-04-04 23:54:18,673] INFO: <profile1>/323590679_106583468937775_4874931410184281585_n.jpg
[2023-04-04 23:54:18,686] INFO: [2/2] 
[2023-04-04 23:54:25,370] INFO: <profile1>/321682151_1527424241015621_5985675679611786587_n.jpg
[2023-04-04 23:54:25,386] INFO: Saved session to /home/yisus_christ/.config/instaloader/session-<session>.
[2023-04-04 23:56:30,769] INFO: Loaded session from /home/yisus_christ/.config/instaloader/session-<session>.
[2023-04-04 23:56:35,849] INFO: Logged in as <session>.
[2023-04-04 23:56:48,849] ERROR: Profile <profile2> does not exist.
[2023-04-04 23:56:48,849] INFO: Trying again anonymously, helps in case you are just blocked.
[2023-04-04 23:57:03,797] INFO: Saved session to /home/yisus_christ/.config/instaloader/session-<session>.
```

As you may see it is **highly customizable**, it is only needed to define the logging basic configuration and replace `print()` calls to `logging.info()` or `logging.error()` based on expected output, i.e. almost immediate implementation. As you might notice there is no need to 'accumulate' log messages and then print all of them at the same time and it works great with the already implemented [log function](https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py#L104) and [error function](https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py#L109).

I would like to see this feature in asap in a big project like this.
Nice work for all the developers!
