### ISSUE TITLE
No profile pictures are being downloaded with 4.0.8

### ISSUE THREAD

**Issue by clb92** [instaloader/instaloader#165]
Am I the only one having this problem?

```instaloader --login=REDACTED --password=REDACTED --max-connection-attempts 1 --fast-update --no-video-thumbnails --stories-only --dirname-pattern=instagram-stories/{target} INSTAGRAM_USERNAME```

This command used to download stories and profile pictures (used v3.?.? before), but now it only downloads stories on 4.0.8.

I don't see any notable changes in the documentation regarding profile pictures. ```--stories-only``` should still get profile pictures, according to it. Am I doing something wrong or is there a bug?

**Comment by e5150** [comment]
50a5330fecb1272487fdd600416354c83ef8922f changed the way stories are downloaded, due to server side changes that affected stories of private accounts. Internally this means that `download_profile()` (which in turn downloads the profile picture) is no loger called if `--stories-only`. I guess either the documentation ought to be changed to state that `--stories-only` does, in fact, imply `--no-profile-pic`. Or the code refactored to handle more of `download_profile()`'s duties in `__main__.py`.
For now, I guess you would have to run `instaloader --profile-pic-only INSTAGRAM_USERNAME` (no need to log in for that) to also get the profile pictures.

**Comment by aandergr** [comment]
Hi. Thanks for reporting. a3777ca fixes it. The following table lists the intuitive flags to select what to download

```
To download (S = Stories, P = Profile Pic, p = Posts)

p	--no-profile-pic
P	--profile-pic-only
Pp	(default)
S	--no-profile-pic --stories-only
Sp	--no-profile-pic --stories
SP	--stories-only
SPp	--stories
```
