### ISSUE TITLE
Unable to use images urls

### ISSUE THREAD

**Issue by jahirfiquitiva** [instaloader/instaloader#1651]
**Describe the bug**
I'm trying to use the returned image url from `Profile.get_posts()` to load in a website, but the images are not loading. When I visit the url it loads, but not within the site.

Here's a video showing this https://shots.jahir.dev/m2FY62

**To Reproduce**
Use the returned url in a `<img>` html tag.

**Expected behavior**
Images should load normally.

**Error messages and tracebacks**
<img width="759" alt="Shot 2022-07-22 at 03 25 58@2x" src="https://user-images.githubusercontent.com/10360816/180397938-a1f0b8b4-c67d-4249-85f4-a325e03b3513.png">

**Instaloader version**
`instaloader --version` output.
4.9.2

**Additional context**
You can view the source code of my project at https://github.com/jahirfiquitiva/jahir.dev/blob/dev/src/components/compounds/InstaFeed.tsx

**Comment by AyluinReymaer** [comment]
This issue is not related to instaloader. It is related to your application itself.

Try the solutions mentioned in this stackoverflow, may or may not work.

https://stackoverflow.com/questions/69243166/err-blocked-by-response-notsameorigin-cors-policy-javascript

However, even if it does not work, please close this issue and try asking on stackoverflow or any other forum as this issue is unrelated to instaloader.
