### ISSUE TITLE
Requesting iphone versions of media seems to be triggering blocks

### ISSUE THREAD

**Issue by fbck** [instaloader/instaloader#1658]
Requesting iphone versions of media seems to be triggering request blocks and account blocks.
Difference in quality between iphone versions is there, but it's sometimes negligible, and sometimes, the original media isn't even reaching up to regular media dimensions, let alone iphone sized ones.
Most immediate solution might be to just not request iphone versions of media, by using --no-iphone option.

**Comment by Showmaster3000** [comment]
and what is your bug?

**Comment by fleescree** [comment]
I also got detected since yesterday, two of my accounts have asked for phone verification and password reset.
`instaloader --sessionfile="$HOME/.Instagram/session" --latest-stamps="$HOME/Instagram/latest-stamps.ini" --user-agent="\"$USER_AGENT\""  --stories --fast-update [user_list] `


```
Downloading stories
Download stories: 400 Bad Request
Saved session to /home/ubuntu/.Instagram/session

Errors or warnings occurred:
400 Bad Request Unable to fetch high quality profile pic.
400 Bad Request Unable to fetch high quality profile pic.
400 Bad Request Unable to fetch high quality profile pic.
Download stories: 400 Bad Request

```

**Comment by ikuchan122** [comment]
Yes, you are absolutely correct. This issue has been occurring since July 15. Several accounts of mine have been temporarily disabled. It used to occur only when Instaloader tried to fetch reposted post/story. However, since three days ago, it occurred whenever Instaloader calls the iphone api. Meanwhile, the web api works fine. 

You may wish to see the discussions in the below thread.
https://github.com/instaloader/instaloader/issues/1633#issuecomment-1186261689
https://github.com/instaloader/instaloader/issues/1633#issuecomment-1193169496

**Comment by fbck** [comment]
> and what is your bug?

This feature requests media in a way that constantly results in blocked accounts, and it shouldn't be the default behavior that requires an extra flag to disable if it's currently broken.

**Comment by AyluinReymaer** [comment]
I actually didn't know that it was due to instaloader retrieving the iphone versions of media.

I'm using the python module of instaloader so I didn't have the `--no-iphone` argument.

However, I've initialized the `Instaloader` class object with `iphone_support=False` (which is set to True by default) according to the docs: https://instaloader.github.io/module/instaloader.html?highlight=iphone_support

I'll report back tomorrow at latest to see if the issue is still ongoing.

**Comment by AyluinReymaer** [comment]
> I actually didn't know that it was due to instaloader retrieving the iphone versions of media.
> 
> I'm using the python module of instaloader so I didn't have the `--no-iphone` argument.
> 
> However, I've initialized the `Instaloader` class object with `iphone_support=False` (which is set to True by default) according to the docs: https://instaloader.github.io/module/instaloader.html?highlight=iphone_support
> 
> I'll report back tomorrow at latest to see if the issue is still ongoing.

Adding `iphone_support=False` to the `Instaloader` class object solved the issue for me as well.

It seems that the issue is indeed as it was mentioned before, the Iphone API is for some reason, giving constant bad requests...

I doubt instagram will solve this since this issue has been going on since the 15th of July. So, a change on the Instaloader API needs to be made, either to by default **not** use the iphone API or, if the iphone API is still working just with different parameters, to fix the instaloader API when retrieving data via the iphone API.

**Comment by EveryDirection** [comment]
I'm getting blocked even with the `--no-iphone` argument.

**Comment by twitter-79** [comment]
I ran into a block a few minutes ago, too. `iphone_support` was set to False and the block happened in `_obtain_metadata` in the line `pic_json = self._context.graphql_query('2b0673e0dc4580674a88d426fe00ea90', {'shortcode': self.shortcode})`

before I already got a Warning of `400 Bad Request Unable to fetch high quality profile pic`. Seems it got worse again...

**Comment by fireattack** [comment]
400 bad request issue seems to only happen to stories, it works fine for posts for me. Can anyone confirm?

**Comment by fireattack** [comment]
Another finding: I can't even visit _some_ accounts' stories by simply entering `https://www.instagram.com/stories/{account_name}/` in browser. It shows:

![image](https://user-images.githubusercontent.com/4130991/181705585-9595f097-070d-47c0-92ec-0e7b4e8c1199.png)

despite they do have stories. Going to their profile and then clicking their avatar works. No idea...

**Comment by Showmaster3000** [comment]
> 400 bad request issue seems to only happen to stories, it works fine for posts for me. Can anyone confirm?

@fireattack have a look at #1633 which already describes your comment...

**Comment by fireattack** [comment]
I read that, but the title says "post". I also have issue with non-"reshared" stories.

**Comment by afterdelight** [comment]
story reshares are usually crappy contents and post shares are always smaller in size anyway better to look at the original posts. normal stories are downloaded in max resolution for me. dont put 400 on --abort-on command and you can continue downloading normal post

**Comment by Nova6K0** [comment]
Look at this:

https://github.com/yt-dlp/yt-dlp/commit/e3e606de12ea138825754290542559b888f72bb5

Greetings.

**Comment by afterdelight** [comment]
what does that fix?

**Comment by afterdelight** [comment]
try to change user agent? it worked for me
