### ISSUE TITLE
count for profile downloads

### ISSUE THREAD

**Issue by movAX13h** [instaloader/instaloader#1660]
Is there a technical reason why `--count` is not available for profile downloads?

If a profile has many thousands of posts but I always only want to get the newest 10 posts, currently the only option to reduce workload is to use `--post-filter` with a certain datetime and hope that I get about 10 posts and it also takes very long because instaloader is going through all posts.

It appears to me that the newest posts are always processed first so `--count 10` to stop iteration after 10 posts would really help in this situation.

Any thoughts appreciated; please let me know if I'm missing something.
Thank you!

**Comment by aandergr** [comment]
This would unfortunately change Instaloader's behavior in a backward-incompatible manner, since an invocation with --count and a mix of hashtags/feed/location and a profile would then behave differently in that the max count now also affects the profile and not only hashtags/feed/location.

Also, it is quite trivial for the user to only download a certain count of posts of a profile, e.g. by calling download_post() for each post of an islice()'d profile.get_posts(). There is no need to include that in the CLI.

**Comment by movAX13h** [comment]
I see. Thank you for your response.

**Comment by movAX13h** [comment]
Just noticed that this is a duplicate of #327 and #141 ... Many users seem to ask for this because it is a very common use-case and somehow weird that this is not the default behaviour of instaloader.

**Comment by vadimkantorov** [comment]
Maybe a new command-line option should be introduced for this very frequent usecase?

This is a very useful usecase for small websites: render statically several most recent instagram posts

If instaloader can download most recent 10 instagram posts and save all the info in a directory, or serialize into JSON, it'd be extremely useful
