### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by Muggeren** [instaloader/instaloader#1711]
Anyone had this problem before, and know how to make it come more rarely. Can't even download a post without it showing up. 

Fixed it once by adding a phone number, but that just allowed me to download 100 posts.. The reason why i need to be logged in, is because im downloading specific photos from diffrent people, so im using the saved feature.

**Comment by WorldTreader** [comment]
I'm having the same issue, right now is almost impossible to use instaloader. If someone has some advice on how to limit the 429 error it would be wonderful.

**Comment by innerchihiro** [comment]
same issue, suddenly cropped up in the past couple days

**Comment by afterdelight** [comment]
did you download stories too or just posts?

**Comment by Muggeren** [comment]
> 

Also stories

**Comment by AyluinReymaer** [comment]
I think instagram is heavily rating stories.

I did some tests in the past and apparently, if you get stories in quick succession, it is flagged by instagram.

2 days ago I had a very weird issue in instagram... I was receiving 429s on instaloader. I stopped using instaloader for hours but I still was receiving 429s even on the browser and the instagram android app.

In order to try to resolve this issue, I even logged out from instaloader from the instagram's login activity, hours later, still having 429s.

Apparently, I received 429s for literally 24 hours, even though they say that the rate limit is per hour...

But the weird thing is, I was only receiving 429s on my instagram home tab.
I couldn't see my feed, see who had new unread stories, couldn't open the DMs and couldn't see comments.

However, I could still open instagram profiles, posts, I could open the stories as well (they just didn't appear in my feed), I could go to the explore tab, I could like and save posts.

Very weird...

Right now, I changed my automation to implement a few delays (especially on stories).

* Delay between each source (profile, hashtag, location, etc...): random between 10 to 30 seconds
* Delay between each post: random between 1 to 3 seconds
* Delay between each story: random between 3 to 10 seconds (longer here just in case. Taking into consideration that the rate limiting seems heavier here)

I made these changes today and am currently testing things to see if it works properly, in conjunction to the "work hours" that I've implemented in the automation. It only works from 09:00 to 23:30 and only triggers every 30 min for a maximum of 5 sources at a time to mimic human behavior.

**Comment by thariq-nugrohotomo** [comment]
I just getting this issue after updating to version 4.9.3.
I decided to rollback to my previous version (4.9.1) and then deleting the saved login session folder (in `%APPDATA%\..\Local\Instaloader`), and after than I can download the stories again normally.

**Comment by afterdelight** [comment]
hmm i wonder whats causing it ? maybe because of a new instagram end point?

**Comment by afterdelight** [comment]
> I think instagram is heavily rating stories.
> 
> I did some tests in the past and apparently, if you get stories in quick succession, it is flagged by instagram.
> 
> 2 days ago I had a very weird issue in instagram... I was receiving 429s on instaloader. I stopped using instaloader for hours but I still was receiving 429s even on the browser and the instagram android app.
> 
> In order to try to resolve this issue, I even logged out from instaloader from the instagram's login activity, hours later, still having 429s.
> 
> Apparently, I received 429s for literally 24 hours, even though they say that the rate limit is per hour...
> 
> But the weird thing is, I was only receiving 429s on my instagram home tab. I couldn't see my feed, see who had new unread stories, couldn't open the DMs and couldn't see comments.
> 
> However, I could still open instagram profiles, posts, I could open the stories as well (they just didn't appear in my feed), I could go to the explore tab, I could like and save posts.
> 
> Very weird...
> 
> Right now, I changed my automation to implement a few delays (especially on stories).
> 
>     * Delay between each source (profile, hashtag, location, etc...): random between 10 to 30 seconds
> 
>     * Delay between each post: random between 1 to 3 seconds
> 
>     * Delay between each story: random between 3 to 10 seconds (longer here just in case. Taking into consideration that the rate limiting seems heavier here)
> 
> 
> I made these changes today and am currently testing things to see if it works properly, in conjunction to the "work hours" that I've implemented in the automation. It only works from 09:00 to 23:30 and only triggers every 30 min for a maximum of 5 sources at a time to mimic human behavior.

how did you manage to do that?  could you tell me whats the randomization codes and where to put it, on what lines?

**Comment by lazarostso** [comment]
Same problem here. I am trying to get followers from different profiles. I can only load up to 8800 followers.

1. I have set random delays between each query and customize handle_429 function. 
2. I have build my own 4G proxies with real life SIM Cards and i am not running anything else on them.
3. I am not running any parallel activity while i excecated the script.
4. I am not overload my scrapers. I use each profile every 24 hours.
5. The profiles are not connected to any other device, they are logged in only on script.
6. I use session save in order to keep the profiles logged in every time the script are using them.
7. I have set "iphone" as default query_type.

Any idea? Why i can't load more than 8K followers?

**Comment by uvx0ol** [comment]
> Right now, I changed my automation to implement a few delays (especially on stories).
> 
>     * Delay between each source (profile, hashtag, location, etc...): random between 10 to 30 seconds
> 
>     * Delay between each post: random between 1 to 3 seconds
> 
>     * Delay between each story: random between 3 to 10 seconds (longer here just in case. Taking into consideration that the rate limiting seems heavier here)

Could you explain how exactly you did this?
