### ISSUE TITLE
Failed to create process. 

### ISSUE THREAD

**Issue by Weirdkid2134** [instaloader/instaloader#1724]
I did as it was written in the page but when I try to run this command, instaloader profile [profile...]
, the terminator shows "failed to create process.".

Somebody please tell me how to solve this issue.
![Screenshot (34)](https://user-images.githubusercontent.com/112609906/188263467-70665d08-fcda-4812-963f-183c02a37204.png)

**Comment by Nova6K0** [comment]
It is because you are putting the parameters badly. And they should be like that:

`instaloader profile1 profile2 profile3...`

In your example:

`instaloader ajey_notreal`

On the other hand, if the profile is not public, you need to log in:

```
instaloader --login USERNAME ajey_notreal

USERNAME = Your own username
```

You do not need to put the word **profile**, before the profiles, **and you do not need to put square brackets between each profile**. That is if you do it with your own source code in Python (since each set of profiles is passed as a list, either numbers (int), or as character chains (strings).

Greetings.

**Comment by Weirdkid2134** [comment]
> instaloader --login USERNAME ajey_notreal
I did the same but it is still not working. tell me what am I doing wrong?
![Screenshot (35)](https://user-images.githubusercontent.com/112609906/188267562-59c9d618-5bb8-4475-ad03-882a2fb4a7af.png)

**Comment by Nova6K0** [comment]
That is because you are using install.py. You should download the Stand-Alone or the Executable version, whose latest version is 4.9.3

Anyway. That message appears, because you do not have the Python file path, in system enviroment variables (PATH), and when you run instaloader.py, it does not find Python.exe or any of the necessary libraries. And I recommend that you do not use many levels of folders, which can also give problems.

Greetings.

**Comment by Weirdkid2134** [comment]
I saw that that there were 2-3 versions of python downloaded and maybe installed too. So I deleted them except the latest one of them, which was 3.9 . Now again I tried to run that command, this time it didn't show "failed to create process." But this time it showed this. 
![Screenshot (38)](https://user-images.githubusercontent.com/112609906/188280429-7b4eb23a-3d61-46d2-a600-df52170e0c7f.png)

Please tell me what to do next?

**Comment by Nova6K0** [comment]
Execute the Instaloader.py, without any argument:

`instaloader`

Let's see if the same appears.

Greetings.

**Comment by Weirdkid2134** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/112609906/188281278-14808c8c-f0c3-4dc2-a15c-a0d994605475.png)
that failed to create process bs started again. lol.
Btw can I get your instagram, It would be easier to talk there. Mine is @rishi_shukla29

**Comment by Nova6K0** [comment]
Let's see several things:

The installing code has to put in a folder only. Something like that:

`G:\instaloader-master`

Then, you have to add the Python path, to the PATH environment variable (for that you have to press the Windows + Pause key, and in the menu on the left, **advanced system settings**, then in **wnvironment variables**, double click In **Path**, and add where you have the **python.exe** file).

Greetings.
