### ISSUE TITLE
make it asynchronous

### ISSUE THREAD

**Issue by antinuke0day** [instaloader/instaloader#1730]
genuinely just make it async instead of using blocking requests it will improve the speed a bunch

**Comment by lucasintel** [comment]
What do you mean by asynchronous?

**Comment by Nova6K0** [comment]
The asynchronous code is one that can be executed, without waiting for the server responses. When you send an HTTP request, you have to wait for the server response. That is lost time, because you can't do anything until the server responds. When you make an asynchronous request, the code continues to run, without waiting for the server's response. It is actually a code that runs on another code, to put it easy. And this provides a much higher speed.

Example:

`https://www.twilio.com/blog/asynchronous-http-requests-in-python-with-aiohttp`

Greetings.

**Comment by SelfAdjointOperator** [comment]
What's the point? What are you going to be doing whilst a http request is pending? If you're thinking about handling multiple requests in a pool that just sounds like a recipe for an instant 429, especially as Instagram seems to have gotten even stricter recently with their API use. Also the `requests` module still isn't async-based.

**Comment by MrVhek** [comment]
Some of us use proxies, so in theory it could be faster. I've tried patching the session.get and session.post and it works well for retrieving statistics of users.
You can use this decorator to transform instaloader calls to async:
```
def force_async(fn):
    '''
    turns a sync function to async function using threads
    '''
    from concurrent.futures import ThreadPoolExecutor
    import asyncio
    pool = ThreadPoolExecutor()
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        future = pool.submit(fn, *args, **kwargs)
        return asyncio.wrap_future(future)  # make it awaitable
    return wrapper
```

**Comment by Henkhogan** [comment]
@aandergr I‘d like to contribute by adding optional async functionality based on aiohttp, if the maintainers are willing to accept and maintain it.

why async? I have an async web app that would need to fetch insta data on certain events and I don’t want that to be blocking
