### ISSUE TITLE
Instaloader stops after a random short amount of images from hashtag, no error

### ISSUE THREAD

**Issue by MatthieuBonenfant** [instaloader/instaloader#183]
Hi, not sure what happened since last time I used but I haven't used the script for about a month and half and it does not seem to work anymore. I have not changed anything in my parameters. Made sure to update to 4.1 (I think I was already on 4.1), but still doing it.

**Describe the bug**
Instaloader stops after 2-3 images, or 9, or 17, no error. I tried different hashtags, always the same pattern. It just stops without giving any error

**To Reproduce**
instaloader #themandalorian --fast-update --filename-pattern={profile}_{date_utc}_UTC --no-videos --no-video-thumbnails --no-captions --no-metadata-json

or

instaloader #kenobi --fast-update --filename-pattern={profile}_{date_utc}_UTC --no-videos --no-video-thumbnails --no-captions --no-metadata-json

**Error messages and tracebacks**
No error, it just stops

**Instaloader version**
4.1

Thanks

**Comment by aandergr** [comment]
Thanks for reporting this! Thanks for also showing us the exact invocation where this happened, which really helped us to easily reproduce the bug and find its cause.

The reason was, that `--fast-update` aborts the download as soon as a post is encountered where nothing is downloaded. Hence, with `--no-videos --no-video-thumbnails` it aborted the download after reaching the first video. We just fixed this error in the logic with 41e734e.
