### ISSUE TITLE
Get caption from Instagram Story

### ISSUE THREAD

**Issue by yjymas** [instaloader/instaloader#1844]
I was able to download posts and stories using Instaloader just fine. However, I wanted to download the captions/texts from the stories and I can't seem to get the save_caption work. Can someone provide a sample on how this is used? I am currently downloading the stories using download_storyitem.

`instance.download_storyitem(item, username+'_stories')`

**Comment by EveryDirection** [comment]
In Instaloader terminology, "captions" mean the captions on feed posts. I do not think it is currently possible to download captions/texts from stories.

**Comment by pharmacologic** [comment]
> In Instaloader terminology, "captions" mean the captions on feed posts. I do not think it is currently possible to download captions/texts from stories.

Is this still the case? Have captions for stories (added text, mentions) ever been supported by instaloader? Because the instaloader documentation on [Instagram structures](https://instaloader.github.io/module/structures.html#instaloader.StoryItem) seems to actually list {caption}, {caption_hastags}, {caption_mentions} as being valid properties of the StoryItem class.

I've attempted to use these properties in `--storyitem-metadata-txt`, but they do return empty values.
