### ISSUE TITLE
Slow down downloads

### ISSUE THREAD

**Issue by ansgarradermacher** [instaloader/instaloader#1869]
**Provide us a use case of the feature**
My account got disabled after using instaloader without prior warning, apparently due to bulk loading of data (violation of community guidelines). Not clear yet, if the reactivation works.

**Describe the solution you'd like**
The documentation should warn about the danger of using the --login option and provide a means to slow down the download in order to avoid getting flagged (I don't know the thresholds, e.g. data size or number of downloads within a given time)

**Describe alternatives you've considered**
How do you achieve the here-described goal without the feature you are requesting?

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
I wanted to download the profile of my daughter, since her account has been hacked and I wanted to save at least the content. I accidentally used the "@" option, e.g. started downloading the content of followers. No recovery methods work and impossible to contact instagram/meta, but that's a different story.

**Comment by ansgarradermacher** [comment]
Sorry, I just see that it has already been discussed, see https://github.com/instaloader/instaloader/issues/828 and https://github.com/instaloader/instaloader/issues/1817

**Comment by marinsebastian** [comment]
Just got an account banned too, I'm unsure where I read it, but I'm pretty sure it was common knowledge not to use your main account. Always created burners for this and even then it's still hit or miss when Instagram might ban/restrict your account, they used to be light then, you'd only need to provide a phone number and a code sent to it, now they asked for a picture of myself holding a paper with some numbers my name and the @ of the account, ultimately account got permanently banned because I refuse to do that.  

I think that even if there'd be some way to limit the down the downloads, which Instaloader already does, it's still unknown how Instagram / Meta can tell that you're using a third party app, sometimes I was able to download thousand of pictures without any issues, other days I'd get banned after less than a hundred pictures. There isn't really a way to prevent those bans unless one knows for certain how Instagram identifies your third party app.

**Comment by ansgarradermacher** [comment]
Apparently, my account has been disabled permanently. This shows that the "investigation" by meta is very superficial and did not look at all into my information that the account had been hacked (which I added to the picture that I had to upload). Well, not really a problem for me, as I did not post any contents and did not have any followers, since my main objective was to see from time to time what my daughter was posting. But it shows that instaloder should definitely add a big warning sign to the --login option.

**Comment by aandergr** [comment]
Instaloader already limits the download rate, and you can even experiment with [overriding the rate controller](https://instaloader.github.io/module/instaloadercontext.html#instaloader.RateController) if the default behavior does not fit your needs.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
