### ISSUE TITLE
Discussion on best practices

### ISSUE THREAD

**Issue by Arrmm** [instaloader/instaloader#1927]
Hi, I discovered this awesome app/tool a week or so ago.  I must admit I am a hoarder for several influencers that I follow.  Some of them have thousands of posts while others have hundreds.  Given IG has anti-bot  mechanisms I thought I want to start a thread and discuss some of the best practices that we can all share:

Here are some that I have discovered and please feel free to critique and add.
(note: I am running the standalone .exe version)

1. If you are hoarding, I *highly* recommend not to use your login to protect your personal account.  You can alternatively create fake accounts and I don't think this is the best platform for that discussion.
2. The `--abort-on` is a god-send feature.  Currently I have it set to `--abort-o=302,400,401,429`. 
 This is so that in case IG times out or deny access when you are pulling down a big list, you can resume at a later time without the need of starting all over again.
3. In addition, it is good to also use the `--latest-stamps` as well. (
   _Note: this isn't working for me for the standalone version so currently I am not using it)._
5. If you want to run this on a regular basis (daily or weekly), I created a short little `.bat` file to make things easier.  You can append additional options as desired.
```
@echo off
for /d %%d in (*) do instaloader.exe %%d -F --latest-stamps
```

Cheers!

**Comment by kissuidotnet** [comment]
hi @Arrmm -- thanks for getting this started.. 
have you had success using args.txt file 
https://instaloader.github.io/cli-options.html?highlight=args%20txt#cmdoption-arg-args-txt
like you.. im using the standalone .exe

**Comment by Arrmm** [comment]
> hi @Arrmm -- thanks for getting this started.. 
> have you had success using args.txt file 
> https://instaloader.github.io/cli-options.html?highlight=args%20txt#cmdoption-arg-args-txt
> like you.. im using the standalone .exe 

I haven't tried the args.txt file yet.  I can look into it tomorrow when I have some time.

**Comment by makako-dev** [comment]
I am also using args.txt file in conjunction of using the [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) script and the standalone instaloader.exe. Also, since I started using the user-agent flag,  my account has not been flagged for suspicious activity in quite some time. In addition, I try not to scrape lots of accounts at the same time and use abort codes. My args.txt file look something like this: 

`--login=myaccount`
`--user-agent=my-user-agent-here`
`--no-metadata-json`
`--no-captions`
`--fast-update`
`--max-connection-attempts=10`
`--request-timeout=100`
`--abort-on=403,400,429,302,401,503,501,500,502,404,410`
`--dirname-pattern=path\to\save\directory\{target}`
`account1`
`account2`
`account3`

**Comment by PrateekSharma0409** [comment]
@Arrmm Do you have copy of rust desk pro version they have deleted the commit
