### ISSUE TITLE
How to extract list of followers of an account?

### ISSUE THREAD

**Issue by TobiasW128** [instaloader/instaloader#1942]
Hi,

Im trying to get a list of all the followers of a specific account. However, whenever I try to log in with the following code:
import instaloader
```
# Get instance
L = instaloader.Instaloader()

USER = USERNAME
# Optionally, login or load session
L.login(USER, "xxx")        # (login)
L.interactive_login(USER)      # (ask password on terminal)
L.load_session_from_file(USER) # (load session created w/
                               #  `instaloader -l USERNAME`)
```

I get the following error message:

````
File "C:\Users\Hp\Documents\Prive\Python\Projects\Tower\venv\lib\site-packages\instaloader\instaloadercontext.py", line 239, in login
    raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXEAeL8Fss_3CFukctZ6kRn0W7vjLa26xm9gdDgfEHjjleTLKG1rFBIoQme90GguvzPmiJw/AfwNRARP-Lz3ydhYRTZMhgdf8dvKGMjdYqcJ1q_Vh27JstoEkIl5H4ivb5Eu_7lTj5zgSIoN-X3dGQ/ffc_XBTXntaH7K6kK4LRhLl3DK553r7B3JncA2o0VcU405L8MbcQ4WGdXXzIAr4eBe8P/ - follow the instructions, then retry.
````

But that website just send me to log in screen of Instagram, and if I try to log in again it says that it detected an dangerous login attempt and that I should pick a new password.

Is this a bug? Or is there a way to get around this issue? If so, how can I download all the followers from a profile and extract that to a txt or xlsx or csv file? I only want the usernames.

**Comment by Mujadid-Ali** [comment]
Couples of days before, I have had the same issue. 

**Reason**
Instagram has strict polices regarding bots/scripts that scrape data from Instagram. So when the first time you will try to log in and Instagram server detects some kind of location change, they will redirect you to `"Login: Checkpoint required. Point your browser to"` error. But if you follow the link and try to complete the checkpoint, it will strut it in a loop, and it will ask again and again to complete the checkpoint. 

**Workaround**
I used the following workaround to avoid this issue. The workaround is consisting of the following steps.

1. Login to your account through Firefox browser.
2. Download [THIS ](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py)script.
3. Run the above script e.g `python <YOUR_SCRIPT_NAME.py>` (it will access Firefox session file and extract session file of your account from Instagram and place it at _C:\Users\<USERNAME>\AppData\Local\Instaloader_).
4. Now Login using session file instead of username and password. (I have use following code to login from session file)
```
      try:
          self.loader.load_session_from_file(username)
          return True
      except FileNotFoundError:
          try: 
              self.loader.login(username, password)
              self.loader.save_session_to_file()
              return True 
```

The above workaround is documented [here](https://instaloader.github.io/troubleshooting.html#login-error). 

**Note:** sometime due to many requests, Instagram temporary blocked the account or your IP. for account recovery you only need to log in from web browser or app and follow the steps and for IP blockage you can change your local IP by using VPN or wait some days (minimum 24 hours) until Instagram unblock it.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
