### ISSUE TITLE
Fixes to Avoid Detection/Bans

### ISSUE THREAD

**Issue by notBradPitt** [instaloader/instaloader#1984]
It's been over a year since I last used Instaloader for this very issue. I rechecked again today and issue still persists. So in this issue I would like to focus on **discussing potential fixes only**, and not the complaints about how this repo should be archived already, how you shouldn't use `--login` (They are needed for stories and private accounts), ,etc. 

Here are several potential fixes I've seen so far:

- **Using Custom User Agent:** Using UserAgent of external browser or Instagram (which you can get this by opening a UserAgent checker site link through Instagram)
- **--abort-on 400:** Aborting on the first error 400 warning
- **--no-iphone:** Using iPhone UserAgent seems to raise the possibility of getting banned.
- **Time Limit Between Requests**: Some users have suggested to set time limit between each requests, however there is still no built-in command for the CLI version.

If you've been banned for using Instaloader before, please share your experience with these fixes. I would really appreciate if someone could add another fix to the list until the devs do something to solve this problem.

**Comment by ekalin** [comment]
Despite the cargo cult following that delay between requests has, I have tested running instaloader with a few seconds delay between requests, and it made no difference. I've also tried with a longer delay between profiles, and also no difference.

For regular updates, one thing that does seem to help is download only a small number of profiles. But this doesn't help when you have many profiles to update, or for downloading a whole profile.

Using the same user-agent as the browser, logging in with the browser and fetching cookies from the browser seems to trigger only a periodic logout that requires just a new log in, no password changes or account lock ups. I prefer to avoid logging in repeatedly, if it logs you out again shortly, I prefer to wait until the next day to try again.

One thing that does seem to help, but I'm still investigating, is logging in with a browser, getting the cookies, and keeping the browser open. Maybe there's some ping that the client-side JS sends to IG. Using the inspector, I see some occasional requests even if I'm not doing anything, but they seem like analytics gathering. Anyway, as I said, I'm still investigating that, can't say conclusively that it works or not.

**Comment by nebula0225** [comment]
and important using good quality account
ex) buy fake acconut vs own account -> own account is better

**Comment by ekalin** [comment]
> Could you please explain how to get the browser user-agent?

https://www.whatismybrowser.com/detect/what-is-my-user-agent/ or any other equivalent site.

> Are you using --no-iphone too?

No, because this prevents downloading the highest resolution media.

**Comment by notBradPitt** [comment]
Might or might not be related, but my account was warned for "automated actions" even though I scraped without account. Accounts aren't supposed to get banned just because they belong in the same IP right?

**Comment by nebula0225** [comment]
@notBradPitt
You work with no account -> your ip is banned -> you login banned ip -> your account is blocked

**Comment by ekalin** [comment]
I think this discussion is still valid

**Comment by notBradPitt** [comment]
Regardless of user agent, Instaloader still uses the API URL to get posts right? I think that might be what's causing the problem

Would it be possible to use a headless browser instead?

**Comment by intellifos** [comment]
I think it would be great if Instaloader had a headless browser option

**Comment by estatistics** [comment]
We are archiving history. Because history is not only great human but also, everyday human. Because of the limitations of instagram, do you like to exchange insta downloaded profiles (public ones) ? if you like get in touch in me in github.

**Comment by estatistics** [comment]
I observed something today. 
i use this 
`instaloader --login=user --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0" --abort-on=302,400,401,429,403 --fast-update --highlights --stories --tagged userA/ && gallery-dl --cookies-from-browser firefox "https://www.instagram.com/userA/reels/"`

while instaloader thrown "429 Too Many Requests". gallery-dl fetched reels immediately after.  
However, gallery-dl may not follow the api /rules of insta very strictly? or because it is a different app, instagram "renew" limits? 

or maybe if you use two different browsers with same insta account, but different cookies, the limits renew too? if someone try it, please report back.

**Comment by notBradPitt** [comment]
> I observed something today. i use this `instaloader --login=user --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0" --abort-on=302,400,401,429,403 --fast-update --highlights --stories --tagged userA/ && gallery-dl --cookies-from-browser firefox "https://www.instagram.com/userA/reels/"`
> 
> while instaloader thrown "429 Too Many Requests". gallery-dl fetched reels immediately after. However, gallery-dl may not follow the api /rules of insta very strictly? or because it is a different app, instagram "renew" limits?
> 
> or maybe if you use two different browsers with same insta account, but different cookies, the limits renew too? if someone try it, please report back.

Tried gallery-dl (didn't know they had an Instagram support) and it worked great! Seems like it's the only viable way to scrape using an account right now. Though, I've only tried using it with long delays between requests, 2-10 secs between media and 15-45 seconds between API requests. 

> lost my account, but what's worse is that i can't create a new account. tried different email providers(clearing cookies, new IPs each time), but it just does not let me. Always suspended right after creating an account. Any tips?

What are you using to sign up? Avoid using the app (or at least use a different profile if you're on Android) as they will check your device identifier. Signing up on browser is pretty much dead since they'll ask you for a phone number 99% of the time and you can only verify like two accounts with one phone number

**Comment by NicoWeio** [comment]
Why was this closed?

**Comment by notBradPitt** [comment]
Not sure why this was closed, it's still a persisting issue for Instaloader. 

If anyone comes across this issue looking for a quick fix, gallery-dl currently works better than Instaloader if you want to scrape with an account. I'm not sure if they have options to collect captions, comments, etc. like Instaloader does, but they do have rate limiting feature which is good to avoid detection.

**Comment by SaurabhS78** [comment]
> Might or might not be related, but my account was warned for "automated actions" even though I scraped without account. Accounts aren't supposed to get banned just because they belong in the same IP right?

I am still facing this issue

**Comment by nebula0225** [comment]
If your IP address is blocked, you can be blocked just by belonging to the same IP address.

**Comment by Patxi080** [comment]
> If your IP address is blocked, you can be blocked just by belonging to the same IP address.
I do not know much about it, but running instaloader through torsock or similar would help with this?

**Comment by PoisonFrog** [comment]
I’d like to share my experience using Instaloader and how I resolved some persistent disconnection issues with Instagram.

At first, I was getting frequent warnings and was being disconnected nearly every time I ran Instaloader. After some trial and error, I found a setup that works reliably for my situation. I use Firefox as my main browser, and I configured Instaloader to use cookies from Firefox by setting `load-cookies=firefox` and pointing `cookiefile` to the `cookies.sqlite` file in my user profile. I also set the `user-agent` to match the one used by the Firefox browser where my Instagram account is logged in.

Since switching to this configuration, I have been able to run Instaloader multiple times without receiving any warnings or being disconnected. The only exception was when my browser updated and I forgot to update the `user-agent` string. Once I did that, everything went back to working smoothly.

I can’t say how long this approach will continue to work, but so far it has been very stable. If you're running into similar issues, it might be worth giving this a try.
