### ISSUE TITLE
Can someone send me a copy of their command line configuration so I can understand how to make my own?

### ISSUE THREAD

**Issue by user50237** [instaloader/instaloader#2023]
I've read https://instaloader.github.io/ but still find it confusing how to correctly make my own configuration because their are no examples of what the code should look like when they're added.

I want to download a list of profiles from a txt file and I'm unsure how the txt file of accounts should be formatted (I want to include user IDs of the accounts too so the account can still be found if there is a username change by the account owner).

I'm using Windows.

**Comment by Jon8RFC** [comment]
Here are some examples.  I suggest not using the one that grabs all posts since Instagram seems to disable/flag/ban accounts more readily as time goes on.

I use the Windows exe and I open a command prompt within the folder location of the exe.  Folders are created alongside the exe.

Please note that the code is all one line/"string", despite it possibly wrapping around in this post.

For singular posts, you just need to add a space, dash/hyphen, and then the post's unique code from the URL, and you can have many retrieved at once.  Also, if you don't have the --dirname-pattern set, if you have posts from both MsJennaFischer and AngelaKinsey being downloaded, then posts will go into a folder named for its respective account owner.
This is handy, for me, to have a separate folder for this case.

Being logged in will grab the higher resolution pictures, otherwise it's limited to 1080px width.  For just a single picture on occasion at 1440px width, rather than the hassle and risk of a ban, I just use:
[this chrome plugin](https://chrome.google.com/webstore/detail/high-resolution-downloade/hbijmiokbffalbolieapplfhmmnioeao)

**POSTS (all):**
`instaloader --login=jon8rfc --no-metadata-json --no-captions --no-profile-pic --no-videos --filename-pattern={date_local}_CST__{shortcode} angelakinsey`

**SINGULAR POST(S) (using URL):**
https://www.instagram.com/p/Ct4cxAEJNBw/
https://www.instagram.com/p/Ct4cxAEJNBw/
`instaloader --login=jon8rfc --no-metadata-json --no-captions --no-profile-pic --filename-pattern={date_local}_CST__{shortcode} --dirname-pattern=singular_posts -- -Ct4cxAEJNBw -Ct7u4U3Mwco`

**STORIES (all):**
`instaloader --login=jon8rfc --no-metadata-json --no-captions --no-profile-pic --no-posts --filename-pattern=stories_{date_local}_CST__{shortcode} --stories angelakinsey`

**STORIES (just specific, using URL):**
https://www.instagram.com/stories/angelakinsey/3138283049654547149/
`instaloader --login=jon8rfc --no-metadata-json --no-captions --no-profile-pic --no-posts --filename-pattern=stories_{date_local}_CST__{shortcode} --stories angelakinsey --storyitem-filter="mediaid == 3138283049654547149"`

**PROFILE picture:**
`instaloader --login=jon8rfc --no-metadata-json --no-captions --no-posts --no-videos --filename-pattern=profile_{date_local}_CST__{shortcode} angelakinsey`

**Comment by makako-dev** [comment]
See [this](https://github.com/instaloader/instaloader/issues/1927#issuecomment-1556256540) comment in which I have an example of my args.txt file.
