### ISSUE TITLE
Instagram limitation in hashtags to top 9 posts

### ISSUE THREAD

**Issue by Jesusmruiz1** [instaloader/instaloader#2049]
Hi everyone,

I have noticed that currently IG in browser only show 9 posts when you want to explore a hashtag. Do you have this limitation using instaloader? 

Thank you in advance,

**Comment by mammuthus** [comment]
Same question

**Comment by SangdonLee972** [comment]
As of my last update in September 2021, Instaloader is a popular Python library that can be used to download pictures (or videos) along with their captions and other metadata from Instagram. One of its features is the ability to explore posts associated with a particular hashtag.

However, Instagram's terms of service and API limitations frequently change, which can affect third-party tools like Instaloader. The number of posts you can retrieve at a given time might be limited due to rate limits set by Instagram.

Additionally, Instagram actively tries to prevent scraping of its platform. So even if a tool like Instaloader works today, it might not work tomorrow, or its capabilities might be reduced due to changes on Instagram's end or due to rate limits.

If you're planning on using Instaloader or a similar tool, there are a few things to keep in mind:

Always respect Instagram's terms of service. Unauthorized scraping can lead to account bans or legal action.
Stay updated with the library's documentation and community. If Instagram changes its API or anti-scraping measures, the maintainers of Instaloader (or its users) may find workarounds or solutions that they share.
Rate Limits: If you're making many requests in a short period, Instagram might temporarily block your IP address. Always use such tools judiciously to avoid being rate-limited or blocked.
To know the current state of Instaloader or how many posts you can fetch using it, you'd need to consult the library's official documentation or community channels, or try it out yourself. Remember, using any scraper responsibly and ethically is crucial.
