### ISSUE TITLE
Delay for each Download (Prevent IP BAN)

### ISSUE THREAD

**Issue by TElu22** [instaloader/instaloader#2115]
Truly sorry if this is already asked or explained (I could not find it myself - Maybe my english)

I was wondering if there was a `--flag` for setting a delay on each download.
Cause i just tested this out today and i already am banned because i did not expect it to download at lightspeed!! hah

Awesome tool though!!

**Comment by RichardHeise** [comment]
If you are on Linux use trickle. Like so:

```trickle -s -d 10 -u 1024 instaloader --user-agent Mozilla/5.0 --login <login> --password <your_password> --comments --abort-on=302,400,401,429 {account}```

trickle flags: 

-s Run trickle in standalone mode independent of trickled
-d <rate>    Set maximum cumulative download rate to <rate> KB/s
-u <rate>    Set maximum cumulative upload rate to <rate> KB/s


Using instaloader in command line with trickle hasn't gotten me a ban yet. I don't know how you could use it with a python script, but I suppouse python itself has some way of doing the same or you can just 

```trickle -s -d 10 -u 1024 python3 script.py```

Hope this helps.

**Comment by TElu22** [comment]
I'm not on Linux, and i have pretty basic python knowledge.
So do you mean run a script that then runs the instaloader script (which does one thing?) and repeat that?
Sorry for being a total noob at this. Open to learn new stuff though.

I saw one post that was talking about changing some lines in the instaloader scripts themselves.
Had no success with that yet though.

**Comment by TElu22** [comment]
Maybe its best i virtualize Linux or something.

**Comment by RichardHeise** [comment]
I would not suggest changing any of instaloader files: usually people don't change anything in the source code because doing so requires knowledge to do that, and it's not something that people outside de project will have.

You don't need to run Linux if you search for a way to limit download speed on Windows or python. Maybe even a sleep() function between requests would be enough, but I cannot say for sure this works since I haven't tried it out myself. One thing you can do, tho, is running it on WSL. It's very good and all you need to know are some command line commands on Linux, trust me it's not a hassle at all. And don't need to be sorry for being new to this, we are all learning.

**Comment by RichardHeise** [comment]
On the matter of limiting the download speed, you are correct: people are doing this because Instagram may ban the account you are using for scrapping or even your IP. Although not illegal, they don't want people to harvest data and overload their API. I have some suggestion for scrapping without getting banned.

1 - Don't use your own account, create a new one and try to use it a bit, follow some people, comment on some posts, add some people etc.
 
2 - Even if you do this, this account will get flagged as suspicious activity, that's fine tho, just don't scrape everyday all day and it will be fine.

3- DON'T USE FIXED IPS! If you try to use a hosting VM service for that, VPN or amazon AWS or any type of service with a fixed IP Instagram will most likely ban the IP without hesitating. This happens because fixed IPs are probably bots in the majority of cases and so Meta won't be banning a user's IP if they are sure you are not a common user. When scrapping from a domestic network, with a dynamic IP provided by your internet provider, you should be fine. Dynamic IPs are given to you by your internet provider, Meta won't ban those because your domestic IP is not your, your provider will give that IP to you temporarily and, at some point, they may change it to the IP of another client, so Meta won't ban those because they potentially would be banning people that have nothing to do with your scrapper. TL;DR: don't use VPNs, hosting machines or AWS for scrapping, use your domestic IP network.

4 - Setting a download limit or just not doing too many requests are good practice or Meta will get pissed at you for overloading their API. 

5 - Use a proxy if possible. Yes, proxies IPs are fixed and meta can ban those, but proxies are meant for that anyway. Just get a new IP on the proxy and you are fine. 

Those are suggestion I got by searching the web and talking to friends and teachers at my University (I'm in the last year of Computer Science). I didn't get ban and have been using Instaloader for some weeks now.

**Comment by TElu22** [comment]
Ok very great answers, But they all require either proxies/VPN's and other tools.
I just wished there was a simple `--sleep` flag or something in the app itself. Which would make sense IMO.

But for now i will try and research further from what you just said.

**Comment by RichardHeise** [comment]
I mean, you don't need VPNs or proxies for scrapping since their IP is fixed and só you probably will get banned faster. All you need is some way to slowdown download speed between requests... I would suggest creating a specific issue about the --sleep flag you mentioned so the devs can implement.

**Comment by leofidus** [comment]
I could also use a --sleep X flag. Maybe even something like wget's --random-wait which randomly waits between 0.5 and 1.5 times the specified amount, to make the pattern harder to detect.

Of course this is already trivially achievable if you use the python library, but for the cli having to resort to external tools is very inconvenient.
