### ISSUE TITLE
github-actions bot closes issues as completed when they are closed due to inactivity

### ISSUE THREAD

**Issue by tari3x** [instaloader/instaloader#2168]
Example: https://github.com/instaloader/instaloader/issues/1341. Ideally this should be marked as wontdo or equivalent - hopefully that's easy to configure?

On that note, if we mark an issue as duplicate, would it be possible to not mark it as completed either? Example: https://github.com/instaloader/instaloader/issues/1470

**Comment by Showmaster3000** [comment]
This issue is a little bit off topic, but related to development.
The mentioned issue 1470 was closed short after the "not planned" feature was added by github. So it was new. 
I think your request has to be splitted. It's not so easy to decide weather to close as "done" or "not planned". This works for issues without comments. Have a look at questions, especially with further comments, which often stay open until closing by actions bot. So was the question solved or is it not?

**Comment by tari3x** [comment]
https://github.com/instaloader/instaloader/issues/1341 was not solved at the point when the bot closed it. The actual issue is solved by https://github.com/instaloader/instaloader/issues/2159 a couple of days ago.

> It's not so easy to decide weather to close as "done" or "not planned".

  Exactly, and thus I think that the bot should make no attempt to make such a decision. Ideally it would simply say "closed due to inactivity" and no more. If it has to make a choice, "not planned" seems better since it's the conservative choice.

**Comment by tari3x** [comment]
What constitutes "activity"? I replied to https://github.com/instaloader/instaloader/issues/2172 in order to prevent the issue from closing, and yet the bot still closed it as "complete". This looks like a straight up bug to me.

**Comment by tari3x** [comment]
Likely relevant: https://github.com/actions/stale/issues/744

**Comment by aandergr** [comment]
Thanks for bringing this up. The version of `actions/stale` we used was older than the feature of distinguishing "completed" and "not planned" as close reasons. We updated it to close stale issues as "not planned" from now on.
