### ISSUE TITLE
Help with the --post-filter function with dates

### ISSUE THREAD

**Issue by maurivan** [instaloader/instaloader#220]
I would like to save the posts that were made from a certain date via command line. And I'm using the `command: --post-filter = "date_utc <= datetime (2018, 10, 4)"`

Full command I am using:
`instaloader PROFILE --post-filter = "date_utc <= datetime (2018, 10, 4)" --no-profile-pic --no-video-thumbnails --no-videos --no-compress-json --no -metadata-json --post-metadata-txt = "https://www.instagram.com/p/{shortcode}" --filename-pattern = {profile} {mediaid}
`

But with this command is saving all the posts and not the posts that were made from that date until today.

**Comment by aandergr** [comment]
Your command line is syntactically incorrect. Please fix your whitespaces.

**Comment by maurivan** [comment]
@e5150 Thanks!, I replaced <= to >= and worked :)

**Comment by chrisg991** [comment]
Is there a way to stop Instaloader processing further images once it has gone back as far as the specified date? I've borrowed your code from above, but it is taking ages to complete because it is checking every single post ever made by the given user to see if the date criteria is met. I'd like it to stop processing as soon as it finds pictures from 2018-10-03

**Comment by aandergr** [comment]
@chrisg991 Yes there is, but it requires Instaloader to be used as module from a python script, rather than the Instaloader CLI. One of the examples in our documentation does exactly that. Sorry for just copy&pasting, but my recent answer on a very similar question seems to fit well to yours:

> `--post-filter` naively evaluates for each post whether the given condition is met or not. It is unaware of the fact that the posts come in chronological order and its implications on which posts have to be filtered.
>
> So what you could do instead is to loop through the posts and *take* them, *while* they are newer than 2 days, stopping as soon as they don't fulfill that condition anymore. This is not possible with the CLI program *instaloader*, however, an example for how this can be achieved with an easy script using the *takewhile()* function can be found here: https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

_Originally posted by @aandergr in https://github.com/instaloader/instaloader/issues/839#issuecomment-708481817_

**Comment by chrisg991** [comment]
@aandergr Thank you for your reply. I spent a lot of time yesterday wrestling with an example similar to the one you sent, but I can't seem to get it to actually save the pictures to disk. Would you mind casting an eye over the code below and telling me what I'm doing wrong, please? Does `download_post` not actually save the file(s) to disk?

```
from datetime import datetime
from itertools import dropwhile, takewhile

import instaloader

import os
path = os.getcwd()
print(path)

L = instaloader.Instaloader()
L.load_session_from_file("myusername")
L.post_metadata_txt_pattern = ""
L.download_geotags = False
L.save_metadata = False
L.save_metadata_json = False
L.download_comments = False


posts = instaloader.Profile.from_username(L.context, "targetusername").get_posts()

print(posts)

#now = datetime.now()
SINCE = datetime(2020, 10, 10)
UNTIL = datetime(2020, 10, 25)

#print(now)

for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    #print(post.date)
    L.download_post(post, "targetusername")
    #L.download_pic("/root/test.jpg", post.url, post.date_utc)
```

**Comment by aandergr** [comment]
@chrisg991 download_post() saves the files to disk. Just swap `SINCE` and `UNTIL` in your script and then it works as expected (alternatively, swap `takewhile` and `dropwhile`). The `>` order relation on python datetime objects is such that `newer > older`. Actually, when I think about it, *since* and *until* were not wisely chosen variable names since the iterator returns them in reverse chronological order. We should have chosen something like *oldest* and *newest* instead.

**Comment by chrisg991** [comment]
Thank you @aandergr I've managed to get it working with your help!

**Comment by jameswan** [comment]
> 

What's the new code which works @chrisg991 ?

**Comment by chrisg991** [comment]
> What's the new code which works @chrisg991 ?

My final script is below. It needs the target username and the date you want to go back to as command-line arguments. The problem that I have noticed recently is that profiles with pinned posts break the script. Any suggestions on how to deal with that would be welcomed - I haven't had a chance to look into it myself.

`from datetime import datetime, timedelta
from itertools import dropwhile, takewhile

import instaloader

import os
import sys

#expect arguments in the following order: target_user historic_date
#where date is in format DDMMYY

target_user = sys.argv[1]
historic_date = datetime.strptime(sys.argv[2], "%d%m%y")
#print(historic_date)

L = instaloader.Instaloader()
L.load_session_from_file("my_username")
L.post_metadata_txt_pattern = ""
L.download_geotags = False
L.save_metadata = False
L.save_metadata_json = False
L.download_comments = False


posts = instaloader.Profile.from_username(L.context, target_user).get_posts()

print(posts)

tomorrow = datetime.now() + timedelta(days=1)

UNTIL = historic_date
SINCE = tomorrow



for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    L.download_post(post, target_user)
    

`

**Comment by jameswan** [comment]
Is there a flag to indicate whether a post is pinned? If so, then the code could ignore those pinned posts.
