### ISSUE TITLE
The procedure entry point PssQuerySnapshot could not be located in the dynamic link library KERNEL32.dll.

### ISSUE THREAD

**Issue by EveryDirection** [instaloader/instaloader#2225]
I can run Instaloader 4.10 and earlier versions on Windows 7. 

However, Instaloader 4.11, starting with 4.11rc1, will not run on Windows 7 and will instead immediately quit with the error message

`The procedure entry point PssQuerySnapshot could not be located in the dynamic link library KERNEL32.dll.`

because the Windows 7 version of kernel32.dll does not include the function PssQuerySnapshot(), which was added in Windows 8.1.

I am curious as to what 4.11 doing different that it needs PssQuerySnapshot() when earlier versions did not.

Is there any possible workaround or patch for this PssQuerySnapshot() issue on Windows 7? It's a shame because Instaloader has been working on Win7 for so many years, and then 4.11's use of PssQuerySnapshot() makes the program flat out un-runnable.

**Comment by Showmaster3000** [comment]
Windows 7 is obsolete since 2020, so updated software may not work any longer.
Beginning with instaloader 4.11, the target build environment is python 3.12 (before it was 3.8).
Python 3.8 is the last version which works on Windows 7. Python 3.9 requires at least Windows 8 (also obsolete)

The following workaround can currently be used:
- install python 3.8
- use pip to install instaloader (see [manual](https://instaloader.github.io/installation.html#install))
or
- download the source release of instaloader 4.11, extract and use it with `python instaloader.py`
