### ISSUE TITLE
How can I recreate a session?

### ISSUE THREAD

**Issue by samadbek-e** [instaloader/instaloader#2264]
I was logging in, and Instaloader said, you are logged out, please recreate a session

**Comment by phoenix1887** [comment]
> I was logging in, and Instaloader said, you are logged out, please recreate a session

Concerning how to do this on the CLI: 

I just figured this out of my own, I didn't see it written anywhere... Use the --login flag with your username and use --sessionfile "" to denote a session file with a blank string... This prompted me for the password again and created a new session. This is very useful because after 1k post downloads or so some of my accounts were getting blocked with 401 and 403 errors. Or sometimes you'll log in and immediately get these errors. Restarting the session can fix this sometimes...
