### ISSUE TITLE
sanitize_path  bug when we inform a path that contains "/" under linux.

### ISSUE THREAD

**Issue by softctrl** [instaloader/instaloader#2312]
**Describe the bug**
When we provide a path with subpaths to download a content the static method sanitize_path forces the replacement of "/" for '\u2215' with changes the behaviour under linux, from a path with a subpath to a new single path with the entire name:

/downloads/reels/other

will became a single directory

/downloads'\u2215'reels'\u2215'other

**To Reproduce**

`
import os
import instaloader

L = instaloader.Instaloader()
target_dir = "downloads/reels/temp"
os.makedirs(target_dir)
L.download_post(post, target=target_dir)
print(f"Content of {target_dir}: {os.listdir(target_dir)}")

ret = target_dir
ret = ret.replace('/', '\u2215')

print(f"Content of {ret}: {os.listdir(ret)}")
`

**Expected behavior**
Download the content to the correct folder, not to create a new one.

**Error messages and tracebacks**
It make a logic erros, not a sintax error, so it can only be seeing from debug a real code.

**Instaloader version**
4.12

**Additional context**

**Comment by e5150** [comment]
Pass `dirname_pattern="/downloads/reels/other"` when initialising `Instaloader`. Any occurrence of `"{target}"` in the dirname pattern will be replaced by a sanitised version of whatever `target` you pass to `download_post()`.

**Comment by imTHAI** [comment]
Hello,
This bug is still present. I was tearing my hair out until I came to see the issues.

**Comment by aandergr** [comment]
This issue is not a bug with Instaloader itself, but rather with how the `download_post` method is being invoked. The method sanitizes the `target` provided to it to ensure valid paths, which is why you're seeing the replacement of `/` with `\u2215`. Instead of passing the entire destination path to `target`, it's more appropriate to use the `dirname_pattern` parameter when initializing the Instaloader class. This allows you to specify a destination path for downloaded files. 

For more detailed guidance, please refer to the documentation on filename specification: [Instaloader Documentation](https://instaloader.github.io/basic-usage.html#filename-specification).

**Comment by imTHAI** [comment]
Ok Im glad a member of the team eventually clarify this issue opened since 3 months as a bug. It probably can be closed now.
Hv a nice day

**Comment by aandergr** [comment]
To clarify, this issue is not a bug with Instaloader but a case of incorrect usage, as was explained by a team member within eight days of the original post. The follow-up comment was also addressed within two days with the same explanation.

As a free, open-source project, Instaloader is maintained entirely by volunteers who offer their time and expertise without compensation or obligation. There is no support contract or guarantee of responses, yet we strive to provide assistance when we can. Given this, it’s neither expected nor justified to make demands or imply entitlement to immediate answers.

**Comment by imTHAI** [comment]
Yes, but it was you who came up with the official explanation and removed the bug tag. Until then I thought it was a bug and the previous answer was a workaround. 
Don't get me wrong, I wasn't criticizing you but really thanking you. And the project is great and all you devs are amazing.
