### ISSUE TITLE
Why does not --latest-stamps set config if I interupt instaloder?

### ISSUE THREAD

**Issue by FreePhoenix888** [instaloader/instaloader#2380]
I want to run instaloader with --latest-stamps option and have a config created. Maybe it is created because I see note that `AppData\Local\Instaloader\latest-stamps.ini` is used. But there I see something like 
```
[freephoenix888]
profile-id = 9999999
profile-pic = 461310553_980131430537583_403398051434667406_n.jpg
```
I do not want to download the whole profile to get `post-timestamp` option example

My problem:
Some time ago I have downloaded a profile but now I need to download only new posts that I have not downloaded before (I do not have local copy so --fast-update is not an option). I could use --post-filter but it checks every post and takes a very long time: https://github.com/instaloader/instaloader/issues/2379
Therefore I have been thinking about using --latest-stamps to download only, for example, last 200 posts, but I have no idea how to do that now without downloading the whole profile to get post-timestamp in my config

**Comment by ekalin** [comment]
If the download stops (and an iterator is saved so that you resume), `post-timestamp` is not updated (or created), so that you can run instaloader again with the saved iterator and resume from where it stopped.

When the download finishes (reaching a post that has already been downloaded, or having downloaded all posts if it's the first run) then `post-timestamp` is updated.

You can edit your `latest-stamps.ini` file and manually set `post-timestamp`, you just need to be careful to use the exact date format expected by Python. Then the next run will only download posts newer than that date and, if it finishes successfully, update `post-timestamp` for the next run.
