### ISSUE TITLE
tagged posts results "400 Bad Request" even no reason given, while stories and highlights are downloading normally.

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2399]
using 
`python3 /mnt/disk/__configs/615_import_firefox_session.py  -c /mnt/diskfirefox/default/cookies.sqlite`
to load cookies and then 
`instaloader --login=USER --fast-update    --user-agent "Mozilla/5.0.........." --abort-on=302,400,401,429,403  --stories  --tagged --highlights Lauren.horner/`

to download pics of user, TAGGED posts are blocked, they arent downloading while stories and highlights are downloading. 
What is happening? In many other profiles same error, or it let me to download some and then it stops with some error. 

Loaded session from /home/........
Logged in as .......
[1/1] Downloading profile lauren.horner
lauren.horner/2024-08-22_01-50-12_UTC_profile_pic.jpg already exists
Retrieving tagged posts for profile lauren.horner.
Resuming from lauren.horner/:tagged/iterator_Wha2sV92.json.xz.
[  1] 
Saved resume information to lauren.horner/:tagged/iterator_Wha2sV92.json.xz.

```
Download aborted: Query to https://www.instagram.com/graphql/query responded with "400 Bad Request": {"message":"feedback_required","spam":true,"feedback_title":"Try Again Later","feedback_message":"We limit how often you can do certain things on Instagram to protect our community. Tell us if you think we made a mistake.","feedback_url":"","feedback_action":"report_problem","feedback_appeal_label":"Let us know","restriction_enrollment_data":"","status":"fail"}.
Saved session to /home/.......
```

Note that i havent download anything from instagram for days. It is some feature of insta specially for tagged posts or is an error sourced to instaloder? 

without tagged posts... 

```
Loaded session from .....
Logged in as .......
[1/1] Downloading profile lauren.horner
lauren.horner/2024-08-22_01-50-12_UTC_profile_pic.jpg already exists
Retrieving highlights "San Diego" from profile lauren.horner
lauren.horner/San Diego/2024-10-01_22-28-08_UTC_cover.jpg already exists
[  1/ 25] lauren.horner/San Diego/2024-10-02_23-45-05_UTC.jpg exists json 
Retrieving highlights "North Carolina" from profile lauren.horner
lauren.horner/North Carolina/2018-07-16_19-59-48_UTC_cover.jpg already exists
[  1/ 26] Warning: Unable to fetch video from graphql of <StoryItem 2585982453185443758>: list index out of range
lauren.horner/North Carolina/2021-05-31_20-32-30_UTC.mp4 lauren.horner/North Carolina/2021-05-31_20-32-30_UTC.jpg exists json 
Retrieving highlights "NYC" from profile lauren.horner
lauren.horner/NYC/2023-06-16_22-45-42_UTC_cover.jpg already exists
[  1/ 19] lauren.horner/NYC/2024-08-22_18-31-40_UTC.jpg exists json 
Retrieving highlights "Jax" from profile lauren.horner
lauren.horner/Jax/2024-07-12_00-27-10_UTC_cover.jpg already exists
[  1/ 27] Loaded session from /home/elias/.config/instaloader/session-fotomelodios.
Logged in as fotomelodios.
[1/1] Downloading profile lauren.horner
lauren.horner/2024-08-22_01-50-12_UTC_profile_pic.jpg already exists
Retrieving highlights "San Diego" from profile lauren.horner
lauren.horner/San Diego/2024-10-01_22-28-08_UTC_cover.jpg already exists
[  1/ 25] lauren.horner/San Diego/2024-10-02_23-45-05_UTC.jpg exists json 
Retrieving highlights "North Carolina" from profile lauren.horner
lauren.horner/North Carolina/2018-07-16_19-59-48_UTC_cover.jpg already exists
[  1/ 26] Warning: Unable to fetch video from graphql of <StoryItem 2585982453185443758>: list index out of range
lauren.horner/North Carolina/2021-05-31_20-32-30_UTC.mp4 lauren.horner/North Carolina/2021-05-31_20-32-30_UTC.jpg exists json 
Retrieving highlights "NYC" from profile lauren.horner
lauren.horner/NYC/2023-06-16_22-45-42_UTC_cover.jpg already exists
....
Downloading stories
Saved session to /......

```

**Comment by estatistics** [comment]
does instagram has infiltrated instaloader? Why it is not planned when instaloader claims to archive instagram's posts, stories, and tagged posts, it is not planned? This is very counterintuitive without any explanation. 
You can say "it is impossible", "we cannot do it", or whatever.... BUT not planned? hey this is instaloader or instagram bot? Thankfully exist other tools to do it.

**Comment by aandergr** [comment]
Instaloader is a free tool, created and maintained by a small group of volunteers who dedicate significant time to this project. We handle hundreds of issues each year, which creates a considerable workload for our team. To manage this, we have a simple reporting process to make sure each issue report includes the essential details for us to investigate thoroughly.

When submitting an issue, users see a note explaining our requirements:

> Please understand that a bug issue that lacks the required information cannot be processed.

This notice is prominent, and the issue template itself asks for specific information. This guidance exists because we need certain details to understand each report and address it efficiently. When these details are missing, we apply a “no template” label and close the report, which indicates that it lacked the information required for us to proceed.

In this case, both the initial note and the “no template” label communicated the requirements clearly, so the reason for closure was fully transparent. This process helps us dedicate our time to actionable reports that benefit the whole community. When users disregard these guidelines and respond with complaints, it can feel ungrateful and discouraging, especially for those volunteering their time to provide this tool for free.

As an open-source project, Instaloader relies on respectful collaboration, and we’re happy to assist users who engage with us constructively. We welcome submissions that follow the template, as thorough reports allow us to work efficiently and effectively.

**Comment by estatistics** [comment]
i have given myself too, my time to open source projects. ok then, from now on i will fully follow the template. i will post the bug again... However, it is mysterious that so few people complain... when to tagged posts can be downloaded... whatever
