### ISSUE TITLE
See followers usernames from public profile

### ISSUE THREAD

**Issue by rafaelheck** [instaloader/instaloader#240]
Hi everyone,

Is there any way i can get the username of the followers of an public instagram?

**Comment by hgkmaxymus** [comment]
Do you mean just check who follows that person?

I don't think you can only get the usernames, but with the " `@profile` " parameter you can download the profiles who follow that person(profile). Since this software is a "downloader", I think you may need to download something. By default, I think it will download all public profiles and download only the id and profile pic of the private profiles (better use the directory and filename patterns parameters).

Parameter(or target, you name it):
> `@profile`
>  - All profiles that are followed by profile, i.e. the followees of profile (requires --login).

Source:
[https://instaloader.github.io/basic-usage.html#what-to-download](https://instaloader.github.io/basic-usage.html#what-to-download)

A valid instagram login is needed to be able to see the followers.
If you have one and are logged in (web browser), you can click the followers number and see who is following that profile.

I hope that help you while you wait for a dev to answer properly :)

**Comment by Thammus** [comment]
Hi,
as @hgkmaxymus already pointed out correctly:
> A valid instagram login is needed to be able to see the followers.

Instaloader isn't just a "downloader". It can also be used as a [Python module](https://instaloader.github.io/as-module.html), allowing to further customize obtaining media and metadata. Instaloader provides a [`get_followers()`](https://instaloader.github.io/as-module.html#instaloader.Profile.get_followers) method that can be used to obtain all followers of a given profile. This can be utilized in a simple Python script to achieve your goal.

```python3
#!/usr/bin/env python3

login_name = 'INSERT-YOUR-LOGIN-NAME-HERE'

target_profile = 'INSERT-TARGET-PROFILE-HERE'
# OR
#import sys
#target_profile = sys.argv[1] # pass in target profile as argument

from instaloader import Instaloader, Profile
loader = Instaloader()

# login
try:
    loader.load_session_from_file(login_name)
except FileNotFoundError:
    loader.context.log("Session file does not exist yet - Logging in.")
if not loader.context.is_logged_in:
    loader.interactive_login(login_name)
    loader.save_session_to_file()

profile = Profile.from_username(loader.context, target_profile)
followers = profile.get_followers()

loader.context.log()
loader.context.log('Profile {} has {} followers:'.format(profile.username, profile.followers))
loader.context.log()

for follower in followers:
    loader.context.log(follower.username, flush=True)
```

**Comment by rafaelheck** [comment]
Thanks @Thammus !!

I was using profile.followers wich give me the number of followers, for some reason i didnt saw .get_followers before. Many thanks!!

**Comment by hendi26** [comment]
It work. Thanks

**Comment by ganeshbelgur** [comment]
There is a catch though.

After retrieving ever ~1000 followers of a profile, Instaloader waits for 10 minutes (Error: 429 - Too many requests) as a cool down period to not overload the Instagram servers with too many request. If there are a million followers to query this could take a very long time!

When I looked into the Profile.get_followers() method, it is basically making a Graph API call to get one user at a time, I think via a generator. I know the hash code for getting followers data is `37479f2b8209594dde7facb0d904896a`. Since I am new to Graph API itself, can someone please help me construct a GET request that would fetch me all the followers data in one request? Is this even possible?

**Comment by Zubair17323** [comment]
@Thammus still getting an error instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 400 - Bad Request. after logging in. If you can help. I think my ip is being blocked

**Comment by hannu021** [comment]
IF YOu have any luck in getting followers in one go please let me know

**Comment by RaildoBarros** [comment]
Thanks! @Thammus
