### ISSUE TITLE
Instagram blocking requests

### ISSUE THREAD

**Issue by hadisotudeh** [instaloader/instaloader#2408]
Hi there,

It seems Instagram keeps blocking simple requests just from the beginning. Is it a common issue?

Just to get the list of followers of a public profile, I receive the following error right in the first request!

Error fetching data for ...: 400 Bad Request - "fail" status, message "checkpoint_required" when accessing https://www.instagram.com/graphql/query?....

**Comment by evgen-dev** [comment]
"checkpoint_required" this is a type of challenge. This challenge can be solved programmatically.

**Comment by FelixWu1110** [comment]
> "checkpoint_required" this is a type of challenge. This challenge can be solved programmatically.

hey, could you share your method to tackle this problem?

**Comment by danielbyiringiro** [comment]
There was some changes in the Instagram GraphQL API, so that's why some features has not been working. I was getting a "feedback_required" error when trying to access comments from Instagram posts but it turned out that it was due to the API change. I did some patches for getting the comments and i have attached the patched code.
[instaloader.zip](https://github.com/user-attachments/files/17509648/instaloader.zip)

**Comment by hadisotudeh** [comment]
@danielbyiringiro, How can we use the patch in python?

**Comment by mosandov** [comment]
@danielbyiringiro thank you so much!!!!!

**Comment by danielbyiringiro** [comment]
> @danielbyiringiro, How can we use the patch in python?

Follow this steps

1. Find where the sitepackages directory for the python version you are running is.
2. Move into the sitepackages directory
3. Delete the instaloader folder within the sitepackages directory
4. Download the patched version which i attached to my earlier comment
5. Unzip it within the sitepackages directory
6. Now run your code and hopefully it will work

**Comment by mirh** [comment]
Fixed in #2384 I guess
