### ISSUE TITLE
only scrape posts after X date?

### ISSUE THREAD

**Issue by TheSinfulKing** [instaloader/instaloader#2415]
I know we have --post-filter, and--storyitem-filter filter. They work well.

However, I noticed when scraping an account with the post-filter set to yesterday, the program still queries all of the posts of the account. It just skips pretty much all of them.

What is it doing behind the scenes? It does appear requests are firing, because I get rate limited after a while. This seems like a lot of unnecessary work with such a restrictive filter applied

I was thinking I could add a post-timestamp entry to the latest-stamps.ini to avoid this, but is there an easier way?

**Comment by aandergr** [comment]
The behavior you're observing with `Instaloader` results from how Instagram's API handles data retrieval. Even with `--post-filter` and `--storyitem-filter`, `Instaloader` still queries all posts, filtering only after retrieval. Instagram’s API returns posts in a paginated format with the newest items first, along with a pointer to the next page, without support for a date range query. This means `Instaloader` must request all posts in sequence, skipping them after they are retrieved if they don’t match the filter.

Using `--latest-stamps` can reduce redundant downloads. By maintaining a timestamp in `latest-stamps.ini`, you avoid re-downloading posts that predate the specified entry. For example:

```ini
[username]
profile-id = 123456789
post-timestamp = 2021-05-10T18:26:39
```

This method is useful for cases where you only want new posts after a certain date and want to avoid hitting Instagram's rate limit due to repeated full retrievals.

Using `--latest-stamps` is particularly convenient for typical use cases, as it automatically updates the timestamps in the configuration file after each download session. This way, you don’t need to manually edit or manage timestamps for each profile—Instaloader will keep track of the latest downloaded post for you. Simply include `--latest-stamps` in your command, and it will ensure only new posts are downloaded, reducing redundant requests.

**Comment by TheSinfulKing** [comment]
Thanks!
