### ISSUE TITLE
Instaloader - generate folders for separate downloads (e.g. highlights, stories)

### ISSUE THREAD

**Issue by ejbytes** [instaloader/instaloader#2424]
**Provide us a use case of the feature**
How could the user invoke the new function? Same: --stories
Which problem would it solve? Grouping locations.
If new information is obtained, how would it be further processed? Self explanatory..

**Describe the solution you'd like**
instaloader --login -l me -pw mypw --stories
and a folder is created in which any new stories would get saved to a folder, "stories"

**Describe alternatives you've considered**
How do you achieve the here-described goal without the feature you are requesting? Manually sifting through hundreds of photos and ha ha ha haaaaaaaaaa

**If the feature request is accepted, would you be willing to submit a pull request?** 
Ah, since I am not actively programming on this open source.. ummmmm
Yes / No

**Additional context**
Add any other context about the feature request here.

**Comment by sawelmout** [comment]
### - **for Stories:**

.\instaloader username --dirname-pattern=username\STORIES --no-posts --no-profile-pic --stories --no-video-thumbnails --login=yourusername"

### - **for Posts pictures:**

.\instaloader username --dirname-pattern=username\POSTS --no-videos --no-profile-pic --no-video-thumbnails --login=yourusername

### - **for POSTS videos:**

.\instaloader username --dirname-pattern=username\POSTS --no-pictures --no-video-thumbnails --no-profile-pic --login=yourusername

### - **for PROFILE PICTURE:**

.\instaloader username --dirname-pattern=username\PROFILE_PICTURE --no-posts --login=yourusername


NOTE: I tried to do it with Highlights, but it doesnt download each highlight in a folder with the name of it, 
I just use the normal way which is this: 
.\instaloader username --no-posts --no-profile-pic --highlights --no-video-thumbnails --login=yourusername
If someone finds a way, I would be grateful.



**- Modify "username" with the username you want, and don't forget to modify the username which is after "--dirname-pattern="
- Modify the path which is after "--dirname-pattern="
- Modify "yourusername" with the username of your account (if you know you know).**

**Comment by ejbytes** [comment]
@sawelmout Thank you! I will try this! I wasn't sure how the " --dirname-pattern" pattern was used. This clears it up for me.

**Comment by ejbytes** [comment]
@sawelmout You seem to know the rules pretty well. A quick question, Right now the files get the "pattern" "2024-11-01-a-UTC_XX.jpg" Do you know how to "pattern" a format such as "2024-11-01 15.30.35 3492820391765452623_1956889964.jpg". "Date military time created filename".

https://instaloader.github.io/basic-usage.html#filename-specification

I see this: {date_utc:%Y-%m-%d_%H-%M-%S}
but I want this? 
{date_utc:%Y-%m-%d %H.%M.%S}

I see this:
instaloader --filename-pattern={date_utc} {filename}
but I want this? 
instaloader --filename-pattern={date_utc:%Y-%m-%d %H.%M.%S} {filename} ?

**Comment by sawelmout** [comment]
The main issue is likely with the formatting placeholders you used, specifically {date_utc:%Y-%M-%D %H.%M.%S}. 
Here are a couple of adjustments and explanations to help get your desired format:

Correct Placeholder Formatting:
{date_utc:%Y-%m-%d %H.%M.%S} should give you the format "2024-11-01 15.30.35" where:

%Y is the four-digit year
%m is the two-digit month
%d is the two-digit day
%H is the hour in 24-hour format
%M is the two-digit minute
%S is the two-digit second

Note: Use lowercase %m and %d for the month and day, not uppercase %M and %D, as uppercase represents different placeholders (%M for minutes and %D is not standard).


Try this:
--filename-pattern="{date_utc:%Y-%m-%d %H.%M.%S} {filename}"

or you can use {mediaid} instead of {filename} if you dont want the long numbers in the file name. It would be this:
--filename-pattern="{date_utc:%Y-%m-%d %H.%M.%S} {mediaid}"


**If you have any more questions, I would be glad to help.**

**Comment by ejbytes** [comment]
@sawelmout Your solution worked perfectly! 

--filename-pattern="{date_utc:%Y-%m-%d %H.%M.%S} {filename}"
resulted in my image filename:
2024-09-02 05.10.32 481881402_6011462445852892_5086513795461141965_n.jpg

This is great because there is another program that I also use and this is the exact format. I'm comparing the strength of one against the other. Without duplicating the files this works perfect. 

Thanks!

**Comment by MonkeyKingViper** [comment]
Just an additional FYI here, the highlights are stored in a strange way in Instagram which is why it's not possible to pull and save them like Stories, Posts, and Reels. I was having a lot of issues trying to come up with something, but after looking in the closed trouble tickets about highlights, this was found to be the reason. They will always be weird and unlike the others.

**Comment by sawelmout** [comment]
@MonkeyKingViper Thank you for sharing! I nearly fried the rest of my brain cells trying to find a way to make it work. Since I didn’t find much, I ended up using the command .\instaloader username --no-posts --no-profile-pic --highlights --no-video-thumbnails --login=yourusername, which downloads each highlight to its own folder. Then, I download the posts and stories inside a subfolder named after my username. And it works… for now.
