### ISSUE TITLE
Downloading public profile without login not working

### ISSUE THREAD

**Issue by mike855** [instaloader/instaloader#2427]
Hello,

I try to download my profile (public) without login, and I'm asked for login.

```
[root@muguet instaloader]# instaloader michaelmuguet

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=michaelmuguet to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
michaelmuguet: Redirected to login page. Use --login or --load-cookies.

Errors or warnings occurred:
michaelmuguet: Redirected to login page. Use --login or --load-cookies.
```

Version 4.14

**Comment by aandergr** [comment]
I tested this, and it works as intended. The issue you’re experiencing is not due to a problem with Instaloader but rather Instagram’s restrictions. Instagram has significantly limited access to most of its content for users who are not logged in. This is why you’re being redirected to the login page.

To resolve this, you’ll need to use Instaloader with a logged-in session, either by specifying `--login` or by loading cookies with `--load-cookies`. This is the only way to bypass Instagram’s restrictions for accessing user profiles.
