### ISSUE TITLE
Is it possible to continue previous downloads?

### ISSUE THREAD

**Issue by tehgarra** [instaloader/instaloader#280]
I thought that would the case when I see that the session is saved but I see that I misunderstood that function

Sometimes when I'm deep in the download process (3900/4785) ,I have to leave for an extended period of time and the conmputer is usually turned off. When I restart the program, is just cycles tthrough everything reporting that it exists and the json is unchanged for every single item until I reach the place I left off. Is there anyway around this

**Comment by aandergr** [comment]
No, it is not yet possible to resume a stopped Instaloader instance. However I like the idea, maybe we could save the `end_cursor` or some other information in a file to resume downloads. It requires some experiments though - I leave this issue open as *feature suggestion* for when someone finds the time to work on this. 

The "session" it saves refers to the http session cookie which Instagram generates to identify your login, Instaloader saves it to avoid having to type in the password everytime.

**Comment by oktayekici** [comment]
This is absoultely what I need because after gettin too many requests error, I have to start from beginning which only checks the same posts again (with False return) and get the same error after a while. If you have time, you can start the code every week (or adapt for your hashtag) but if you don't have time, you get stuck.

By the way, @aandergr thank you very much for the package, it helped a lot.

**Comment by aandergr** [comment]
This is implemented with #732 now.
