### ISSUE TITLE
[question] when using @profile, is it possible to exclude an account from downloading/updating? 

### ISSUE THREAD

**Issue by tehgarra** [instaloader/instaloader#321]
There are some accounts that I try to avoid archiving but it will get invoked with @profile. Is there a way around this? I

**Comment by aandergr** [comment]
Per default, Instaloader names its target directories like the targets, so you can re-download targets with
```
instaloader `ls -d */`
```

Hence you could run `instaloader @profile`  once (pass `--no-posts --no-profile-pic` to just let it create the profile directories), delete the profiles you don't want to have updated, and from there on always invoke Instaloader with the command above rather than `instaloader @profile`.

**Comment by tehgarra** [comment]
Wow that's amazing. Thank you!
