### ISSUE TITLE
Option to Use UserID as input instead of userName

### ISSUE THREAD

**Issue by github-userx** [instaloader/instaloader#325]
Would be great as I am currently still using github.com/Snbig/instaTrack to convert userIDs generated by instaloaders scraping back to UserNames in case a user changed their username.

UserID would be much easier to keep track of users, e.g. when we use a .txt with many different usernames as input

**Comment by github-userx** [comment]
But how does this work? If I downloaded justinbieber in the past, and he changes his username to justinbieber321 - I have to know his new username.

I was more talking about keeping track of Accounts and their photos without having to manually keep track and know their new usernames. 

See also: https://github.com/snbig/InstaTrack <https://github.com/snbig/InstaTrack>

(also what happens if my already downloaded user justinbieber changes his username to justinbieber321 and another completely different user takes over the old username? When I put in justinbieber it will just get the new accounts data (who has a different userID) but I will have lost track of justinbieber321 since maybe I do not know his new username yet!)

**Comment by github-userx** [comment]
@aandergr i think there should be an option to use userID as input:

python3 instaloader.py —user-id=123456789

**Comment by github-userx** [comment]
@aandergr i think there should be an option to use userID as input:

python3 instaloader.py —user-id=123456789

**Comment by MatthieuBonenfant** [comment]
Ewoks Folge Tapes - 3 Episodes (German)
https://mega.nz/#!J9l2WQ7B!xZ-R6C5XC1xwoFNCilMlu0iYr8WSWTpPwZ9oQKp2OXw
[https://cms2.mega.nz/5b342017f1b709b7098b4567.png]<https://mega.nz/#!J9l2WQ7B!xZ-R6C5XC1xwoFNCilMlu0iYr8WSWTpPwZ9oQKp2OXw>
MEGA<https://mega.nz/#!J9l2WQ7B!xZ-R6C5XC1xwoFNCilMlu0iYr8WSWTpPwZ9oQKp2OXw>
MEGA provides free cloud storage with convenient and powerful always-on privacy. Claim your free 50GB now
mega.nz


Source:
https://www.youtube.com/user/Aggerstern/search?query=ewok

Matthieu Bonenfant
mmathab@hotmail.com

________________________________

**Comment by aandergr** [comment]
> But how does this work? If I downloaded justinbieber in the past, and he changes his username to justinbieber321 - I have to know his new username.

No you don't. Instaloader stores a file named `id` with each profile, and when downloading a profile whose id file already exists, it uses the user id stored in that file rather than the profile name to identify the profile to download.

> I was more talking about keeping track of Accounts and their photos without having to manually keep track and know their new usernames. 

No need to do so.

> also what happens if my already downloaded user justinbieber changes his username to justinbieber321 and another completely different user takes over the old username?

As a consequence of what I wrote before, it would download justinbieber321 in that case,

> When I put in justinbieber it will just get the new accounts data (who has a different userID)

False.

Hence, I don't see any purpose of your suggestion.

If you really need to fetch a profile and only know its user id, do the following
```
mkdir some_directory_name
echo USERID > some_directory_name/id
instaloader some_directory_name
```

The code for that logic is here:
https://github.com/instaloader/instaloader/blob/6d5bb1e181636cd15e69455372435295586f66f2/instaloader/instaloader.py#L886-L929

**Comment by aandergr** [comment]
Little Instaloader History: This was one of our first features, introduced in September 2016 with Instaloader version 1.1.

No need to manually track user ids ever since.

**Comment by VasiliPupkin256** [comment]
It is still inconvenient on batch updates. The batch file is only containing old usernames and on the next run when instaloader have already renamed its directory to the new username the error "no such user" will be reported and no updates for the renamed user will be made. Using instaloader one need to always list directory names and pass them to instaloader instead of a file with username list.

**Comment by github-userx** [comment]
@aandergr I see, so it’s simply required to have and keep the already downloaded Instagram users (data) in the directory, so Instaloader can look into the userID file in /justinbieber and „learn“ that he changed his username to justinbieber321?

So did I get that right, that If I already have a folder named justinbieber that I downloaded last year And he now has changed the username to justinbieber321, I will get justinbieber321 's Media flies when I give justinbieber to instaloader?
If /justinbieber/userid doesn’t exist, instaloader will not know the old useraccount and just download the current person named justinbieber.

I guess I never thought like this because I always move all the downloaded files to external drives etc. So it would hust have been much more convenient to work with a input file and userIDs that never change.

    # Canadian Singer Justin Bieber
    123456789
    # Singer Brittney Spears 
    123456789123
