### ISSUE TITLE
Login failed. Require checkpoint

### ISSUE THREAD

**Issue by Mr-Somebody** [instaloader/instaloader#328]
**Describe the bug**
Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/13093078879/xHaMmJoU73/, follow the instructions, then retry

**To Reproduce**
import instaloader
L = instaloader.Instaloader(download_pictures=False, download_videos=False, download_video_thumbnails=False, download_geotags=False, download_comments=False)
L.login(username, password)

**Expected behavior**
Require send verification code to your mail address and input code in browser

**Error messages and tracebacks**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mahua/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 425, in login
    self.context.login(user, passwd)
  File "/home/mahua/.local/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 216, in login
    "follow the instructions, then retry.".format(resp_json.get('checkpoint_url')))
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/13093078879/xHaMmJoU73/, follow the instructions, then retry.

**Instaloader version**
4.2.7

**Additional context**
Tests on this issue show that, every time you change to a new login client, it requires checkpoint.

**Comment by gnaslaniec** [comment]
I'm having the same issue, the program was working fine until yesterday. Tested it with 4 different accounts and all of them throws the same exception.

**Comment by Mr-Somebody** [comment]
> I'm having the same issue, the program was working fine until yesterday. Tested it with 4 different accounts and all of them throws the same exception.

Yes, it worked fine before yesterday. I also tested with multiple accounts and multiple ips.

**Comment by ZHANGBADAO** [comment]
I also met this problem:
Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/13093078879/xHaMmJoU73/, follow the instructions, then retry

I follow the instructions in browser, still logon failure

**Comment by arnmtk** [comment]
Experiencing same issue here. Seems like Instagram changed something recently.

**Comment by luponata** [comment]
This problem appear if the instagram account got blocked due to someone trying brute-forcing it, after trying to log with the account on a web browser, and confirming the pin code received on the email inbox (because after the brute-force the account is locked, and you can't login until you enter the received pin), the problem disappear

**Comment by kareemrasheed89** [comment]
Am experiencing same issue

**Comment by AnishRedmond** [comment]
same here :worried:

**Comment by urvanov-ru** [comment]
I have the same problem too.

**Comment by Crisfon6** [comment]
Same problem  :( help!!!

**Comment by not-tanh** [comment]
> > This problem appear if the instagram account got blocked due to someone trying brute-forcing it, after trying to log with the account on a web browser, and confirming the pin code received on the email inbox (because after the brute-force the account is locked, and you can't login until you enter the received pin), the problem disappear
> 
> My script is working good, anyone tried to do what i wrote before?

Wish I could. I didn't get any pin code on my email inbox

**Comment by Josenyldo** [comment]
Just add a 10 second sleep to each download track. Example: every 800 items downloaded, wait 10 seconds. It worked.

**Comment by Massa4usetts** [comment]
The bug is reproducing again. Using pyTelegramBotAPI 4.12.0 and instaloader 4.9.6

`While trying to download stories i got a message Login: Checkpoint required. Point your browser to www.instagram.com/challenge/AXEHCMEKofRt_9a-0Zfgu7qSKmuBvUr0Wq8tp6JHx8jHdYgvfQN0YxAlCSBeUkgUPjtazg/AfxqzifP9AcjTSbQlmObVE0VfJ9lpawFDSP8f7y4PxE68xfFMcOPEcv4eX1SHChIzpDXnzbZuM_OwQ/?challenge_context=Af5jcotThWKG6K0Z_NyWhIYQ0M1J1q86XhuGzi3Rf1Y8gtjBk8ElsJnlz4s1fjD-hThrm8meW1GIIsdostp5jsyIyn3mauEF8NI-k7CbKGr-nzbs_FNJ8f9vYkdBJnXUEBWWvOWRNyuLd3IRbdEdFCCyMzVL-IJZXIC9ihn4e_zbOe5bm8UzYQmgqJMPBEbvGBkNsutERPZFbyPTzrj0v9AP94XmROpyzIcBLoVq7QVNuFtu0gwoYW7Eqo2wGozfNnRrq3wL_vzw9624you1B3uijvYPX-KoW8rAzmwMmWFLzz3Q5S2IDm3C-GevYqtzMjcqRGzAL2OUtY8qAyOM4tR6NmoABB-NXJk_UbnIzUYH9tulgXsxIQyEtU6PFpu0hqHaG46MiO9iha4BJkZZ9JMFLxIiChX9s12Wmz-Yix0SU1IjY9ofAwRbWyKTN_nEgWRJmbpgYunvDMOhGN0wfwZLpMJOw0RANkLiLkVb6VrwFitrYlUmB0M1pyo4ztgJk4GYb9yzBem2YTe53s24Q9_FfqmCNrtLOVxNSRWhAafCiTlBjrtm4a0cao_E5497msj6DTc2T0zfqZordv8CUavJbeZry64p_qUEHeOGaTLKRIZCOJyq5IrS8ooFzb7gKQSZEH6-WwZpgi2zaZQOzvUy1qpxAu_uiSBbXAMAzUqFcqRw37cW7s1Vi5FD927fgNvscKhF0yTQP0e2su2b4uqrrJkspX2tgBQxGOav3PqPLUEYlgKVMkDy00kk1OgBMYFSPs4N5_etMRn1TSI1dHRIUXh0RnSZxo8iIKmbFucWn-JIxFkTmdwkm6eW2vBSCxMkYLZG3MD70wCaeRlnFxxuHqLvUs0-7eti_oDwQMD1SEZQldwns5f-EkCyC5y4tqD0hNbcOFd_W-veFIFeAAleQyPXoMJD5Lgw32e2-_p71cJBJGzL-KbqihuKY3A_Gx7sLVQsGKgZ-M_qaOuklO35HAn6-s1oIYeR1Gln8Je_5wrsg1LF4gsp5D6MhjdB5UAJbOK6OqTEJmo1zujqe5XOh0WUYw1zvqwGcfKbghx3vxX-ITuO2nqmX3tKaHidQPPKdFaaqXfVum7KP6wRTfnDS5W9_7C8omBhBOgEcxzunmTzmAQpRyrIAg2fvaHKgWpHdM5EhyVQpwJtXUh7rbA5r-fFSEZq0RHpNzVIrw - follow the instructions, then retry.`

But if i open in nothing happen, just regular Instagram feed page is opening

**Comment by Toktorov** [comment]
Lol

**Comment by m2k7m** [comment]
Hi, I was facing this problem but I manage to slove it in 3
1. Enable 2FA 
2. Update your login code to given code
```py
import instaloader

L = instaloader.Instaloader()

try:
	L.login('username','pass')
except instaloader.exceptions.TwoFactorAuthRequiredException:
	L.two_factor_login(111111) # Replace with your 2FA code

L.save_session_to_file('insta_session') # Maybe you want to save your session
```
3. Have fun

Good luck everyone.
