### ISSUE TITLE
Featue Suggestion - "Listen" for new posts and download them.

### ISSUE THREAD

**Issue by redcupperboi** [instaloader/instaloader#341]
Would it be possible to have Instaloader capture new posts as they're made? I launch an Instaloader script a few times a week to capture stories from friends. A lot of the time I'll miss some since there is that 24h limit to watch them. It would be so convenient to launch Instaloader in a listening state that automatically scrapes new content posted by an account.

Thanks for your work, this software is awesome.

**Comment by aandergr** [comment]
Nice idea, however, at the moment I have no idea how to realize that. But I can imagine that we find a way in the future, since there do exist some kind of notifications also in the web app.

Until then, we have to keep our Instaloader scripts as a cronjob, which you can run twice a day without any problem, such that you never miss any story :)
