### ISSUE TITLE
429 Limits

### ISSUE THREAD

**Issue by Mezzical** [instaloader/instaloader#368]
Hi,

Are the limits re: 429 errors tied to an IP address or user (if logged in)? Can you run multiple instances if you use different logins?

Thanks

**Comment by aandergr** [comment]
I'm convinced they're tied to the user when logged in, and tied to the IP otherwise. Hence, running multiple instances with different logins should work.

Could you try it and tell us your results?

**Comment by hgkmaxymus** [comment]
It is per user (I alternate when downloading HD profile pictures). But, I don't know if today instagram is unstable since I am getting the error way earlier and with two accounts and even when not logged in, or they are checking the IP. When I try it using an anonymous window, it asks me to login right away.

So, I think it blocks first the user, then the IP. I know the instagram API seems to be unstable today, so the IP block might not exist, but the different logins did happen way before.
