### ISSUE TITLE
Can't login, the challenge page not only require a code.

### ISSUE THREAD

**Issue by sleiter88** [instaloader/instaloader#373]
**Describe the bug**
Instaloaded worked fine until today. I've implemented it inside of EC2 container in amazon. I follow the challenge steps without any problems but today I've got a different challenge page that broke the flow and don't let me login.

**To Reproduce**
I don't know how to reproduce it, it happens suddenly.

**Instaloader version**
4.2.8

**Additional context**
[Heres the screenshot of challenge page.](https://imgur.com/a/U7PPMzA)

**Comment by aandergr** [comment]
Doesn't look like a bug. Instagram considers your login attempt suspicious because it differs from how you usually login, which is natural due to your EC2 most likely being in a different location than you usually are, and due to Instaloader using a different user agent. It should work after clicking on "he sido yo".
