### ISSUE TITLE
No way to save content using original filename?

### ISSUE THREAD

**Issue by avekifes** [instaloader/instaloader#395]
I read a post some months back about how --filename-pattern doesn't support/have an option for original filenames (based on the URL below, that would be "67364184_671839889994326_1590822563240188615_n"). Is that still the case? If so, why is that?

https://scontent-lga3-1.cdninstagram.com/vp/d2899631a4e1053ec39ce2321631eaee/5E046CE1/t51.2885-15/e35/s1080x1080/67364184_671839889994326_1590822563240188615_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com

**Comment by aandergr** [comment]
That is still the case. It would be not so easy to implement, because the Post (class `Post`), whose properties are available for --filename-pattern, represents one post, which in case of a sidecar consists of multiple images and hence multiple image URLs. We'd have to somehow change our internal structures to enable that feature.
