### ISSUE TITLE
Is it possible to grab only a specific number of the posts, comments and likes?

### ISSUE THREAD

**Issue by amansingh9097** [instaloader/instaloader#421]
First of all, THANK YOU for writing out 'Instaloader'. It has helped many of us in many ways.

Now as its common to get into the **rate-limiting problems** and people have to wait from 19 to 466 seconds to grab the next batch of posts. I was wondering if its possible to grab just some of the posts/comments/likes. Say if I just want to see the first 20 or 30 posts of any username, is there any direct way to achieve this?

Thanks,
Aman

**Comment by amansingh9097** [comment]
cc: @aandergr @Thammus

**Comment by tradingbase** [comment]
I am watching this issue, because I have the same problem. It would be highly appreciated, if there is a chance to get a parameter for an offset, where to start. We have accounts with > 500 posts, where we like to download the comments, too. And we always get stuck after a while. With an offset we could start at an older position without re-loading the first 100 posts/comments again and again.
I have no clue, whether this is easy to achieve or not, but it would be nice, if you could at least have a look at it before closing this issue. Thanks for all your work on this project, btw.

**Comment by amansingh9097** [comment]
not sure if it'll ever be answered or not..
