### ISSUE TITLE
Newest Hashtags download

### ISSUE THREAD

**Issue by michelinhn** [instaloader/instaloader#473]
Hello,

its possible to download only the newest Hashtag-Pictures of a specific Hashtag?

**Comment by aandergr** [comment]
For hashtags, there is the option `--count` to limit how many posts should be downloaded: https://instaloader.github.io/cli-options.html#cmdoption-count

Also, there is `--fast-update` for when you want to only fetch the new posts since the last time you downloaded: https://instaloader.github.io/cli-options.html#cmdoption-fast-update
