### ISSUE TITLE
":tagged" is invalid folder name on Windows

### ISSUE THREAD

**Issue by XPanniX** [instaloader/instaloader#526]
**Describe the bug**
The folder where tagged posts are stored is named ":tagged". When trying to use the script on Windows or copying the directory to Windows you aren't able to open this folder. This happens because colons aren't allowed in Windows file/directory names. You're even unable to rename the directory.

**To Reproduce**

Download the posts of a user with the --tagged flag and try to open the ":tagged" directory on windows.

**Expected behavior**

The foldername should not contain a colon or there should be a flag to prevent such invalid characters.

**Instaloader version**
4.2.10

**Comment by gituzzer** [comment]
For tagged, a fix/workaround is easy, instaloader.py:

downloaded = self.download_post(post, target if target else Path(profile.username) / Path(':tagged'))
--> change to 'tagged'.

A similar but harder problem exists with highlights, since the folder name is created by whatever chars are part of the highlighted set.
Sometimes it's illegal folder name like  ".", sometimes it's ".." or ":" or some illegal emotes or other illegal chars.  
I added an Exception to my private code to deal with these but there are a lot of illegal combos.
It's not good to filter them where they are checked in code as it'll affect all the folders being created e.g. stories or profiles, so a fix like this is not good to replace specific chars.

**Comment by XPanniX** [comment]
> It's not good to filter them where they are checked in code as it'll affect all the folders being created e.g. stories or profiles, so a fix like this is not good to replace specific chars.

I don't understand your argument against sanitizing file- and foldernames. Could you explain it a little further? Sanitizing by default could be a bad idea but giving the user the option to do so would be nice. Therefore a new flag could be added that that only allows certain (e.g. ASCII) characters. Just like `--restrict-filenames` does in youtube-dl. Here is it's implementation: https://github.com/ytdl-org/youtube-dl/blob/97c822b3d5221d612748e1b589c87603bbae8a4a/youtube_dl/utils.py#L2112

**Comment by psylenced** [comment]
Is this related to issue  #304 ?

**Comment by XPanniX** [comment]
> Is this related to issue #304 ?

I don't think it's directly related to #304. The faulty commit you mention in #304 is about invalid (back)slashes in paths while this issue is about invalid folder-names.

**Comment by Thammus** [comment]
Using the script on Windows should be no problem since the colon gets replaced by a unicode equivalent that does work on Windows directories. If you intend to copy the directory from a filesystem that supports colons to another one that does not support it, just rename the directory beforehand. Another possibility to overcome the unsupported folder names is to use `--dirname-pattern` to change the output directory to something that does not include unsupported characters in the first place.

**Comment by 89z** [comment]
https://github.com/instaloader/instaloader/issues/1352
