### ISSUE TITLE
Fails after Downloading Stories

### ISSUE THREAD

**Issue by duraki** [instaloader/instaloader#534]
**Describe the bug**
Images not downloading.

**To Reproduce**
`./instaloader.py --login osint.profile --profile profile_name --geotags --no-compress-json`

**Expected behavior**
Download images + geotags.

**Error messages and tracebacks**
No option for verbose? Output:

```
Loaded session from /var/folders/gg/4j75ppv12g994lhydklh36tw0000gn/t/.instaloader-dx/session-osint.profile.
Logged in as osint.profile.
profile_name/2019-10-04_11-08-14_UTC_profile_pic.jpg already exists
Loaded session from /var/folders/gg/4j75ppv12g994lhydklh36tw0000gn/t/.instaloader-dx/session-osint.profile.
```

**Instaloader version**
```
## Tried two versions, latest, and stable from pip.

./instaloader.py --version
4.3a2

instaloader --version
4.2.10
```

**Comment by aandergr** [comment]
> **Describe the bug**
> Images not downloading.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> `./instaloader.py --login osint.profile --profile profile_name --geotags --no-compress-json`

Remove `--profile` from your invocation.

Background: Instaloader allows the command line options to be abbreviated to a prefix, if the abbreviation is unambiguous (the prefix matches a unique option). For example, instead of `--geotags`, it suffices to use `--geo`. Hence, in your invocation, `--profile` is matched to the (deprecated, yet still supported) option `--profile-pic-only`, disabling the download of regular posts.

Sorry for the confusion this may have caused in that case.

**Comment by duraki** [comment]
Ah I see, now it's working properly. Thanks for pointing to right direction. I will close this for now, hope it will help others with similar question. Looking forward for stable 4.3 release.
