### ISSUE TITLE
How to download list of users from a textfile?

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#545]
I just did "instaloader file.txt" and it didn't work. Is there some way i'm supposed to do this?

**Comment by Coloradohusky** [comment]
Do "instaloader +file.txt", however that doesn't really work well for me, so I made a batch script if you're on Windows:

```
@echo off & setlocal EnableDelayedExpansion
<cd to wherever the file is located>
FOR /F "tokens=*" %%i IN (<file with users in it>) DO (
		instaloader --login=<your username> --stories --highlights -F --no-metadata-json %%i
		call:rand 30 100
		timeout /T !RAND_NUM!
	)
goto:EOF
:rand
SET /A RAND_NUM=%RANDOM% * (%2 - %1 + 1) / 32768 + %1
goto:EOF
```

The delays are so that Instagram doesn't temporarily disallow you from downloading, as happens when downloading a lot in a short period of time, you can change or remove the delay if you want to, and the stuff in <> brackets you need to customize to fit your needs. Ask if you have any questions!
