### ISSUE TITLE
Download HD Profile Photo

### ISSUE THREAD

**Issue by harshamv** [instaloader/instaloader#546]
Is there a way i can only download all the usernames profile photo in HD?

**Comment by Thammus** [comment]
If [logged in](https://instaloader.github.io/cli-options.html#login-download-private-profiles), profile pics get downloaded in the best resolution available. The flag [`--no-posts`](https://instaloader.github.io/cli-options.html#cmdoption-no-posts) prevents downloading posts, so that only the profile pic is downloaded.
