### ISSUE TITLE
How to download profile from a user ID (not the username)

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#547]
i have a list of user ID's I would like downloaded. How would I go about downloading that? Is there a way to modify the program's config file (where that is?) and input the list of IDs in there then perform an 'update' so it downloads everyone's profile?

**Comment by Jeffade1** [comment]
That's exactly what I need too. Very practical.

**Comment by Thammus** [comment]
This is a typical use case for [Instaloader as a module](https://instaloader.github.io/as-module.html). Get Profile instances with [Profile](https://instaloader.github.io/as-module.html#profiles).[from_id()](https://instaloader.github.io/as-module.html#instaloader.Profile.from_id) and download them with [download_profiles()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.download_profiles).

Alternatively, to achieve this with the Instaloader CLI, you can manually create a folder per profile, store the profile ID in a file named `id` and instruct Instaloader to download the names of these folders. The names do not necessarily have to match really existing profiles since Instaloader uses the ID to find the associated profile.
