### ISSUE TITLE
How does this work when a user id changes their username to someone else's former username?

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#554]
1. User ID 1 has the username "Bob"
2. Bot scrapes their profile
3. User ID 1 changes username to "Smith"
4. Bot scrapes the new profile "Smith"
5. User ID 2 creates a new account with the username "Bob"
6. Bot scrapes their profile

In step 4 is the previous username account renamed from Bob to Smith, or is a new folder created?

**Comment by Thammus** [comment]
The behavior of Instaloader in step 4 depends on the invocation of Instaloader. If you instruct Instaloader to download "Bob", it will automatically detect the profile name change and renames the folder `Bob` to `Smith`. Otherwise, if you instruct Instaloader to download the renamed profile "Smith" instead while the old folder `Bob` exists, you would take the possibility from Instaloader to look inside the `Bob` folder and to apply a proper renaming. If the stored ID in the folder `Bob` is associated with a profile name whose folder already exists, Instaloader will also be unable to rename it.

**Comment by sxlfhxxm** [comment]
Will it work if I only have an old nickname and don't know the new one?
