### ISSUE TITLE
How to specify timezone for --filename-pattern?

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#557]
By default {date_utc} is used, but what if I want to use a different timezone, e.g KST (UTC+9)? Is it possible?

**Comment by Thammus** [comment]
Instaloader does not support specifying different timezones for the filename pattern. Nevertheless, you can use [`{date_local}`](https://instaloader.github.io/as-module.html?highlight=date_local#instaloader.Post.date_local) to insert the post's creation date in local time. As described in [Filename Specification](https://instaloader.github.io/basic-usage.html#filename-specification) you can also use [strftime()-style formatting options](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) to further customize the date string, for example `{date_local:%Y-%m-%d_%H-%M-%S%z}` will include the UTC offset of your local time. However, the usage of local time filenames is discouraged because the filenames vary when changing the timezones which leads to problems concerning identifying equal posts by filename as discussed in #69.
