### ISSUE TITLE
Is there a way to get all the profiles that might have blocked me?

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#616]
I was wondering if there is a way to get all the users who have blocked me on Instagram. There are apps that claim to do so, so obviously there is a way and also some of the log outputs of Instaloader also hint that. But is there any specific way to do just this?

**Comment by aandergr** [comment]
I think it is very unlikely that this is possible, since blocking is a privacy feature. I doubt that Instagram exposes this information in a structured manner.

**Comment by roboshim** [comment]
I can image only how you can check, if some account blocks you. Access the profile as not logged in, there should be everytime any content. Then log in and access the profile again. If there is 404 (profile does not exist), the profile has blocked you. But you probably never get list of all instagram accounts and if someone has blocked you, then this profile does not exist for you.

**Comment by Deleora** [comment]
Yeah but there are apps that claim that they can get the list of accounts that have blocked me.
How do they do it?
Check the description of [FollowMeter - Unfollowers Analytics for Instagram](https://play.google.com/store/apps/details?id=com.beakerapps.instameter2) app of Google Play.

**Comment by roboshim** [comment]
@Deleora I think, there is missunderstooding.
>  Track who blocked your account
I think they just list and save the users you follow. Next time, they check the list again and if they cannot access some accounts, then they know that users have blocked you.
Something similar I can see with instaloader - I download some accounts and sometimes some accounts start reporting, that I cannot see the content, because the account changed to private. The same I can see for accounts, who blocked me. But you have to somehow get the user list. And IG will not generate you all accounts. You can try to search users but this would take long time.
