### ISSUE TITLE
:saved changed?

### ISSUE THREAD

**Issue by somera** [instaloader/instaloader#665]
Why looks :saved folder now different in Windows?

left pic -> new style
right pic -> old style

![image](https://user-images.githubusercontent.com/8334250/83943473-b811e880-a7fc-11ea-972a-51bffcb3904b.png)

After I started the new pre release the new :saved folder was created. It's look bold in the explorer.

**Comment by aandergr** [comment]
The names of directories Instaloader creates get a special treatment on Windows, because several characters are illegal in Windows path names, such as the regular colon (`:`). [Version 4.4.3](https://github.com/instaloader/instaloader/releases/tag/v4.4.3) introduced a series of improvements to the path name handling on Windows via #631, one of which was the change of the colon replacement character to be more consistent with the other chosen characters.

**Comment by somera** [comment]
thx
