### ISSUE TITLE
List of who liked a post.

### ISSUE THREAD

**Issue by anseml** [instaloader/instaloader#70]
Would it be possible to modify the metadata to include a list of who liked a post in addition to the count that is provided?

**Comment by aandergr** [comment]
It might take many requests (and as such, much time) to obtain the complete list of likes. Hence, I would favor to not automatically include it in the metadata json created by `--metadata-json`, but rather with a separate mechanism, just like we do with the comments. Also, it seems that the liked-by information is only accessible when logged in.

**Comment by anseml** [comment]
A separate option would be good, I agree.  The number of requests wouldn't be equal to the number of likes would it?  As a side question is using `--metadata` instead of  `--metadata-json` different? I normally use `--metadata` myself.

**Comment by aandergr** [comment]
The method `Post.get_comments()` is probably a good starting point for an implementation of `Post.get_likes()`.

---

> The number of requests wouldn't be equal to the number of likes would it?

I think it is similar as with comments, where each request returns a "page" of up to *n* comments (with currently *n*=200). So it is roughly one request per *n* items. Nevertheless, requests are rate-controlled, meaning that we are only allowed to do a certain number of requests within a certain time. Instaloader has a fine logic to always stay within the limits (given that there is only one instance running), but the fact that there is a limit makes requests somewhat valuable regarding total download time.

---

> As a side question is using `--metadata` instead of `--metadata-json` different?

It's completely the same. All flags starting with `--` can be abbreviated as long as its unambiguous. So you may also use `--only` instead of `--only-if`, `--geo` instead of `--geotags`, `--sess` instead of `--sessionfile`, etc.

**Comment by anseml** [comment]
Is this something you would possibly add in the future then?

I could attempt it but have never programmed anything interacting with instagram before, unless you have some more suggestions on how to get started on writing a get.likes method.

**Comment by aandergr** [comment]
With commit 17e443a (currenty in branch `v3.3-dev`), Instaloader's `Post` class has the method `get_likes()`, which iterates over the likes of a Post. Each like is represented by a dictionary having the keys `username`, `followed_by_viewer`, `id`, `is_verified`, `requested_by_viewer`, `followed_by_viewer`, `profile_pic_url`.

A brief example to obtain the usernames of the likers of a Post:
```python
import instaloader
L = instaloader.Instaloader()
P = instaloader.Post.from_shortcode(L, "SHORTCODE")
for like in P.get_likes():
    print(like['username'])
```

(The usage of Instaloader as a module is further described in https://instaloader.github.io/as-module.html)
