### ISSUE TITLE
Download Stories

### ISSUE THREAD

**Issue by alu45** [instaloader/instaloader#701]
Hi, this is a very stupid question but please understand I’m very new to coding. I want to download all the stories of a user with a public profile. I use Jupyter Notebooks via Anaconda Navigator.
I read the instructions and this is what I typed: 

```
! pip install instaloader
! pip install --upgrade instaloader
import instaloader
```

and then I don’t know what to do. I tried all the codes I found here but I always get “invalid syntax”. Could you please tell me exactly what I’m supposed to write? Thank you

**Comment by Deleora** [comment]
You want to script this or you simply want to use it via terminal?

**Comment by alu45** [comment]
@Deleora Actually, as I read your comment, I understood my mistake. I used JupyterLab > Terminal and it worked. 
`instaloader --login=myusername --password=mypassword --stories-only theirusername`
However, is there a way to get the old stories too? Or I can download only the current ones?

**Comment by Deleora** [comment]
Instead of giving `--password=YOUR-PASSWORD`, I would suggest to remove this part and hit ENTER. Now you will be asked to enter the password if the session file is not found. This way you won't reveal your password to spying eyes 👀. 

And NO. If you are talking about downloading old stories of some other PROFILE, it's not possible because you don't have access to them in any way. 
So it's not possible.

**Comment by alu45** [comment]
I see, thank you so much!
