### ISSUE TITLE
Being redirected to login page

### ISSUE THREAD

**Issue by thomasthomas11235** [instaloader/instaloader#726]
Hello, I've been using this tool for a long time. But I hadn't used it for a few months until today, and now when I try and scrape images from a hashtag, I am being imediately redirected to a login page. Has something changed at Instagram recently to cause this? And is there a work around? I operate behind proxies, and I used to rotate them as soon as I was throttled by Instagram, but this login request seems to be happening right away.

Cheers!

**Comment by Showmaster3000** [comment]
Difficult to answer. You didn't give enough information, most important the command you used and the output it generates. Hope you updated to the latest version.

**Comment by Jablinski-hub** [comment]
![Error](https://user-images.githubusercontent.com/68208751/87302067-0fba1700-c554-11ea-94d8-52ecf3aaf2a4.PNG)

**Comment by Showmaster3000** [comment]
what about the rest?
- instaloader version
- command line

**Comment by Jablinski-hub** [comment]
This is the terminal transcript from when ive been trying stuff. Just wanted to make sure there isnt anything im doing that is obviously not right so i can learn what not to do next time?

I've seen that i need to enter password and username for it to work again, do i do that in my code editor (im using Visual studio code).

Thanks in advance anyone who can quickly look over this!
<3

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader
test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Inst
aloader test/Jablinski_Scraper.py", line 1
$pip3 install instaloader
^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader
test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py", line 1
instaloader [--login jonathan_cervantes92]
^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py", line 1
instaloader [--login jonathan_cervantes92]
^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>
C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>pip3 install --upgrade instaloader
Requirement already up-to-date: instaloader in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (4.4.4)
Requirement already satisfied, skipping upgrade: requests>=2.4 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from instaloader) (2.24.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (1.25.9)

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>instaloader 6amfeeling

HTTP redirect from https://www.instagram.com/6amfeeling/ to https://www.instagram.com/accounts/login/?next=/6amfeeling/
JSON Query to 6amfeeling/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 664 seconds, at 22:42.
GraphQL requests:
other
last 10 minutes: 1 requests
last 11 minutes: 1 requests
last 15 minutes: 1 requests
last 20 minutes: 1 requests
last 30 minutes: 1 requests
last 60 minutes: 1 requests

**Comment by Jablinski-hub** [comment]
> what about the rest?
> 
> * instaloader version
> * command line

![versions](https://user-images.githubusercontent.com/68208751/87313235-ef468880-c564-11ea-8f48-f603e02c5140.PNG)

**Comment by Showmaster3000** [comment]
I don't really understand your output, seems to be mixed from different sources.
you cannot call `` pip3`` inside a python script. this is a command line/terminal command.

Your updated post says version 4.4.4 which is ok at the moment.

It looks like that your ip address is blocked by instagram. that happens if you are too rough and get too much error 429.
I just entered your command `` instaloader 6amfeeling`` here and it immediately begins downloading the profile.

**Comment by Jablinski-hub** [comment]
Thanks im just trying to figure it all out, i am using a VPN, is there a way instagram can block them all? Ive tried America/AUS etc. Is there a chance that ive installed it incorrectly or running two versions of instaloader at the same time? Thanks for replying
