### ISSUE TITLE
Who prevent that?

### ISSUE THREAD

**Issue by MrJmpl3** [instaloader/instaloader#744]
In console , I had the response "Could not find "window._sharedData" in html response. [retrying; skip with ^C]", who prevent that?

**Comment by Deleora** [comment]
Plz share the command you executed along with the full log (ofcourse hiding your personal data)

**Comment by MrJmpl3** [comment]
```
instaloader profile [hidden] --no-captions --no-video-thumbnails --max-connection-attempts=100 --request-timeout=300 --highlights --igtv --stories --login [hidden] --password=[hidden]
Loaded session from C:\Users\JOSE MANUEL\AppData\Local\Instaloader\session-[hidden].
Logged in as [hidden].
JSON Query to profile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
```

**Comment by MrJmpl3** [comment]
```
instaloader profile [hidden] --no-captions --no-video-thumbnails --max-connection-attempts=100 --request-timeout=300 --highlights --igtv --stories --login [hidden] --password=[hidden]
Loaded session from C:\Users\[hidden]\AppData\Local\Instaloader\session-[hidden].
Logged in as [hidden].
JSON Query to profile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
```

**Comment by Deleora** [comment]
The problem in your command is that you are trying to access a PROFILE with username 'profile'. I've highlighted the error in your command below:
> instaloader **profile** [hidden] --no-captions --no-video-thumbnails --max-connection-attempts=100 --request-timeout=300 --highlights --igtv --stories --login [hidden] --password=[hidden]

The `profile` is not required, Instaloader automatically figures that out for you. That's why you got this error:
> JSON Query to **profile**/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

The correct command should be:
`instaloader [hidden] --no-captions --no-video-thumbnails --max-connection-attempts=100 --request-timeout=300 --highlights --igtv --stories --login [hidden] --password=[hidden]`

To make it more understandable:
`instaloader TARGET_PROFILE --no-captions --no-video-thumbnails --max-connection-attempts=100 --request-timeout=300 --highlights --igtv --stories --login YOUR_USERNAME --password=YOUR_PASSWORD`
