### ISSUE TITLE
Folder naming with text only?

### ISSUE THREAD

**Issue by psonnosp** [instaloader/instaloader#758]
Is it possible to make the folders that are created when downloading highlights to be text only and filter possible emojis?

I've looked at the documentation but this cmd stuff is a bit new and still kind of a jungle to me 😄 

I can't make Windows handle them properly when I try to "batch things up" so would be gr8 to be without them.

**Comment by Thammus** [comment]
There is no such feature to filter out emojis from highlight folder names. Besides, simply deleting them would not work because some highlight titles do only consist of emojis. However, as far as I know, Windows should be able to handle them in some way. Maybe consider using [PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview) instead of batch files.

**Comment by psonnosp** [comment]
Ah, didn't think of that occasion when there's only emojis since it's not relevant in my case but I see that it would cause a problem.
I've tried changing charset and stuff but it just wont handle them but I'll check if it's any difference in powershell.
