### ISSUE TITLE
Fatal error: Login: Checkpoint required 

### ISSUE THREAD

**Issue by AlkaffAhamed** [instaloader/instaloader#798]
**Describe the bug**
When I try to download posts by logging in, I get the Checkpoint Error with a URL. When I open the URL in the browser, I am asked to verify the "suspicious login attempt". After that, Instagram logs in the browser but the program doesn't continue. 
When I try to login again in the same terminal, same instance of the program running, the same error comes again asking me to verify in the browser. Same cycle repeats. 

**To Reproduce**
Not sure how to reproduce this error as it started coming suddenly. Previously the program worked fine. 

**Expected behavior**
I am only guessing that the program should communicate with Instagram to login successfully. Somehow, the output of successfully verifying the account should be taken back by the program. Then another login attempt should be done automatically instead of manually trying again and coming to the same error again and again. 

**Error messages and tracebacks**
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/7433087375/Y51gc9RvNU/ - follow the instructions, then retry.

**Instaloader version**
4.4.3

**Comment by clublek** [comment]
This helped for me in this scenario: https://instaloader.github.io/troubleshooting.html#login-error

**Comment by AlkaffAhamed** [comment]
I tried installing the Firefox browser and ran the script. In the App Data also, the session file was there as expected. When I tried to login, I got this error: 

Session file does not exist yet - Logging in.
Enter Instagram password for [USER]:
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/.../.../ - follow the instructions, then retry.

I tried again by copy and paste the session file into the working directory, fed that session file as a parameter (--sessionfile SESSIONFILE). This time I got this error: 

Loaded session from session-[USER].
Fatal error: 400 Bad Request

**Comment by AlkaffAhamed** [comment]
Ok, trying the 2nd time it worked. 

I deleted all cookies and login from Firefox. When I copy paste the session file generated by the script, it didn't work. It only worked when I pass the session file as part of the arguments. 

Thanks for the directions! @clublek

**Comment by loverboyXD** [comment]
Hello!
I am also having lots of trouble related to this🥲 issue
I am using instaloader on my telegram bot and i am not able to login 

My Following codes to generate Instaloader session file can be Found here: https://spaceb.in/api/v1/documents/ZAdnrXPR/raw

Please help me what can i do to solve this issue?

**Comment by Grufftactician2033** [comment]
Can I see your code? (Delete the login info) I've been trying to log in for 3 days already.

**Comment by adityaarya99** [comment]
Hi, 
I am facing a similar issue here in 2024. Does anybody have any solution?

`import instaloader
loader = instaloader.Instaloader()
loader.login("user_name", "password@2025") `

**Comment by PedroAzuos** [comment]
Same issue. Anyone figure this out?

**Comment by jsspen** [comment]
@adityaarya99 @PedroAzuos 

I've been using Instaloader as a Python module in a script that runs as a cronjob and I just ran into this.  Here's what I did:

(Some aspects are probably not necessary but I included them anyway prefaced with a *)

1. Logged into IG account in Firefox, completed auth challenge when prompted. *Used a fresh install of Firefox and I left the window open while I did the rest.
2. From terminal `wget https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py` to grab the script from the troubleshooting page [here](https://instaloader.github.io/troubleshooting.html#login-error). *I put it in the same directory as my script.
3. Run the script. I used `/usr/bin/python3 /path/to/your/615_import_firefox_session.py` If it works you should get: `Using cookies from /home/xxxx/.mozilla/firefox/xxxx.default-esr/cookies.sqlite.`, `Imported session cookie for {IG username}.` and `Saved session to /home/xxxx/.config/instaloader/session-{IG username}.`
4. The troubleshooting page says to then run instaloader with `instaloader -l USERNAME` BUT since I'm not using instaloader on the command line, I instead had to edit my script.
5. Previously my script looked something like this:
```
import instaloader
import os
from datetime import datetime

# Configuration
USERNAME = 'XXXXX'  # Instagram username to monitor
DOWNLOAD_DIR = '/Instagram'
LAST_RUN_FILE = os.path.join(DOWNLOAD_DIR, 'last_run.txt')
PASS = 'XXXXXXX'
USER = 'XXXXXXX'


# Initialize Instaloader instance
L = instaloader.Instaloader(dirname_pattern=DOWNLOAD_DIR, download_videos=True, post_metadata_txt_pattern='')
L.login(USER, PASS)
```
Now it looks like this:
```
import instaloader
import os
from datetime import datetime

# Configuration
USERNAME = 'XXXXX'  # Instagram username to monitor
DOWNLOAD_DIR = '/Instagram'
LAST_RUN_FILE = os.path.join(DOWNLOAD_DIR, 'last_run.txt')


# Initialize Instaloader instance
L = instaloader.Instaloader(dirname_pattern=DOWNLOAD_DIR, download_videos=True, post_metadata_txt_pattern='')
L.load_session_from_file('{IG Username}')
```
I gave it a run and everything was back to working flawlessly.
