### ISSUE TITLE
":tagged" folder name (colon issue)

### ISSUE THREAD

**Issue by uvx0ol** [instaloader/instaloader#799]
Hello, 

As megacmd does not support colon in sync mode, that would be great if the ":tagged" folder could be named simply "tagged". Or anything else but without colon. Megacmd creates %3a instead of colon and that is very irritating, as this folder cannot be synced correctly and then it is downloaded as %3a to the local storage.

**Comment by aandergr** [comment]
Have you tried the following invocation?

```
instaloader --tagged --no-posts --dirname-pattern=tagged PROFILE
```

**Comment by lx30011** [comment]
> Have you tried the following invocation?
> 
> ```
> instaloader --tagged --no-posts --dirname-pattern=tagged PROFILE
> ```

That doesn't make sense.

What I've been doing as a workaround is renaming the folders that include a colon for the duration that instaloader runs.
```sh
mv <user>/__tagged <user>/:tagged
instaloader <...>
mv <user>/:tagged <user>/__tagged
```

I presume a colon is an illegal character in a highlight name so it was chosen to prevent collisions. Still it's isn't good design because it's also an illegal character on Windows. This at least breaks sharing via SMB and causes problems with cloud storage providers. I've chosen __tagged because it's unlikely you encouter a highlight named that way so it shouldn't collide. Instaloader should switch to a proper directory structure to avoid collisions.

hightlights/
tagged/
posts/ (if you like, posts can also just remain in root directory)
...and so on
