### ISSUE TITLE
Endpoint Filter

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#80]
Is it possible to know which one is the filter added to the picture? 
I don't find this information in the metadata-json query.

Best
P

**Comment by pvita** [comment]
Hi there,
as you can see [here](https://www.instagram.com/developer/endpoints/tags/#get_tags_media_recent
), "Filter" is one of the metadata of the pictures.
Probably the only one missing comparing to your "medatada-json"
Best
P

**Comment by aandergr** [comment]
Hi,

> as you can see [here](https://www.instagram.com/developer/endpoints/tags/#get_tags_media_recent), "Filter" is one of the metadata of the pictures.

That's the documentation of the official Instagram API, which we do not use because it requires an access token which we cannot provide. Instaloader exports all received metadata in the JSON files along with each post, and there is no information about the filters that have been used.

Best regards
Alex
