### ISSUE TITLE
Instaloader-reader

### ISSUE THREAD

**Issue by prohtex** [instaloader/instaloader#808]
Has anyone considered writing an instaloader reader? I'm thinking about a lightweight PHP script that parses a directory of stored profiles and generates browsable layouts.

**Comment by Fogest** [comment]
I actually was just wondering the exact same thing. I had a dog breeder that had an instagram account for the litter of puppies. They have since removed the account a few months after but I have it backed up. The other owners of the puppies have no such backup and wanted to see the photos. So for now I just uploaded all the photos on Google Photos but it lacks the captions to go with them which can be useful. 

I have considered making a webpage but don't know if I have the time/motivation right now.

**Comment by Fogest** [comment]
Bump

**Comment by cloudrac3r** [comment]
You might be looking for Bibliogram. Bibliogram intentionally does not save data to disk to protect the privacy of users, but I don't think it would be difficult to modify it to save photos and p reserve deleted accounts.

https://sr.ht/~cadence/bibliogram/

**Comment by forivall** [comment]
I'm probably going to build a simple node app to do this, with the capability to read off of google drive, since that's where i'm storing my archives.
