### ISSUE TITLE
Running --stories hangs indefinitely

### ISSUE THREAD

**Issue by clydachpugsley** [instaloader/instaloader#810]
Instaloader halts mid rip for stories and hangs indefinably, mine was hung 8 days without knowing. Running again repeats behaviour

**To Reproduce**
Use --stories on any profile(s) with and without session file

**Expected behavior**
Stories should be ripped to completion

**Error messages and tracebacks**
No messages, instaloader simply halts at some point during the rip and dosent continue, and it is not just the rate limiter,nothing is output from instaloader

**Instaloader version**
4.5.3

**Comment by aandergr** [comment]
This may be due to connection problems, leading requests to remain unresponded. Per default, Instaloader waits indefinitely for a response from the server. Instaloader has the option [`--request-timeout N`](https://instaloader.github.io/cli-options.html#cmdoption-request-timeout) to change this behavior. 

Is this fixed by passing something like `--request-timeout 30` to Instaloader?

(just for reference: `--request-timeout` has been suggested and implemented in #330, #422)

**Comment by clydachpugsley** [comment]
Seems to be working adding the --request-timeout, however, I've used it without that for atleast a year and I'm not having any issues loading instagram via the website or app. I would like to see if it is something else causing it instead of applying as band-aid to it when it could be something more serious behind the scenes.
