### ISSUE TITLE
Has the story been viewed?

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#811]
Is it possible to know if the stories of TARGET has been viewed already, form the JSON file which Instaloader downloads?
If yes, how?

**Comment by aandergr** [comment]
Yes, the Story JSON contains a field `seen`, which is evaluated by the properties [`last_seen_local` and `last_seen_utc`](https://instaloader.github.io/module/structures.html#instaloader.Story.last_seen_local). They return `None` if the story has not been viewed, and a `datetime` otherwise. However, Instaloader does not save the Story JSONs, the JSON files saved when downloading a Story correspond to _StoryItems_.

**Comment by Deleora** [comment]
Alright. But, is it possible to download Story JSON using instaloader? If yes, could you please guide me on how to achieve that?

**Comment by Deleora** [comment]
> Alright. But, is it possible to download Story JSON using instaloader? If yes, could you please guide me on how to achieve that?

I tried this code but it's not printing last seen time of that story.

```
import instaloader

your_username = '...'
target_profile = 'forbes'

L = instaloader.Instaloader()
L.load_session_from_file(your_username)

for story in L.get_stories():
    if story.owner_username == target_profile:
        print(story.last_seen_utc)
        print(story.last_seen_local)  #IST (+5:30)
```

o/p:
```
2020-09-29 01:51:26 
2020-09-29 07:21:26 
```
however, the story was actually viewed at 19:45 IST (approx). So now I don't know what are these 2 timestamps in output. Any help please?

**Comment by e5150** [comment]
In the raw json I get from instagram, "seen" (if set) always matches the timestamp of the storyitem itself. So it won't tell you when, only if, an item has been seen.
