### ISSUE TITLE
Add option to turn off high resolution images

### ISSUE THREAD

**Issue by psylenced** [instaloader/instaloader#820]
**Provide us a use case of the feature**

Currently, I believe that the download high resolution image uses an API request.

https://github.com/instaloader/instaloader/pull/662

**Describe the solution you'd like**

I would like an option to disable this behaviour while still logged in (ie. ```--no-high-resolution```)

The reason why this is needed, is that when downloading large batches of images, the 429 error appears more regularly.

I'm happy to be proven wrong, but by including this option, there will be fewer API hits, allowing more images to be downloaded without hitting 429 limits.

**Comment by aandergr** [comment]
Yes, this would be good to have. Getting the URL of the higher resolution image indeed requires an extra request to the i.instagram.com endpoint.

**Comment by psylenced** [comment]
This seems to be quite an important issue at the moment.

Most of the 429 issues and checkpoints that people have been getting recently have been to this change. Far more API hits which are causing their systems to get triggered.

**Comment by aandergr** [comment]
@psylenced no, that is not how it works.

The here-suggested feature would merely allow to download a target's media faster at the cost of lower quality. Instaloader needs to do an additional query for obtaining the URL of the high-quality version. Since only a certain number of queries is allowed within a certain time, every additional query causes to slow down the overall download process.

That query's allowed rates seem perfectly modeled within Instaloader's rate controller, both according to my own experiments and to what has lately been reported in the issues.

Further, it is illogical to avoid a certain query to reduce API hits. Avoiding a certain query will not reduce the overall query rate.

However, if, for whatever reason, this is important to you, feel free to implement it. As already stated in my last comment, this would be good to have and we would of course accept pull requests for it.

**Comment by psylenced** [comment]
> The here-suggested feature would merely allow to download a target's media faster at the cost of lower quality. Instaloader needs to do an additional query for obtaining the URL of the high-quality version. 

Just so I can understand.

When querying an account, you get back (from a single API-hit) a list of media eg. 20 items.

This then downloads each of those at "low quality". Meaning 1 API hit gives 20 downloads.

With "high quality" turned on, you have your initial API hit, plus 20 further hits to get 20 media items.

So high quality is n+1 (21) to get 20 downloads. Meaning that the API hits are 20x larger for having the high quality feature enabled.

If quick update averages 3 lists over 100 accounts, the comparison is:

300 api hits (low quality) vs 6,300 api hits for high quality.

This clearly would increase the number of 429s for accounts? Or is my understanding wrong?

**Comment by aandergr** [comment]
Sorry for obviously not having it emphasized enough in my comment earlier this day: This would be a nice-to-have feature, and we would welcome a pull request for it. Sticking to the lower-quality versions of the media will speed up the download process, i.e. the message generated by our rate controller *Too many queries in the last time, need to wait ...* (which is not a 429 error!) will appear less.
