### ISSUE TITLE
How to use --resume-prefix command?

### ISSUE THREAD

**Issue by angentanewbe** [instaloader/instaloader#825]
How to use --resume-prefix command?

I am download a large number of profiles and once the download is interrupted it starts from beginning and 429 error occurs.

Please explain --resume-prefix command in detail. Also it is possible to use multiple accounts to download posts of profiles to avoid 429 error.

**Comment by aandergr** [comment]
> Please explain --resume-prefix command in detail. 

Sure, already did that here: https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix

**Comment by DennisPing** [comment]
@angentanewbe It's easy. Add --resume-prefix <string> to your command. For example:

`instaloader (your other command options) --resume-prefix resume taylorswift`

You do not need a unique <string> for each account since each account folder has its own resume json file. It's best to use this option every time since it's very useful if your connection breaks.

**Comment by angentanewbe** [comment]
@DennisPing can you explain it more. Like how to add it in config file so that it resumes from where last time the connection broke.

**Comment by DennisPing** [comment]
@angentanewbe You're thinking too hard. There's no extra config to do. I can literally copy/paste this command and run it:

`instaloader --no-metadata-json --no-captions --no-video-thumbnails --resume-prefix resume --login=[username] taylorswift donaldtrump lebronjames irrfankhan shakira`

**Comment by angentanewbe** [comment]
@DennisPing Alright. Got it. Thanks ☺️
