### ISSUE TITLE
Manual override of where to restart download of posts

### ISSUE THREAD

**Issue by UweLau** [instaloader/instaloader#855]
**Provide us a use case of the feature**

Due to blocking on Instagrams side it is now nearly impossible to get posts larger than 500-1000 posts without hitting some error.

What I want is a manual override of where to (re-)start the downloads or the checks.

Example:
I download with one account like this:

`--stories --highlights --igtv --login=xxxx --password=xxxx someone`

Lets assume the highlights are downloaded normally (which is mostly the case) it then starts to download the posts, lets say 1/873. After a while you hit the API limit and eventually (lets say at 273/873) you get a 400 Bad Gateway error which means the login account is burned in most cases.

When I restart the whole thing again with above parameters with a new login account (could also be true with the same account?) 
it checks the highlights rather fast and then again tries to downloads or better checks for the jsons.

What I now want is to specify a post where it restarts the download, in my example it would be likely somewhere at 265 to be on the safe side.

There is the iterator thing in the directory which should be used in that case (in my opinion) but I only saw it once it kicked in. Maybe it is because it is user-based? I really don't know.

Without this feature it is not possible at the moment to get a large set of posts when logged in. But even if the login problems are solved it would be nice to start or restart on a specific post.

I understand I can get all posts if I don't login but then I won't get the larger resolutions.

**Comment by aandergr** [comment]
Do you have an idea for how to start the loop at an arbitrary post instead of the first?

> There is the iterator thing in the directory which should be used in that case (in my opinion) but I only saw it once it kicked in. Maybe it is because it is user-based? I really don't know.

Yes, only resume files with matching login names are considered.

**Comment by UweLau** [comment]
I am afraid I have no idea how to start a loop at a specific post because I do not know how instaloader does the download. I think you have a way better understanding in this.
How does the iterator work? Can it be modified into using it for other users? 
Another idea: When I restart the download again with another account I end up in API problems again so I assume instaloader checks again with the help of the API if a JSON exists. Now my idea is to first check if the json exists and only then try to download the file.
Or how about only download a file when there is a higher-quality image available. So it would be possible to download the files without login and then only download the ones that have higher-quality images?
I am very sorry I can not be of help here,  I really do not understand the whole download process :-(

**Comment by aandergr** [comment]
> I am afraid I have no idea how to start a loop at a specific post because I do not know how instaloader does the download. I think you have a way better understanding in this.

As far as I know, it is not possible to *start* the iteration at an arbitrary point (in contrast to *resuming* at an arbitrary point).

> How does the iterator work? Can it be modified into using it for other users?

We decided to not allow resuming download loops between accounts because the information needed for resuming a download may be private in the sense of being associated to a certain account. This becomes clear when thinking about looping through a private profile that is followed by one account but not by another one. Sharing resume information between these accounts would very likely lead to a 'suspicious activity' ban. With Instaloader being open source, it is of course possible to remove the same-account-check in Instaloader's [nodeiterator.py](https://github.com/instaloader/instaloader/blob/master/instaloader/nodeiterator.py).

> Or how about only download a file when there is a higher-quality image available. So it would be possible to download the files without login and then only download the ones that have higher-quality images?

To find out which posts are available in a higher-quality, one would need to iterate over all posts while being logged-in.
