### ISSUE TITLE
Only get Metadata

### ISSUE THREAD

**Issue by boerninator** [instaloader/instaloader#862]
Is ist somehow possible to only download the metadata, without the pictures? For example a whole profile and only the metadata for each post?

**Comment by flipso** [comment]
Hey @boerninator 

Sure thats easy use these parameters:
 --no-pictures --no-videos --no-profile-pic --no-captions --metadata-json

If you dont want compression than add:
--no-compress-json 

Cheers

**Comment by boerninator** [comment]
Hey @flipso 

thanks for the answer! Do you also know how I could call the instaloader as an object in my own python script? New into programming and could not figure it out from going through the .py files on GitHub...

**Comment by flipso** [comment]
Hey @boerninator,

1. Please close the issue because we solved the problem. 
2. Instaloader have many Commandline options. Read the docs carefully before you start coding:
https://instaloader.github.io/cli-options.html
3. Of course you can create your own instance aka object of instaloader in your code.

here's code for creating a instaloader instance:

    import instaloader
    L = instaloader.Instaloader()

you should consolidate the docs first: https://instaloader.github.io/codesnippets.html could be a entry point for your purpose.  But not try to use "likes-of-a-profile-ghost-followers" section because Insta restricted. I have mentioned these in #860 

Feel free to ask for help via email if you have problems. 

Cheers mate
