### ISSUE TITLE
Are there "429 - Too Many Requests" limits for authenticated users?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [instaloader/instaloader#864]
Hi!

I have a question regarding the `429 - Too Many Requests` error. The documentation at https://instaloader.github.io/troubleshooting.html#too-many-requests states the following:

> There have been observations that services, that in their nature offer promiscuous IP addresses, such as cloud, VPN and public proxy services, might be subject to significantly stricter limits for anonymous access. However, logged-in accesses (see --login) do not seem to be affected.

Since I don't make backups with Instaloader heavily just trying to archive one relatively big profile as an _authenticated_ user, I run it once a day in general. More times rarely because of the 429. However, there are days that Instaloader fails just after a few requests (e.g. 20 two days ago, but ~90 yesterday). I'm wondering, even the question sounds silly: how should I interpret the following data:

```
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   #<id-1>#########################:    1    1    1    1    1    1
                              other:    1    1    1    1    1    1
 *                           iphone:   18   18   18   18   18   18
   #<id-2>#########################:   18   18   18   18   18   18
   #<id-3>#########################:   18   18   18   18   18   18
   #<id-4>#########################:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
```

? I definitely run single instance only, don't use any Instagram apps (neither official, nor unofficial except Instaloader), and I don't even own an Apple device. Should I configure Instaloader somehow, or should I review other aspects?

```
$ instaloader --version
4.5.3
```

Thanks.

**Comment by lyubomyr-shaydariv** [comment]
Looks pretty much like #834.

**Comment by Thammus** [comment]
The message that is printed when facing a 429 lists all requests that occurred in the last time. The left side of the table specifies the type of queries that were made. The hashes for example are identifiers which are used to define the endpoints on Instagram's side. They can be interpreted as the source from which the data gets fetched. By the way, these hashes are hardcoded in Instaloader's source code and do not contain any information of the user and thus do not need to be obfuscated. The type `iphone` simply means that a query to an iphone endpoint is made in order to fetch some data. `other` refers to normal HTTPS requests that are neither using GraphQL endpoints nor the iphone API. 
The asterisk on the left side marks the type of query which got responded with a 429. 

> However, there are days that Instaloader fails just after a few requests

An important thing to mention here is that such a 429 message does not mean that the entire download process of Instaloader failed. It just means that the Instagram servers responded with a status code of 429 that indicates too many requests. After waiting several minutes, Instaloader should be able to automatically continue its processing without problems.

This being said, getting a 429 response is something that should not happen. Instaloader's [rate controlling logic](https://instaloader.github.io/module/instaloadercontext.html#ratecontroller) intends to prevent these unusual responses by keeping track of the requests being sent and deferring subsequent ones.

**Comment by lyubomyr-shaydariv** [comment]
@Thammus that's a very appreciated answer, thank you!

> An important thing to mention here is that such a 429 message does not mean that the entire download process of Instaloader failed. It just means that the Instagram servers responded with a status code of 429 that indicates too many requests. After waiting several minutes, Instaloader should be able to automatically continue its processing without problems.

> This being said, getting a 429 response is something that should not happen.

Hm, that diverges from my experience. If I remember correct, downloading a profile under an authenticated user allows to backup images with higher resolution, however I end up with 429 severyday I use Instaloader (and usually I just give up until the next day since even one-two requests fail with 429 over and over the same day -- it looks like Instagram merely keeps banning me for a whole day). And vice versa, if I'm fine to backup lower resolution images being an unathenticated user, I seem to have never ran into 429.

I'm also wondering: is there any way of working around that? E,g, configuring the request rate (say, let it be 2-3 times slower to get rid of 429s (if it ever makes sense, of course) + I don't write in Python but adding some sleeps is definitely not a rocket science to me), or resuming a failed download session so that the next 429 shows up after a big bunch of requests (e.g., AFAIU, `instaloader.RateController` is a way to work around a completely black box on the Instagram side)?

**Comment by ready2r** [comment]
So is this repo dead in the water?

I get 25-30 images in before i get the 429 error.  Even waiting the 10 mins for it to start up again.. it immediately triggers the error again.. over and over.

**Comment by lyubomyr-shaydariv** [comment]
@ready2r 
If I'm getting what @Thammus is saying, then Instaloader tries doing its best to backup profiles. It seems to really depend on a particular session I guess and the endpoints Instaloader fetches data from: for example, my today backup iteration ended up in two phases with ~50 posts at the first iteration, and suddenly ~150 at the last iteration (usually, last iterations fetch much less before Instaloader gives up). However, what I'm still wondering is that if it's possible to overcome the limits by mimicking the web browser (I hardly believe walking 20-30 posts in the browsers will result in 429) or whatever else. In any case, Instaloader is a great tool for me. <3

**Comment by ERasnier** [comment]
I can't get anything from my follower/following script but just an instant 429 even after deleting the sessions file. However I can use the cli version just fine but this bug really needs to be fixed!

**Comment by Thammus** [comment]
The observation that using Instaloader without login/authentication leads to less frequent 429 problems can be explained with the additional queries to the iphone API that are made on logged in sessions to fetch higher quality pictures.
This coincides with the information that comes out of your 429 error output, which already shows the iphone query as the one causing problems.
So, one possibility to alleviate the 429 problems would be to make these higher quality iphone requests optional like suggested in #820. Also, using them is not mimicking the browsers behavior, since these endpoints are not used in Instagram's Web Interface.

**Comment by lyubomyr-shaydariv** [comment]
@Thammus 
got it, sounds like there is not much to do with it anyway as I'd still like to backup higher quality images for archiving purposes. Let's see. Thank you!
