### ISSUE TITLE
Too many queries in the last time, without even querying 100 posts

### ISSUE THREAD

**Issue by Lerring** [instaloader/instaloader#879]
Hi, I'm loading instaloader like so:

```
from instaloader import Instaloader, Hashtag
import json
import datetime
import time
from collections import deque

L = Instaloader(save_metadata=False, compress_json=False, download_video_thumbnails=False,
download_comments=False, download_videos=False, download_geotags=True,download_pictures=False)
L.post_metadata_txt_pattern = ""
L.download_geotags = False
L.save_metadata = False
L.save_metadata_json = False
L.download_comments = False

#L.load_session_from_file('session')
L.login("XXXXX", "XXXXX")
hashtags = Hashtag.from_name(L.context, "georgefloyd")

SINCE = datetime.datetime(2020, 5, 25)
UNTIL = datetime.datetime(2020, 6, 7)

def isApril(ringBuffer):
    if len(ringBuffer) == 0:
        return
    months = [ post.date_utc.month for post in ringBuffer]
    return max(set(months), key = months.count) == 4

def getPostsByDateRange(posts, startDate, endDate):
    postsByDateRange=[]
    ringBuffer=deque(maxlen=100)
    count=0
    updated=False
    for post in posts:
        #if date within selected range, append
        if (startDate < post.date_utc and post.date_utc < endDate):
            ringBuffer.append(post)
            postsByDateRange.append(post)
            if (len(postsByDateRange) % 100 == 0):
                print(len(postsByDateRange))
            updated=True
        #only checks ringbuffer every 5 posts, to save waiting ages
        if count <= 5:
            count=count+1
            continue
        #dont run it the state of the ringBuffer is the same
        if updated == True and isApril(ringBuffer):
            return postsByDateRange
        updated=False
        count=0

start = time.time()
postsByDateRange=getPostsByDateRange(hashtags.get_posts(), SINCE, UNTIL)
end = time.time()
print([post.shortcode for post in postsByDateRange])
print("Time Taken: ")
print(end - start)
print("Posts Found: ")
print(len(postsByDateRange))
```

I'm querying a popular hashtag (blm) but reach the following error before I've even collected 100 posts.

> Too many queries in the last time. Need to wait 421 seconds, until 22:12.

If I'm wanting to look for dates within a certain range, how is it possible to do so without spending years dealing with too many queries, can instaloader not handle large hashtags?

Kind regards.

**Comment by mauro-cb** [comment]
hello, i'm with the same problem here, but with profile's query.
the collect is giving "too many requests" too soon, and is giving some message about redirect as well:
"HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/"

**Comment by marty90** [comment]
yes, I have this problem starting from 2 day ago. They might have changed something in the rate limit :(

**Comment by ThomasAn73** [comment]
First time trying this tool and I run into the "too many requests" issue merely by running the ghostFollowers example from the Advanced Instaloader Examples page.

**Comment by kk-Chiron** [comment]
Anyone here solves this? It's definitely not account related and my proxies/VPN connection also respond with the same 429 error. 
Sadly this makes Instaloader kinda useless for me.

**Comment by basementmilan** [comment]
Same problem here, the error message appears after a very short list of downloaded media

**Comment by g4digital** [comment]
I'm facing the same problem, has anyone managed to solve it?

**Comment by Lerring** [comment]
I've been unable to resolve the problem, and as a consequence my girlfriends dissertation has had to change last minute as we needed the data to progress! 

It shouldn't be this hard to query the data, I was close to just using selenium before time ran out.

**Comment by g4digital** [comment]
![Capturar](https://user-images.githubusercontent.com/68974103/100205762-492c6700-2ee4-11eb-8d01-66464fec9fc9.PNG)

**Comment by aandergr** [comment]
Closing this question as it seems unclear what the question is actually about:
- the quoted log message is explained in the [documentation](https://instaloader.github.io/troubleshooting.html#too-many-queries-in-the-last-time), and this question does not seem to refer to that explanation,
- many off-topic comments, which further underlines the ambiguity of the question – *429 Too Many Requests* and *Too many queries in the last time* are different messages with different meanings,
- aggressive, provocative tone by this issue's author, instead of a discussion culture that actually invites to help.

@Lerring We're certainly not your free support service, we're not here to fix your problems. There are many peer-reviewed papers out there that successfully used Instaloader to obtain their data. Instaloader waits up to 11 minutes and 6 seconds – not "years" – as required per Instagram's rate limiting. If you find a way to avoid that  – "It shouldn't be this hard to query the data" – you're welcome to contribute.
