### ISSUE TITLE
Error with login via instaloader.

### ISSUE THREAD

**Issue by WaseemRakab** [instaloader/instaloader#884]
**Describe the bug**
```
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/29704744066/CRz61vM0ua/ - follow the instructions, then retry.
```

**To Reproduce**
(e.g. Instaloader command line)

**Expected behavior**
every time i try to login to download anything via instaloader. I'm having this issue, and i followed the instruction in the URL above, then after trying to log in again, the same error occurs, (like a loop).
any help appreciated.
thanks.
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.
```
4.5.3
```

**Additional context**

**Comment by dorokkkk** [comment]
I have had the same error, but no luck in resolving it...

**Comment by Showmaster3000** [comment]
Have a look at the documentation: https://instaloader.github.io/troubleshooting.html#login-error

**Comment by andreybondarb** [comment]
The same issue even after loading cookies. Next Triying to deactivate & activate my account in 24 hours, maybe this could help.

**Comment by Showmaster3000** [comment]
I never had the problem, that my account was blocked/in challenge required state after grabbing cookies from firefox. I hope you all use the latest version of instaloader. What happens if you open your profile just in this firefox session which is used for grabbing the cookies?
Next question is: are you sure, that your cookie file gets replaced with the new one?

**Comment by aandergr** [comment]
Given that these questions remain unanswered, I guess this is resolved. Please comment if the problem still persists.

**Comment by psonnosp** [comment]
@aandergr No it is still an issue, at least on the windows standalone.
I'm on the latest version and get stuck in the loop.
The link above that @Showmaster3000 posted is kind of out of my league (that's why I'm using the standalone in the first place :wink:) so can this be done manually?
I see all the values from the cookie in FF but how do I edit the session file? It's in a format I don't know how to edit corrrectly, tried just changing the values in Notepad+ but that didn't work.
