### ISSUE TITLE
Is there a way to detect existing downloaded posts by something other than filename?

### ISSUE THREAD

**Issue by aaaxx** [instaloader/instaloader#899]
Hashes, for example? Or shortcode?

I'd like to be able to rename the existing files. And even if I didn't, I still have to remember to pass the `--filename-pattern` used initially every time I update an archive.

**Comment by AplhaSlayer1964** [comment]
I would recomend making a batch script to run your command then you don't have to type the command everytime and won't have to worry about running the --filename-pattern because it will already be there. As far as I know there anren't any other built in ways to check existing you could always make a pull request with something like that implimented.
