### ISSUE TITLE
Save photo metadata as one JSON file instead of having one file per photo.

### ISSUE THREAD

**Issue by EriZain** [instaloader/instaloader#90]
I would love to have it so that instead of having one JSON file per photo, I could download all the metadata into one json file (which is essentially just a list of all the metadata for each photo). If you could point me in the right direction for where the JSON is downloaded, I'd be happy to try to contribute code to this feature. Thanks!

**Comment by aandergr** [comment]
> I would love to have it so that instead of having one JSON file per photo, I could download all the metadata into one json file (which is essentially just a list of all the metadata for each photo)

For Version 4, we have planned to rework the JSON file format and give it the purpose to reimport these JSONs to extract further metadata afterwards. However, most probably we continue to create one JSON per Post. What's the purpose of downloading all the metadata into one single file?

> If you could point me in the right direction for where the JSON is downloaded, I'd be happy to try to contribute code to this feature.

There is `Instaloader.download_post()` which with a given `Post` instance calls `Instaloader.save_metadata_json()` with `Post.json_encoder()` to convert the `Post` instance to a JSON-exportable structure, i.e. build the structure that is then saved in metadata files. The `Post` instances themselves are created (and their GraphQL JSONs retrieved from Instagram) in `Instaloader.get_*_posts()` methods, and can also be created with `Post.from_shortcode()` classmethod, which is really helpful for debugging and experimenting.

Currently we have a `v4-dev` branch were we do some code cleanups. It might be better and easier to implement it there, rather than `master`.
