### ISSUE TITLE
--fast-update breaks when user changes name and --filename-pattern includes {profile}

### ISSUE THREAD

**Issue by AplhaSlayer1964** [instaloader/instaloader#901]
**Describe the bug**
Whenever a user changes their instagram profile name all images will be redownloaded using --fast-update if the --filename-pattern includes {profile}.

**To Reproduce**
--fast-update --filename-pattern={profile}_{mediaid}

**Expected behavior**
I guess the expected behaviour would be for --filename-pattern to act like --dirname-pattern. --dirname-pattern seems change the folder name if the folder is set to {profile}

**Error messages and tracebacks**
No error messages

**Instaloader version**
`instaloader --version` output.
4.5.3

**Additional context**
Like I said in expected behavior --dirname-pattern seems change the folder name if the folder is set to {profile}

**Comment by aandergr** [comment]
Yes, `--fast-update` simply adds a check to the download iteration loop to abort if a file with the current filename already exists, and the files are not renamed after a profile name change, only the directory defined by `--dirname-pattern` is renamed.

We're open for any ideas, however, I think it is not possible to cleanly let Instaloader rename all affected files after a profile name change. This is part of the reason why we have a split `--filename-pattern` and `--dirname-pattern` instead of a single parameter to specify download paths.

**Comment by AplhaSlayer1964** [comment]
You are definitely right about it not being clean the only way I can think of doing it would require the user to have either {owner_id}, {shortcode}, or {mediaid} already in the file name and using some regex search based on a given  --filename-pattern to then check all images in the --dirname-pattern. Thank you for the response though and I have also switched to not using the {profile} in --filename-pattern. Might also be helpful to list this under a troubleshooting problem though having this happen probably isn’t too common.
