### ISSUE TITLE
Code gets stuck indefinitely 

### ISSUE THREAD

**Issue by aalshakarchi** [instaloader/instaloader#907]
https://github.com/instaloader/instaloader/blob/dcc7ab89c18a58b810ea7a519b0754abc3cabb74/instaloader/instaloadercontext.py#L322

When running for a long time, code gets stuck here indefinitely without raising an error. Suggest adding a timeout argument to the request. Testing different timeout values and can fork to fix this if helpful.

**Comment by aandergr** [comment]
Similar to #810.

This may be due to connection problems, leading requests to remain unresponded. Per default, Instaloader waits indefinitely for a response from the server. Instaloader has the option [`--request-timeout N`](https://instaloader.github.io/cli-options.html#cmdoption-request-timeout) to change this behavior.
