### ISSUE TITLE
always email for unknown access when using Instaloader

### ISSUE THREAD

**Issue by TravelTrader** [instaloader/instaloader#919]
First, I want to say that it's a great and helpful library to have a good overview of followers and followees.
But whenever I run a code with instaloader I get such an email from Instagram that a new accesspoint (Browser, Location, ..) was used. Everytime. When I run 10 codes, I get 10 emails.

I already tried to allow this access point to use my account but it didn't change anything.

Is there any solution for this?

Thank you!

**Comment by chocolatepaper** [comment]
Have you tried importing a session file from firefox cookies? 
https://instaloader.github.io/troubleshooting.html#login-error

**Comment by TravelTrader** [comment]
> Have you tried importing a session file from firefox cookies?

Thank you, @chocolatepaper. I didn't know about this cookie management.
I tried around but I always get:

```Cookie import failed: database is locked```

I am using `instaloader` under Ubuntu 18.04.
Do you have any additional help for me?

**Comment by aandergr** [comment]
Instagram sends a notification to you whenever someone logs into your account, as a security measure. Thanks to this feature, you will notice immediately if someone else uses your Instagram account and can then manually take appropriate action.

If your code logs in everytime, you will receive this notification everytime you run your code. 

Instaloader allows to persist the session cookies in a *sessionfile* to not have to login each time you're using Instaloader. It is highly recommended to use session files instead of logging in each time. Have a look at the documentation for how to load a session file in your code: https://instaloader.github.io/as-module.html 

> I tried around but I always get:
> 
> `Cookie import failed: database is locked`

You seem to use an outdated version of the firefox cookie import script.

**Comment by TravelTrader** [comment]
Thank you, @aandergr!
> You seem to use an outdated version of the firefox cookie import script.
I use the script shown in the above link (https://instaloader.github.io/troubleshooting.html#login-error). As I could read in the code it also finds the right cookie folder and file in my Ubuntu system but could not open/read it.
Hm, I will check the link but when you say that the import script should work there's maybe anything wrong in my system?

**Comment by TravelTrader** [comment]
Now I used the sample script from GitHub and not the one in the DOCs and it worked immediately.
Thanks for the hint that it's a mistaken script.
