### ISSUE TITLE
Updating previously downloaded profile with comments

### ISSUE THREAD

**Issue by aaaxx** [instaloader/instaloader#93]
I tried to download comments for a previously downloaded profile, adding the `--comments --fast-update` options to the standard download command, but that fails on the first picture, saying "unchanged comments". Am I doing something wrong or is it impossible to download such additional content separately from the pictures?

**Comment by aandergr** [comment]
` --fast-update` instructs Instaloader to abort when it reaches the first picture that has already been saved on your disk. It is useful for fastly downloading the latest posts, i.e. the ones that you don't yet have.

In your case, since Instaloader would have to go through all online posts of that particular target, you cannot use `--fast-update`. Even without that flag, Instaloader notices that files are already there and does not download them again, however, the time intensive part is iterating through the Profile to obtain all the metadata that is required, which it would do unless `--fast-update` is given.
