### ISSUE TITLE
400 Bad Request Unable to fetch high quality image version

### ISSUE THREAD

**Issue by jlntrt** [instaloader/instaloader#942]
**Describe the bug**
Since yesterday, instaloader shows me the message that images can't be downloaded of any account. 
```
400 Bad Request Unable to fetch high quality image version of <Post CILxBBQpRjF>
```

**To Reproduce**
```
instaloader --sessionfile ../session --login=xy --password=123 --stories --fast-update --no-profile-pic $(ls -d * | shuf -n 8)
```

**Expected behavior**
High quality images should be downloaded (guess what ;) )

**Error messages and tracebacks**
/

**Instaloader version**
4.5.5

**Additional context**
The special in this case is, that I run instaloader with 3 different instagram accounts. Only one of them shows this message.

**Comment by bebunw** [comment]
this is not a bug, you got **flagged for supicious activity by instagram**, maybe because you run multiple parrallel instaloader with same ip adress even if it's different accounts, like i dit with vpn, i got  same error on several account during the last 2 weeks, they ask to change password ect, then i kept downloading then i lost these account the moment they ask for phone number validation (temp phone number will not work), i thought the rule was no parallele download with one account but it was also no parallel download with one ip i think. its takes a hell lot of time to update my database with just one instaloader as it stop after around 100 requests or so. Also Instagram has been stricter lately, i can't create new accounts with vpn and temp mail anymore. I might stop hoarding instagram considering the current state, not worth the effort you are getting into

**Comment by alesservin** [comment]
This happens to me when I log out from Instagram on the PC I used to create the session file (I'm not sure why). What I do when this happens is: Login on Instagram with firefox, create the session file with [this script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py), and then use the created session file to log in. It's important that you don't log out from your instagram account on Firefox, you can close Firefox, but not log out from Instagram. 

It's a little trick I found out, I'm not sure if this will work for you, but give it a try. I hope it helps.

**Comment by jlntrt** [comment]
@bebunw and @alesservin **many thanks** you both. I'm going to try it with the firefox-script.

**Comment by Showmaster3000** [comment]
I have similiar problems since about two weeks. Before I easily could download all of the (over 150) interesting profiles with two or three accounts.
My current setup which is working since about three days consists of 8 download accounts/logins, which are not used more then 5-6 times per hour. If I use them more often, the account will be flagged with error 400 after about one day. Trying to reactivate them requires entering a mobile(!) phone number. Be careful not to use one mobile number for more than one account, which permanently burns the number as well as the accounts.
Concerning the connection: I currently use a provider dialin with public ipv4-address (and disabled ipv6) which changes on reconnect but I do not reconnect very often.

**Comment by MrJmpl3** [comment]
> This happens to me when I log out from Instagram on the PC I used to create the session file (I'm not sure why). What I do when this happens is: Login on Instagram with firefox, create the session file with [this script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py), and then use the created session file to log in. It's important that you don't log out from your instagram account on Firefox, you can close Firefox, but not log out from Instagram.
> 
> It's a little trick I found out, I'm not sure if this will work for you, but give it a try. I hope it helps.

I tried that, and still persist the error. With 4.5.5 version, don't exists that error, maybe because the high quality, and the new version 4.6 hit "Too many queries in the last time." so quick

**Comment by parasiteoflife** [comment]
I'm getting the same error and my account has just been blocked, I don't remember how many times it has been. I haven't used Instagram while instaloader was scraping the profiles, in fact I don't use Instagram at all, I only have an account for the profiles that are private and I haven't ran multiple instances of instaloader so my account was locked solely by instaloader's behavior.

**Comment by irvinm** [comment]
@Showmaster3000 I am just curious how you created IG accounts without a phone number for each account.  Everything I tried eventually asked me for a phone number.

**Comment by parasiteoflife** [comment]
> @Showmaster3000 I am just curious how you created IG accounts without a phone number for each account. Everything I tried eventually asked me for a phone number.

I have also created multiple accounts and it didn't ask me for a phone number, perhaps it has something to do with the country?

**Comment by irvinm** [comment]
@parasiteoflife thanks!

**Comment by Showmaster3000** [comment]
I can't say anything about the reasons, but I noticed that creating/registering by web browser fails for me. I use smartphone/tablet app. Most of the time it works fine. Anyway you need a bunch of email-addresses - one for each account you create.

**Comment by bebunw** [comment]
@Showmaster3000 

Did you used email accounts that ask your phone number, "officials" mails domain like gmail, hotmail, outlook, yahou ect ... ? 
Or did you use tempmail adresses on smartphone & tablet ?

**Comment by Showmaster3000** [comment]
@bebunw no freemail services like you mentioned. I currently use my own domains with alias names forwarding to my mailbox. You need it at least for getting the activation code.
temp addresses/domains are probably blocked by Instagram but didn't try that.

**Comment by christoarmani** [comment]
I am now getting this error message when I am logged in. I have tried two different accounts.
