### ISSUE TITLE
Use cookies of multiple accounts parallel?

### ISSUE THREAD

**Issue by TravelTrader** [instaloader/instaloader#954]
When I am logged into my account in firefox, I use the import cookie script to save the session file and then I can use this to run my instaloader codes.

But when I want to connect to another account of mine. I have to change the account in firefox, run the import cookie script again and then it works.

Is there anything faster?
How can I load multiple session cookies at the same time?
Or use several accounts without always having to run the import cookie scripts?

If it's not possible, is there a way to import cookies from different browsers (firefox, chrome, ..) while being logged into different accounts on each browser?

Thank you and still a healthy and happy year 2021!

**Comment by Showmaster3000** [comment]
You can use multiple accounts at the same time (but I'm unsure if you can run them parallel, I currently have huge problems concerning account things in the last weeks).
If you grab the cookies from firefox, they are saved in a session file which you can use a long time. But as I remember, somebody said, that you need to avoid to logout from that account in firefox.
The export script only supports firefox. If you HAVE to use the session export, then you can create different profiles in firefox, one for each instagram account. Log in (and stay logged in), then export all sessions using the script.
See here for details: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
If you have problems exporting all sessions, check the parameters of the export script to get what you want.

**Comment by Deleora** [comment]
**OR**
If you don't wanna go through the headache of creating multiple browser profiles for each account, (I've not tried this) maybe you can simply clear the cookies of Instagram (from site settings) after you have grabbed them into a session file. Then refresh the page and login to another account and repeat the step. So this way you can have all the session files required and since you DIDN'T logout (only deleted them from browser side), the cookies should still be valid for Instaloader to use.
**OR**
You can login using the Instaloder CLI which will create the session files without any problems.

And later you can probably write a script to do whatever you want using the session files
