### ISSUE TITLE
Archive file of ids

### ISSUE THREAD

**Issue by AplhaSlayer1964** [instaloader/instaloader#996]
**Provide us a use case of the feature**
Every time an image is downloaded it's id is saved to a file which can be referenced by instaloader to not re download that image.

**Describe the solution you'd like**
Instaloader has some type of archive file for storing already downloaded images

**Describe alternatives you've considered**
fast update and resume prefix both seem like they should already do this partially. Both seem to have problems. First fast update stops the download after one match but if the download was stopped before all older posts had been downloaded they will neve be downloaded. Second resume prefix only works when the user interrupts the download. When downloading multiple accounts and trying to make sure they are up to date instagram will lock my account causing the downloads to stop and neither solution listed would help with that.

**If the feature request is accepted, would you be willing to submit a pull request?**
No sorry I don't know python well enough to not make something terrible

**Additional context**
Something like what youtube-dl does would be nice. This might save on api calls as you would only call for id's that are not in the archive file? I don't know how the api calls are made or work so I don't know if this is the case.

**Comment by aandergr** [comment]
There is no additional value in saving the ids in an extra archive file, since Instaloader already does create a file for each post. This is sufficient to determine whether a post is already downloaded or not.

Instaloader goes through the media online, determines the filenames that would be generated for that media, and skips each media if it already exists in the target's folder locally.

Instaloader was really slow when going through a target that had most posts already downloaded, because it erroneously did some unnecessary metadata fetches. We fixed that efficiency bug with 672b0b184019bf840e3003e90a1c662fcb4df79a, currently in the `upcoming/v4.7` branch.

This can be installed with:
```
pip3 install --upgrade git+https://github.com/instaloader/instalaoder@upcoming/v4.7
```

**Comment by AplhaSlayer1964** [comment]
Does it only do this when --remuse-prefix is used?

**Comment by aandergr** [comment]
`--resume-prefix` only changes the filenames of the iterator files. It does not enable or disable any feature.

Instaloader always checks which files are already present locally and only downloads missing media. This cannot be disabled by any flag.
